/*
 * fuzz_manifest.c — manifest parser fuzz harness (fuzz wave 4/4).
 *
 * Feeds malformed codecpack manifests through the REAL registration path
 * (pack_scan_dir -> parse_manifest -> pack_register, all inside codec.o)
 * by pointing INVFS_CODECPACKS at a temp dir holding exactly one
 * fixture .codecpack per case, calling invfs_codec_probe_reset() and then
 * forcing a registry rebuild (invfs_codec_all). After each registration
 * the registry is exercised: probe() every codec (access() checks over
 * the fuzzed argv templates) and sniff() with a random head buffer and a
 * fuzzed filename (exercises the fuzzed sniff.magic/sniff.ext rules).
 *
 * The exec hooks are stubs (the codec_test.c convention): no fuzzed argv
 * is ever executed.
 *
 * INVARIANT: registration never crashes and never half-registers; a
 * registered pack has a nonempty name and algo < 64 (the AST field
 * bound pack_register documents). A crash aborts the process; the last
 * "CASE nnnnn" line on stdout names the culprit, and the manifest is
 * kept at <cases>/case_nnnnn.manifest (also regenerated by --only N).
 *
 * Build (tools/test-fuzz.sh does this):
 *   gcc -std=gnu11 -O2 -I src -o fuzz_manifest \
 *       tools/fuzz/fuzz_manifest.c build/obj/{codec,ppmd8,ppmd8enc,\
 *       ppmd8dec,ppmd_codec,lz4,bcj_x86}.o -Wl,-l:libzstd.so.1 -lz -lpthread
 *
 * Run:  fuzz_manifest [iterations=200] [seed=0xCAFE] [--only N]
 */
#define _CRT_SECURE_NO_WARNINGS

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "codec.h"
#include "invarifs.h"

/* ---- stubs for the volume.c exec hooks (never called by the fuzz legs,
 * but codec.o references the symbol) ---- */
int invfs_codec_pack_exec(const invfs_codec *c, int is_encode,
                          const char *in_path, const char *out_path)
{
    (void)c; (void)is_encode; (void)in_path; (void)out_path;
    return -1;
}

int invfs_codec_pack_estimate(const invfs_codec *c, const char *in_path,
                              uint64_t *out_bytes)
{
    (void)c; (void)in_path; (void)out_bytes;
    return -1;
}

int invfs_codec_pack_cmd(const invfs_codec *c, int cmd,
                         const char *in, const char *idx,
                         const char *dir, const char *recipe,
                         const char *out)
{
    (void)c; (void)cmd; (void)in; (void)idx; (void)dir; (void)recipe;
    (void)out;
    return -1;
}

/* ---- deterministic PRNG (xorshift64*) ---- */
static uint64_t g_s;
static uint64_t xr(void)
{
    uint64_t x = g_s;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    g_s = x;
    return x * 0x2545F4914F6CDD1Dull;
}
static unsigned rr(unsigned n) { return n ? (unsigned)(xr() % n) : 0; }

/* ---- base manifests (the real rawdisk container pack + a codec-pack
 * flavor), mutated per case ---- */
static const char BASE_CONTAINER[] =
    "# comment line\n"
    "name = rawdisk\n"
    "type = container\n"
    "algo = 16\n"
    "pack_version = 1\n"
    "generation = 1\n"
    "caps = container|external\n"
    "dec_mem = 0\n"
    "sniff.magic = 4546492050415254\n"
    "sniff.offset = 512\n"
    "sniff.magic = 55AA\n"
    "sniff.offset = 510\n"
    "sniff.ext = img,raw\n"
    "enumerate = rawdisk enumerate {in} {out}\n"
    "extract = rawdisk extract {in} {idx} {out}\n"
    "strip = rawdisk strip {in} {out}\n"
    "rebuild = rawdisk rebuild {recipe} {dir} {out}\n"
    "map = rawdisk map {in} {out}\n"
    "estimate = rawdisk estimate {in}\n";

static const char BASE_CODEC[] =
    "name = fakeimg\n"
    "algo = 42\n"
    "pack_version = 2\n"
    "generation = 3\n"
    "caps = external|wholefile\n"
    "dec_mem = 67108864\n"
    "sniff.magic = DEADBEEF\n"
    "sniff.offset = 4\n"
    "sniff.ext = fake,fk\n"
    "encode = fakeimg encode {in} {out}\n"
    "decode = fakeimg decode {in} {out}\n";

static const char *KEYS[] = {
    "name", "type", "algo", "pack_version", "generation", "caps",
    "dec_mem", "sniff.magic", "sniff.offset", "sniff.ext", "requires",
    "encode", "decode", "estimate", "enumerate", "extract", "strip",
    "rebuild", "map", "bogus.key", "", "na me",
};

/* a manifest case buffer (64 KiB cap: far past any parser line cap) */
static char g_buf[64 * 1024];
static size_t g_len;

static void emit(const char *s, size_t n)
{
    if (g_len + n >= sizeof g_buf) n = sizeof g_buf - 1 - g_len;
    memcpy(g_buf + g_len, s, n);
    g_len += n;
    g_buf[g_len] = '\0';
}

static void gen_case(unsigned which)
{
    const char *base = (which & 1) ? BASE_CODEC : BASE_CONTAINER;
    size_t blen = strlen(base), i, nflip;
    unsigned style = rr(100);

    g_len = 0;
    emit(base, blen);

    if (style < 30) {
        /* random byte flips anywhere (may land inside any field) */
        nflip = 1 + rr(32);
        for (i = 0; i < nflip; i++)
            g_buf[rr((unsigned)g_len)] = (char)rr(256);
    } else if (style < 45) {
        g_len = rr((unsigned)g_len);            /* truncate */
        g_buf[g_len] = '\0';
    } else if (style < 60) {
        /* inject raw bytes (incl. NUL) at a random point */
        size_t at = rr((unsigned)g_len), n = 1 + rr(24), j;
        char ins[32];
        for (j = 0; j < n; j++) ins[j] = (char)rr(256);
        if (g_len + n < sizeof g_buf) {
            memmove(g_buf + at + n, g_buf + at, g_len - at);
            memcpy(g_buf + at, ins, n);
            g_len += n;
        }
    } else if (style < 75) {
        /* huge / adversarial values on random known keys */
        char line[4200];
        const char *k = KEYS[rr(sizeof KEYS / sizeof KEYS[0])];
        size_t n = 1 + rr(4000), j;
        int nul = rr(4) == 0;
        snprintf(line, sizeof line, "\n%s = ", k);
        j = strlen(line);
        for (i = 0; i < n && j + 2 < sizeof line; i++)
            line[j++] = nul && rr(8) == 0 ? '\0' : (char)('!' + rr(94));
        line[j++] = '\n';
        emit(line, j);
    } else if (style < 85) {
        /* whitespace / CR perversion on every line boundary */
        size_t j;
        for (j = 0; j + 1 < g_len; j++)
            if (g_buf[j] == '\n' && rr(3) == 0) {
                memmove(g_buf + j + 2, g_buf + j + 1, g_len - j - 1);
                g_buf[j + 1] = rr(2) ? '\r' : '\t';
                if (++g_len >= sizeof g_buf) break;
            }
    } else if (style < 95) {
        /* duplicate-key storm */
        char line[600];
        const char *k = KEYS[rr(sizeof KEYS / sizeof KEYS[0])];
        for (i = 0; i < 5 + rr(20); i++) {
            int n = snprintf(line, sizeof line, "%s=%llu\n", k,
                             (unsigned long long)xr());
            emit(line, (size_t)n);
        }
    } else {
        /* a completely random blob */
        g_len = rr(8192);
        for (i = 0; i < g_len; i++) g_buf[i] = (char)rr(256);
        g_buf[g_len] = '\0';
    }
}

int main(int argc, char **argv)
{
    unsigned iterations = 200, i;
    int only = -1;
    char cases[4096], packdir[4400], mpath[4608];
    const char *cases_env;

    g_s = 0x9E3779B97F4A7C15ull;
    if (argc > 1) iterations = (unsigned)strtoul(argv[1], NULL, 0);
    if (argc > 2) g_s ^= strtoull(argv[2], NULL, 0) * 0x100000001B3ull;
    if (argc > 3 && strcmp(argv[3], "--only") == 0 && argc > 4) {
        only = atoi(argv[4]);
        if (only >= 0 && (unsigned)only >= iterations)
            iterations = (unsigned)only + 1;
    }
    if (!g_s) g_s = 1;

    cases_env = getenv("INVFS_FUZZ_CASES");
    snprintf(cases, sizeof cases, "%s",
             cases_env ? cases_env : "/dev/shm/invf-fuzz-manifest");
    snprintf(packdir, sizeof packdir, "%s/fz.codecpack", cases);
    snprintf(mpath, sizeof mpath, "%s/manifest", packdir);
    mkdir(cases, 0755);
    mkdir(packdir, 0755);
    setenv("INVFS_CODECPACKS", cases, 1);

    printf("fuzz_manifest: %u iterations, seed base %#llx\n",
           iterations, (unsigned long long)g_s);
    for (i = 0; i < iterations; i++) {
        if (only >= 0 && (int)i != only) continue;
        FILE *f;
        char cpath[4800];
        size_t n, k;
        const invfs_codec *all;

        gen_case(i);
        snprintf(cpath, sizeof cpath, "%s/case_%05u.manifest", cases, i);
        f = fopen(cpath, "wb");
        if (!f) { perror("case file"); return 2; }
        fwrite(g_buf, 1, g_len, f);
        fclose(f);
        f = fopen(mpath, "wb");
        if (!f) { perror("manifest"); return 2; }
        fwrite(g_buf, 1, g_len, f);
        fclose(f);

        printf("CASE %05u (%zu bytes)\n", i, g_len);
        fflush(stdout);

        invfs_codec_probe_reset();
        all = invfs_codec_all(&n);   /* forces the pack scan + register */
        if (!all || n == 0 || n > 256) {
            fprintf(stderr, "FAIL case %u: registry size %zu\n", i, n);
            return 1;
        }
        for (k = 0; k < n; k++) {
            const invfs_codec *c = &all[k];
            const invfs_pack_def *def;
            static uint8_t head[512];
            char fname[64];
            unsigned h;
            int score;

            if (!c->name || !c->name[0] || c->algo >= 64) {
                fprintf(stderr, "FAIL case %u: half-registered entry "
                        "(name=%p algo=%u)\n", i, (void *)c->name, c->algo);
                return 1;
            }
            if (c->probe) c->probe();   /* availability: access() only */
            for (h = 0; h < sizeof head; h++) head[h] = (uint8_t)xr();
            snprintf(fname, sizeof fname, "f%llu.%s",
                     (unsigned long long)(xr() & 0xFFFF),
                     rr(2) ? "img" : "fake");
            if (c->sniff) {
                score = c->sniff(head, rr((unsigned)sizeof head), fname);
                if (score < 0 || score > 100) {
                    fprintf(stderr, "FAIL case %u: sniff score %d out of "
                            "range for %s\n", i, score, c->name);
                    return 1;
                }
            }
            def = invfs_codec_pack_def(c);
            (void)def;
        }
        (void)invfs_codec_by_algo(rr(64));
        (void)invfs_registry_generation();
        /* keep the case file only while --only debugging; else refresh */
        if (only < 0) unlink(cpath);
    }
    printf("fuzz_manifest: %u cases, no crash, registry consistent\n",
           iterations);
    return 0;
}
