.TH INVF-RESIZE 8 "2026-09" "InvariantFS" "System Administration"
.SH ИМЯ
invf\-resize \(em увеличение или уменьшение тома InvariantFS оффлайн
.SH СИНТАКСИС
.B invf\-resize
.IR image | device
.IR newsize [ K | M | G ]
.SH ОПИСАНИЕ
.B invf\-resize
изменяет размер тома InvariantFS (WP18). Том должен быть не смонтирован.
.I newsize
\(em размер в байтах с необязательным суффиксом K/M/G, округляемый вниз
до целого блока; минимальный размер тома \(em 64 MiB.
.PP
Изменение размера этапируется как запись RSZ0 и выполняется
идемпотентно при следующем открытии тома, поэтому прерванное изменение
просто продолжается.
.PP
Для двух\-устройственных томов (WP25)
.I newsize
\(em общий размер обоих устройств; рост попадает на последнее устройство
(dev1, указанное переменной окружения
.B INVFS_DEV1
или подсказкой, записанной при mkfs). Уменьшение двух\-устрой\-ственного
тома отклоняется.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
.TP
.B INVFS_DEV1
Путь второго устройства двух\-устройственного тома.
.SH КОД ВОЗВРАТА
0 при успехе; 1 при ошибках (слишком маленькая цель, сбой ввода\-вывода,
отказ); 2 при ошибках параметров.
.SH СМОТРИТЕ ТАКЖЕ
.BR invf\-mkfs (8),
.BR invarifs (7)
