.TH INVF-LS 1 "2026-09" "InvariantFS" "User Commands"
.SH ИМЯ
invf\-ls, invf\-cat, invf\-cp, invf\-stat \(em утилиты чтения для томов InvariantFS
.SH СИНТАКСИС
.B invf\-ls
.I image
.br
.B invf\-cat
.I image
.I name
.RI [ output\-file ]
.br
.B invf\-cp
.I image
.I host\-file
.RI [ name\-in\-volume ]
.br
.B invf\-stat
.I image
.RB [ \-\-files ]
.SH ОПИСАНИЕ
Эти утилиты читают данные из тома InvariantFS без монтирования FUSE.
Они работают напрямую с файлом\-образом или блочным устройством тома.
.SS invf\-ls
Выводит список всех активных файлов на томе с указанием размера,
номера иноды и имени. Для файлов\-контейнеров выводятся виртуальные
окна (члены контейнера).
.SS invf\-cat
Извлекает именованный файл из тома в
.IR output\-file
или в stdout, если не указан. Для имён\-членов контейнеров, содержащих
.BR ! ,
сначала выполняется поиск по иноде, затем извлечение члена контейнера.
.SS invf\-cp
Копирует файл хоста в том. Если
.I name\-in\-volume
не указан, используется имя файла хоста. Если имя уже существует,
старое содержимое перезаписывается.
.SS invf\-stat
Отображает визуальную диаграмму блоков с ANSI\-цветами по категориям
(RAW, семантическая, дедупликация, свободно) и сводку по населению.
.IP "\fB\-\-files\fR" 4
Дополнительно выводит список файлов с тегом политики и размером.
.SH КОД ВОЗВРАТА
Все четыре утилиты возвращают 0 при успехе, 1 при ошибках ввода\-вывода
или тома, 2 при ошибках параметров.
.SH СМОТРИТЕ ТАКЖЕ
.BR invf\-fuse (8),
.BR invf\-sweep (8),
.BR invarifs (7)
