.TH INVF-IMPORT 8 "2026-09" "InvariantFS" "System Administration"
.SH ИМЯ
invf\-import \(em массовый импорт дерева каталогов в том InvariantFS
.SH СИНТАКСИС
.B invf\-import
.I volume
.I src\-dir
.RI [ exclude\-dir\-name ...]
.SH ОПИСАНИЕ
.B invf\-import
рекурсивно импортирует дерево каталогов хоста в не смонтированный том
InvariantFS на уровне движка (без монтирования FUSE). Создаёт каталоги,
обычные файлы, символические ссылки и специальные узлы (FIFO, сокет,
символьные и блочные устройства) с полными метаданными формата v2
(тип, режим, uid/gid, mtime/atime).
.PP
Необязательные аргументы в конце задают имена каталогов, исключаемых
из обхода (например,
.BR \.git " " node_modules ).
Максимальная глубина рекурсии \(em 32.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
.TP
.B INVFS_IMPORT_PREFIX
Если задана, импорт выполняется в подкаталог существующего тома вместо
корня. Целевой каталог должен уже существовать.
.TP
.B INVFS_IMPORT_KEEP_OWNER
Если равна 1, сохраняет uid/gid исходного файла. По умолчанию (0) все
файлы создаются от имени root (uid=0, gid=0).
.SH КОД ВОЗВРАТА
0 при успехе (пропущенные записи не являются ошибкой); 1 при ошибках
открытия или повреждения суперблока; 2 при ошибках параметров.
.SH СМОТРИТЕ ТАКЖЕ
.BR invf\-mkfs (8),
.BR invf\-sweep (8),
.BR invarifs (7)
