.TH INVF-MKFS 8 "2026-09" "InvariantFS" "System Administration"
.SH ИМЯ
invf\-mkfs \(em создание тома InvariantFS
.SH СИНТАКСИС
.B invf\-mkfs
.IR image | device
.RI [ size_gb ]
.PP
.B invf\-mkfs
.IR dev0 " " size0_gb " " dev1 " " size1_gb
.SH ОПИСАНИЕ
.B invf\-mkfs
форматирует файл или блочное устройство как том InvariantFS. InvariantFS \(em
семантическая, адресуемая по содержимому файловая система с инвариантом
бит\-в\-бит: каждое сжатие проверяется декодированием и сравнением
перед доверием. См.
.BR invarifs (7)
для обзора формата.
.PP
Для обычного файла
.I image
том имеет размер
.I size_gb
ГиБ (по умолчанию 4, допускаются дробные значения); файл является
разреженным. Для блочного
.I устройства
используется всё устройство, если
.I size_gb
не ограничивает его; устройство открывается эксклюзивно (блокируется и
размонтируется) во время форматирования.
.PP
Четырёх\-аргументная форма создаёт двух\-устройственный том (WP25):
.I dev0
\(em быстрое устройство (метаданные + RAW\-зона + файеринг) и
.I dev1
\(em ёмкостное устройство (зеркало метаданных + тень). Одно\-устройственные
образы, созданные двух\-аргументной формой, остаются байт\-идентичными
историческому макету.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
.TP
.B INVFS_META_FRAC
Масштаб зоны метаданных: по умолчанию 1/64 тома;
.B INVFS_META_FRAC=16
занимает 1/16 (рекомендуется для нагрузок с частыми изменениями).
.SH КОД ВОЗВРАТА
0 при успехе; 1 при ошибках ввода\-вывода или ёмкости; 2 при ошибках
параметров.
.SH ПРИМЕРЫ
.nf
invf\-mkfs vol.img 10          # 10 GiB разреженный образ
invf\-mkfs /dev/sdb            # всё разделение
invf\-mkfs fast.img 4 slow.img 32   # двух\-устройственный том
.fi
.SH СМОТРИТЕ ТАКЖЕ
.BR invf\-fuse (8),
.BR invf\-sweep (8),
.BR invf\-verify (8),
.BR invarifs (7)
