#!/usr/bin/env bash
# Regenerate the ctags-derived impl_docs: FUNCTIONS.md, TYPES.md,
# functions/*.txt, types/*.txt.
#
# Scope note (2026-08-31): the generated set is ONLY those four artifacts.
# AUDIT.md, FILEMAP.md, DOCMAP.md and WP*.md are hand-maintained — an earlier
# version of this script did `rm -rf "$OUT"` and would have destroyed them;
# never do that again. FILEMAP.md/DOCMAP.md used to be generated here; they
# are curated documents now (FILEMAP describes the post-split vol_* module
# layout, which a wc -l listing cannot).
#
# 2026-09-18: the script additionally drives doxygen (repo-root Doxyfile) to
# produce impl_docs/doxygen/html. That tree is gitignored and additive; the
# four ctags artifacts above stay the committed, hand-diffable index.
set -euo pipefail

ROOT="/home/user/InvariantFS"
SRC="$ROOT/src"
OUT="$ROOT/impl_docs"

# Wipe and rebuild ONLY the generated artifacts.
rm -rf "$OUT/functions" "$OUT/types" "$OUT/FUNCTIONS.md" "$OUT/TYPES.md"
mkdir -p "$OUT/functions" "$OUT/types"

# 2026-09-04 restructure: sources live in per-role subdirs (core/ codecs/
# recipes/ cli/ vendor7z/ legacy/); the top level only keeps vendored zstd.h
# and the zlib/, zstd-1.5.6/, examples/ trees (still out of scope, as before).
shopt -s nullglob
SRCFILES=("$SRC"/*.c "$SRC"/*.h)
for d in core codecs recipes cli vendor7z legacy; do
  SRCFILES+=("$SRC/$d"/*.c "$SRC/$d"/*.h)
done

# Function index: every source file (the post-split vol_*.c modules are
# covered by the same glob).
for f in "${SRCFILES[@]}"; do
  b=$(basename "$f")
  ctags -x --c-kinds=f "$f" > "$OUT/functions/${b}.txt" || true
done

{
  echo "# Function Index (all sources)"
  echo
  echo "Generated by tools/gen_impl_docs.sh — do not edit by hand."
  echo
  echo "| symbol | kind | line | file |"
  echo "|---|---|---|---|"
  cat "$OUT"/functions/*.txt | awk '{n=$4; sub(/.*\//,"",n); print "| "$1" | "$2" | "$3" | "n" |"}'
} > "$OUT/FUNCTIONS.md"

# Type index: headers AND all .c files — post-split, module-local structs
# live in the vol_*.c units (e.g. vol_sweep.c's sweep_seed), not just in
# volume.c/fuse_fs.c/blkio.c as the old list assumed.
for f in "${SRCFILES[@]}"; do
  b=$(basename "$f")
  ctags -x --c-kinds=stgu "$f" > "$OUT/types/${b}.txt" || true
done

{
  echo "# Type Index (structs/unions/enums/typedefs)"
  echo
  echo "Generated by tools/gen_impl_docs.sh — do not edit by hand."
  echo
  echo "| name | kind | line | file |"
  echo "|---|---|---|---|"
  cat "$OUT"/types/*.txt | awk '{n=$4; sub(/.*\//,"",n); print "| "$1" | "$2" | "$3" | "n" |"}' | sort -t'|' -k2
} > "$OUT/TYPES.md"

ls "$OUT"

# ---- doxygen HTML browser (additive) -------------------------------------
# ctags gives the flat FUNCTIONS/TYPES indexes above; doxygen gives the
# browsable tree + call graphs. Output goes to impl_docs/doxygen/ (gitignored)
# and is driven by the repo-root Doxyfile. Skip quietly when doxygen is not
# installed or INVFS_DOCS_NO_DOXYGEN=1 (e.g. minimal CI images).
if [ "${INVFS_DOCS_NO_DOXYGEN:-0}" != 1 ] && command -v doxygen >/dev/null 2>&1 \
   && [ -f "$ROOT/Doxyfile" ]; then
    ( cd "$ROOT" && doxygen Doxyfile )
    echo "doxygen: impl_docs/doxygen/html/index.html"
else
    echo "doxygen: skipped (not installed or INVFS_DOCS_NO_DOXYGEN=1)"
fi
