#!/bin/bash
# test-migrate-v2.sh — WP27 e2e: the offline format v1 -> v2 converter
# (invf-migrate-v2) and the v2 refusal gate. Persistent regression suite.
#
# There are no v1 fixture images in-repo (the format predates this tree's
# history), so the suite SYNTHESIZES them: a generated engine harness
# builds a v2 volume (plain/compressible/meta+xattr/renamed/deleted/empty
# files + swept text-batch members, i.e. a non-empty owner WAL), then
# DOWNGRADES it byte-level to format v1 (32B -> 24B entries, the full L2P
# journal rebuilt from the records, heat folded into journal pads,
# VOLF_ASTV2 cleared, journal back to the legacy flat log). The converter
# under test then reads exactly what a field v1 volume would carry.
#
#   Leg A (convert): downgrade -> invf-migrate-v2 -> harness verify
#     (bit-exact reads, meta/xattr carried, heat TLV folded from the pads,
#     WAL owner-only, VOLF_ASTV2 set) -> fsck clean -> v1-refusal leg
#     (vol_open of the un-converted image fails loudly, pointing at the
#     converter).
#   Leg B (crash protocol): INVFS_MIGRATE_ABORT_AT = staged | armed |
#     applied -> kill -> re-run completes -> verify.
#   Leg C (--abort): arm, kill, disarm -> the volume is back to v1
#     (superblock CLEAN, no ASTV2) -> a fresh conversion succeeds.
#
# Run from the repo root after `make`:  bash tools/test-migrate-v2.sh
# Uses /dev/shm (tmpfs) like the other soak scripts; image paths are
# RELATIVE (blkio treats /dev/* as raw devices).
set -e
set -o pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
B=$REPO/bin
WORK=/dev/shm/wp27migrate
rm -rf "$WORK" && mkdir -p "$WORK"
cd /dev/shm
rm -f wp27m-*.img

fail() { echo "FAIL: $*" >&2; exit 1; }

# ---- the engine harness ------------------------------------------------
CORE="volume vol_cpack vol_png vol_seal vol_repair vol_rollback \
      vol_resize vol_fsck vol_crash vol_exer vol_dedupe vol_textzone \
      vol_heat vol_sweep vol_read vol_write vol_records vol_ast \
      vol_dirs arc crc32c lz4 flacx tarx pngx blkio miniz blake3 \
      blake3_dispatch blake3_portable ppmd8 ppmd8enc ppmd8dec \
      ppmd_codec codec bcj_x86 rs vol_tier vol_meta_merge"
OBJS=""
for m in $CORE; do OBJS="$OBJS $REPO/build/obj/$m.o"; done

cat > "$WORK/mig2_harness.c" <<'EOF'
/* mig2_harness.c — WP27 converter test driver (generated by
 * tools/test-migrate-v2.sh; links the engine objects).
 *
 *   populate <img>   write the test tree into a fresh v2 image
 *   downgrade <v2> <v1>  rewrite a copy as format v1 (24B entries, full
 *                    L2P flat journal with heat pads, VOLF_ASTV2 cleared)
 *   verify <img>     assert the converted volume: content bit-exact,
 *                    meta/xattrs carried, heat TLV, owner-only WAL
 *
 * Content is deterministic (xorshift64 seeds / word soup), so verify
 * regenerates it -- no manifest file needed. */
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "volume.h"
#include "invarifs.h"
#include "blkio.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

static uint64_t xs64(uint64_t *st)
{
    uint64_t x = *st;
    x ^= x >> 12; x ^= x << 25; x ^= x >> 27;
    *st = x;
    return x * 0x2545F4914F6CDD1DULL;
}

static uint8_t *gen_bin(uint64_t seed, size_t n)
{
    uint8_t *b = malloc(n ? n : 1);
    size_t i;
    if (!b) die("oom");
    for (i = 0; i < n; i++)
        b[i] = (uint8_t)(xs64(&seed) >> 32);
    return b;
}

/* compressible binary: a repeating 256-byte block with a counter */
static uint8_t *gen_comp(uint64_t seed, size_t n)
{
    uint8_t *b = malloc(n ? n : 1);
    size_t i;
    uint8_t blk[256];
    if (!b) die("oom");
    for (i = 0; i < 256; i++) blk[i] = (uint8_t)(xs64(&seed) >> 32);
    for (i = 0; i < n; i++)
        b[i] = (uint8_t)(blk[i & 255] ^ (uint8_t)(i >> 12));
    return b;
}

/* word-soup text (sniffs as text; PPMd-batchable) */
static uint8_t *gen_text(uint64_t seed, size_t n)
{
    static const char *W[] = {
        "alpha","beta","gamma","delta","epsilon","zeta","eta","theta",
        "iota","kappa","lambda","mu","nu","xi","omicron","pi"
    };
    uint8_t *b = malloc(n ? n : 1);
    size_t o = 0;
    if (!b) die("oom");
    while (o < n) {
        const char *w = W[xs64(&seed) % 16];
        size_t wl = strlen(w);
        if (o + wl + 1 > n) break;
        memcpy(b + o, w, wl);
        o += wl;
        b[o++] = (xs64(&seed) % 7 == 0) ? '\n' : ' ';
    }
    while (o < n) b[o++] = '\n';
    return b;
}

static void wr(invfs_volume *v, const char *name, const uint8_t *d, size_t n)
{
    if (!vol_create_file(v, name, d, n)) die("create failed");
}

/* ---- the tree -------------------------------------------------------- */
static void populate(invfs_volume *v)
{
    uint8_t *b;
    wr(v, "empty.txt", NULL, 0);
    b = gen_text(11, 3000);  wr(v, "small.txt", b, 3000);  free(b);
    b = gen_bin(22, 200*1024);  wr(v, "big.bin", b, 200*1024);  free(b);
    b = gen_comp(33, 150*1024); wr(v, "comp.bin", b, 150*1024); free(b);
    b = gen_bin(44, 48*1024);   wr(v, "hot.bin", b, 48*1024);   free(b);
    b = gen_bin(55, 40*1024);   wr(v, "gone.bin", b, 40*1024);
    if (vol_delete_file(v, "gone.bin") != 0) die("delete failed");
    free(b);
    b = gen_bin(66, 24*1024);   wr(v, "oldname.bin", b, 24*1024); free(b);
    if (vol_rename(v, "oldname.bin", "renamed.bin") != 0)
        die("rename failed");
    /* meta + xattr carrier */
    b = gen_bin(77, 48*1024);
    wr(v, "meta.bin", b, 48*1024);
    free(b);
    {
        invfs_meta_pub m;
        uint64_t id = vol_find(v, "meta.bin");
        if (!id) die("meta.bin lost");
        memset(&m, 0, sizeof m);
        m.type = INVFS_ITYP_REG;
        m.mode = 0601;
        m.uid = 1234;
        m.gid = 4321;
        m.mtime = 1700000000;
        m.nlink = 1;
        if (!vol_apply_meta(v, "meta.bin", &m)) die("apply_meta failed");
        if (vol_set_xattr(v, id, "user.note", "hello-wp27", 10) != 0)
            die("set_xattr failed");
    }
    /* the batch candidates (a sweep batches these into the owner WAL) */
    {
        int i;
        for (i = 0; i < 8; i++) {
            char nm[32];
            snprintf(nm, sizeof nm, "txt%d.txt", i);
            b = gen_text(100 + (uint64_t)i, 2500 + (size_t)i * 500);
            wr(v, nm, b, 2500 + (size_t)i * 500);
            free(b);
        }
    }
}

/* ---- downgrade: v2 image -> v1 image -------------------------------- */

typedef struct { uint64_t pos, id; } dg_ver;
typedef struct {
    char name[256];
    uint32_t nlen;
    dg_ver *vers;
    uint32_t nvers, capvers;
} dg_name;
typedef struct { dg_name *n; size_t count, cap; } dg_live;

static dg_name *dg_find(dg_live *L, const char *name, uint32_t nlen)
{
    size_t i;
    for (i = 0; i < L->count; i++)
        if (L->n[i].nlen == nlen && !memcmp(L->n[i].name, name, nlen))
            return &L->n[i];
    return NULL;
}

static void dg_inod(dg_live *L, const char *name, uint32_t nlen,
                    uint64_t id, uint64_t pos)
{
    dg_name *e = dg_find(L, name, nlen);
    if (!e) {
        if (L->count == L->cap) {
            size_t nc = L->cap ? L->cap * 2 : 256;
            dg_name *nn = realloc(L->n, nc * sizeof *nn);
            if (!nn) die("oom");
            L->n = nn; L->cap = nc;
        }
        e = &L->n[L->count++];
        memset(e, 0, sizeof *e);
        memcpy(e->name, name, nlen);
        e->nlen = nlen;
    }
    if (e->nvers == e->capvers) {
        uint32_t nc = e->capvers ? e->capvers * 2 : 4;
        dg_ver *nv = realloc(e->vers, nc * sizeof *nv);
        if (!nv) die("oom");
        e->vers = nv; e->capvers = nc;
    }
    e->vers[e->nvers].pos = pos;
    e->vers[e->nvers].id = id;
    e->nvers++;
}

static void dg_delt(dg_live *L, const char *name, uint32_t nlen,
                    uint64_t id, uint64_t killpos)
{
    dg_name *e = dg_find(L, name, nlen);
    uint32_t i;
    if (!e || !e->nvers) return;
    if (!killpos) {
        if (e->vers[e->nvers - 1].id == id) { e->nvers = 0; return; }
        for (i = 0; i < e->nvers; i++)
            if (e->vers[i].id == id) {
                memmove(e->vers + i, e->vers + i + 1,
                        (e->nvers - i - 1) * sizeof *e->vers);
                e->nvers--;
                return;
            }
        return;
    }
    for (i = 0; i < e->nvers; i++)
        if (e->vers[i].pos == killpos) {
            memmove(e->vers + i, e->vers + i + 1,
                    (e->nvers - i - 1) * sizeof *e->vers);
            e->nvers--;
            return;
        }
}

/* v2pos -> v1pos (the v1 stream shrinks: 24B entries) */
typedef struct { uint64_t v2, v1; } posmap_ent;
static posmap_ent *posmap; static size_t posmap_n, posmap_cap;

static void posmap_put(uint64_t v2, uint64_t v1)
{
    if (posmap_n == posmap_cap) {
        size_t nc = posmap_cap ? posmap_cap * 2 : 256;
        posmap_ent *np = realloc(posmap, nc * sizeof *np);
        if (!np) die("oom");
        posmap = np; posmap_cap = nc;
    }
    posmap[posmap_n].v2 = v2; posmap[posmap_n].v1 = v1; posmap_n++;
}

static uint64_t posmap_get(uint64_t v2)
{
    size_t i;
    for (i = 0; i < posmap_n; i++)
        if (posmap[i].v2 == v2) return posmap[i].v1;
    return 0;
}

/* strip the invfs.heat TLV from an ext blob; *len shrinks in place */
static void dg_strip_heat(uint8_t *ext, size_t *len_io)
{
    static const char HN[] = INVFS_XATTR_HEAT;
    const size_t hn = sizeof(HN) - 1;
    invfs_meta_ext_hdr h;
    uint8_t *p, *out;
    size_t rem, w;
    if (*len_io < sizeof h) return;
    memcpy(&h, ext, sizeof h);
    if (h.magic != INVFS_META_MAGIC || h.ext_len > *len_io ||
        (size_t)sizeof h + h.target_len > h.ext_len)
        return;
    p = ext + sizeof h + h.target_len;
    rem = h.ext_len - sizeof h - h.target_len;
    out = p;
    w = 0;
    while (rem >= 4) {
        uint16_t nl, vl;
        size_t tsz;
        memcpy(&nl, p, 2);
        memcpy(&vl, p + 2 + nl, 2);
        tsz = (size_t)2 + nl + 2 + vl;
        if (tsz > rem || nl == 0) break;
        if (!(nl == hn && memcmp(p + 2, HN, hn) == 0)) {
            memmove(out + w, p, tsz);
            w += tsz;
        }
        p += tsz;
        rem -= tsz;
    }
    h.ext_len = (uint16_t)(sizeof h + h.target_len + w);
    memcpy(ext, &h, sizeof h);
    *len_io = sizeof h + h.target_len + w;
}

/* the framed extent of the segment at pba (the v1 map length) */
/* WP25-aware: a pba past dev0 lives on dev1 (the rawm owner's mirror
 * copies sit in the dev1 shadow) */
static blkio *g_io1;            /* dev1 when the DEVT says two-device */
static uint64_t g_dev0_blocks;
static blkio g_io1v;            /* the handle when open */

static uint64_t dg_extent(blkio *io, uint64_t pba)
{
    uint8_t hb[8];
    uint32_t csize;
    blkio *d = io;
    uint64_t off = pba * (uint64_t)INVFS_BLOCK_SIZE;
    if (g_io1 && g_dev0_blocks && pba >= g_dev0_blocks) {
        d = g_io1;
        off = (pba - g_dev0_blocks) * (uint64_t)INVFS_BLOCK_SIZE;
    }
    if (blkio_pread(d, off, hb, 8) != 0)
        die("extent read failed");
    memcpy(&csize, hb, 4);
    if (!csize) die("extent: empty frame");
    return ((uint64_t)csize + 8 + INVFS_BLOCK_SIZE - 1) / INVFS_BLOCK_SIZE;
}

static void downgrade(const char *v2path, const char *v1path)
{
    blkio v2, v1;
    invfs_superblock sb;
    uint64_t bm_blocks, jbase, iarea, iarea_end, p, v1pos;
    dg_live live;
    uint8_t *jrn;
    size_t jn;
    FILE *f;
    long fsz;
    int rc;

    memset(&live, 0, sizeof live);
    if (blkio_open(&v2, v2path, 0) != 0) die("open v2");
    /* WP25: if the source is two-device, the rawm owner's mirror copies
     * live on dev1 -- the journal synthesis reads segment frames there */
    g_io1 = NULL;
    g_dev0_blocks = 0;
    {
        invfs_devt dt;
        if (blkio_pread(&v2, INVFS_DEVT_OFF, &dt, sizeof dt) == 0 &&
            memcmp(dt.magic, "DEVT", 4) == 0) {
            invfs_devt t = dt;
            t.crc32c = 0;
            if (invfs_crc32c(&t, sizeof t) == dt.crc32c && dt.dev_count == 2) {
                const char *d1 = getenv("INVFS_DEV1");
                char hint[129];
                memset(hint, 0, sizeof hint);
                memcpy(hint, dt.dev1_hint, sizeof dt.dev1_hint);
                if (!d1 || !*d1) d1 = hint;
                if (d1 && *d1 &&
                    blkio_open(&g_io1v, d1, 0) == 0) {
                    g_io1 = &g_io1v;
                    g_dev0_blocks = dt.dev_blocks[0];
                }
            }
        }
    }
    if (blkio_pread(&v2, 0, &sb, sizeof sb) != 0) die("sb read");
    if (!(sb.vol_flags & VOLF_ASTV2)) die("source is not v2");
    bm_blocks = (sb.total_blocks / 8 + INVFS_BLOCK_SIZE - 1) /
                INVFS_BLOCK_SIZE;
    jbase = (sb.metadata_zone_start + bm_blocks) * (uint64_t)INVFS_BLOCK_SIZE;
    iarea = (sb.metadata_zone_start + bm_blocks + INVFS_JOURNAL_BLOCKS) *
            (uint64_t)INVFS_BLOCK_SIZE;
    iarea_end = (sb.metadata_zone_start + sb.metadata_zone_blocks) *
                (uint64_t)INVFS_BLOCK_SIZE;

    /* the v1 image starts as a byte copy of the v2 one */
    f = fopen(v2path, "rb");
    if (!f) die("fopen v2");
    if (fseek(f, 0, SEEK_END) != 0) die("fseek");
    fsz = ftell(f);
    if (fsz < 0 || fseek(f, 0, SEEK_SET) != 0) die("ftell");
    {
        FILE *g = fopen(v1path, "wb");
        uint8_t *cp = malloc(1 << 20);
        size_t rd;
        long left = fsz;
        if (!g || !cp) die("fopen v1");
        while (left > 0) {
            size_t want = left > (1 << 20) ? (1 << 20) : (size_t)left;
            rd = fread(cp, 1, want, f);
            if (rd == 0) die("read v2");
            if (fwrite(cp, 1, rd, g) != rd) die("write v1");
            left -= (long)rd;
        }
        free(cp);
        if (fclose(g) != 0) die("close v1");
    }
    if (fclose(f) != 0) die("close v2");

    if (blkio_open(&v1, v1path, 0) != 0) die("open v1");

    /* pass 1: the live set (v2 walk, CRC-filtered) */
    p = iarea;
    while (p + INVFS_REC_HDR_LEN <= iarea_end) {
        invfs_inode_rec rh;
        uint8_t *rb;
        uint32_t cs, cc;
        size_t nl;
        if (blkio_pread(&v2, p, &rh, sizeof rh) != 0) die("walk read");
        if (rh.magic != INODE_REC_MAGIC && rh.magic != TOMBSTONE_MAGIC)
            break;
        if (rh.rec_len < INVFS_REC_HDR_LEN + 1 ||
            rh.rec_len > INVFS_MAX_REC_LEN ||
            p + rh.rec_len + 4 > iarea_end)
            break;
        rb = malloc((size_t)rh.rec_len + 4);
        if (!rb) die("oom");
        if (blkio_pread(&v2, p, rb, (size_t)rh.rec_len + 4) != 0)
            die("walk rec read");
        memcpy(&cs, rb + rh.rec_len, 4);
        cc = invfs_crc32c(rb, rh.rec_len);
        if (cc == cs && rh.name_len && rh.name_len <= INVFS_MAX_NAME &&
            (size_t)rh.rec_len >= (size_t)INVFS_REC_HDR_LEN + rh.name_len + 1) {
            const char *nm = ((const invfs_inode_rec *)rb)->name;
            nl = rh.name_len < INVFS_MAX_NAME ? rh.name_len : INVFS_MAX_NAME;
            if (rh.magic == INODE_REC_MAGIC)
                dg_inod(&live, nm, (uint32_t)nl, rh.inode_id, p);
            else
                dg_delt(&live, nm, (uint32_t)nl, rh.inode_id,
                        rh.file_size);
        }
        free(rb);
        p += (uint64_t)rh.rec_len + 4;
    }

    /* pass 2: emit the v1 stream + the v1 flat journal */
    jrn = malloc((size_t)INVFS_JOURNAL_BLOCKS * INVFS_BLOCK_SIZE);
    if (!jrn) die("oom jrn");
    memset(jrn, 0, (size_t)INVFS_JOURNAL_BLOCKS * INVFS_BLOCK_SIZE);
    jn = 0;
    v1pos = iarea;
    p = iarea;
    while (p + INVFS_REC_HDR_LEN <= iarea_end) {
        invfs_inode_rec rh;
        uint8_t *rb, *nb;
        uint32_t cs, cc;
        size_t nl;
        uint64_t livepos;
        if (blkio_pread(&v2, p, &rh, sizeof rh) != 0) die("walk2 read");
        if (rh.magic != INODE_REC_MAGIC && rh.magic != TOMBSTONE_MAGIC)
            break;
        if (rh.rec_len < INVFS_REC_HDR_LEN + 1 ||
            rh.rec_len > INVFS_MAX_REC_LEN ||
            p + rh.rec_len + 4 > iarea_end)
            break;
        rb = malloc((size_t)rh.rec_len + 4);
        if (!rb) die("oom");
        if (blkio_pread(&v2, p, rb, (size_t)rh.rec_len + 4) != 0)
            die("walk2 rec read");
        memcpy(&cs, rb + rh.rec_len, 4);
        cc = invfs_crc32c(rb, rh.rec_len);
        if (cc != cs) { free(rb); p += (uint64_t)rh.rec_len + 4; continue; }
        nl = rh.name_len < INVFS_MAX_NAME ? rh.name_len : INVFS_MAX_NAME;

        if (rh.magic == TOMBSTONE_MAGIC) {
            /* the position kill maps onto the v1 stream position */
            invfs_inode_rec *th = (invfs_inode_rec *)rb;
            uint32_t tc;
            if (th->file_size) {
                uint64_t m = posmap_get(th->file_size);
                if (!m) {   /* the target was never emitted: drop */
                    free(rb);
                    continue;
                }
                th->file_size = m;
            }
            tc = invfs_crc32c(rb, th->rec_len);
            if (blkio_pwrite(&v1, v1pos, rb, th->rec_len) != 0 ||
                blkio_pwrite(&v1, v1pos + th->rec_len, &tc, 4) != 0)
                die("v1 tomb write");
            v1pos += (uint64_t)th->rec_len + 4;
            free(rb);
            p += (uint64_t)rh.rec_len + 4;
            continue;
        }

        /* INOD: convert the entries 32B -> 24B */
        {
            invfs_ast_hdr ah;
            size_t base, ent0, off, choff;
            size_t ext_off, ext_len = 0;
            uint8_t *extp = NULL;
            uint32_t i;
            size_t nlen2;
            uint64_t id = rh.inode_id;
            int is_hot;
            dg_name *ne;
            int live_now;

            base = (size_t)(invfs_rec_cbody((const invfs_inode_rec *)rb) - rb);
            if (rh.rec_len < base + INVFS_AST_HDR_V1_LEN ||
                invfs_ast_hdr_parse(rb + base, rh.rec_len - base, &ah) != 0)
                die("v2 recipe parse");
            ent0 = base + ah.hdr_len;
            if ((size_t)ah.num_blocks * sizeof(invfs_ast_block_entry) >
                rh.rec_len - ent0)
                die("v2 entries overflow");
            choff = ent0 + (size_t)ah.num_blocks *
                           sizeof(invfs_ast_block_entry);
            off = choff;
            for (i = 0; i < ah.num_children; i++) {
                uint16_t cnl;
                if (rh.rec_len - off < 2) die("child oob");
                memcpy(&cnl, rb + off, 2);
                if (rh.rec_len - off < (size_t)cnl + 22) die("child oob2");
                off += 2 + cnl + 20;
            }
            ext_off = off;
            if (rh.rec_len - off >= sizeof(invfs_meta_ext_hdr)) {
                invfs_meta_ext_hdr mh;
                memcpy(&mh, rb + ext_off, sizeof mh);
                if (mh.magic == INVFS_META_MAGIC &&
                    mh.ext_len <= rh.rec_len - ext_off) {
                    extp = rb + ext_off;
                    ext_len = mh.ext_len;
                }
            }

            ne = dg_find(&live, ((const invfs_inode_rec *)rb)->name,
                         (uint32_t)nl);
            live_now = ne && ne->nvers &&
                       ne->vers[ne->nvers - 1].pos == p;
            is_hot = nl == 7 &&
                     memcmp(((const invfs_inode_rec *)rb)->name,
                            "hot.bin", 7) == 0;

            /* build the v1 record */
            nlen2 = base + ah.hdr_len +
                    (size_t)ah.num_blocks *
                    sizeof(invfs_ast_block_entry_v1) +
                    (off - choff) + ext_len;
            nb = calloc(1, nlen2 + 4);
            if (!nb) die("oom nb");
            memcpy(nb, rb, ent0);   /* rec header + recipe header */
            for (i = 0; i < ah.num_blocks; i++) {
                const invfs_ast_block_entry *e2 =
                    (const invfs_ast_block_entry *)
                    (rb + ent0 + (size_t)i * sizeof *e2);
                invfs_ast_block_entry_v1 *e1 =
                    (invfs_ast_block_entry_v1 *)
                    (nb + ent0 + (size_t)i * sizeof *e1);
                e1->file_offset = e2->file_offset;
                e1->length = e2->length;
                e1->zone = e2->zone;
                e1->algo = e2->algo;
                e1->block_id = e2->block_id;
                e1->block_offset = e2->block_offset;
            }
            if (off > choff)
                memcpy(nb + ent0 +
                       (size_t)ah.num_blocks *
                       sizeof(invfs_ast_block_entry_v1),
                       rb + choff, off - choff);
            if (extp) {
                size_t xl = ext_len;
                uint8_t *xdst = nb + base + ah.hdr_len +
                                (size_t)ah.num_blocks *
                                sizeof(invfs_ast_block_entry_v1) +
                                (off - choff);
                memcpy(xdst, extp, ext_len);
                dg_strip_heat(xdst, &xl);
                nlen2 -= ext_len - xl;
            }
            {
                invfs_inode_rec *nh = (invfs_inode_rec *)nb;
                uint32_t ncrc;
                nh->rec_len = (uint32_t)nlen2;
                ncrc = invfs_crc32c(nb, nlen2);
                memcpy(nb + nlen2, &ncrc, 4);
            }
            if (blkio_pwrite(&v1, v1pos, nb, nlen2) != 0 ||
                blkio_pwrite(&v1, v1pos + nlen2,
                             nb + nlen2, 4) != 0)
                die("v1 rec write");
            posmap_put(p, v1pos);
            v1pos += (uint64_t)nlen2 + 4;

            /* the v1 journal maps for a LIVE record's entries */
            if (live_now) {
                for (i = 0; i < ah.num_blocks; i++) {
                    const invfs_ast_block_entry *e2 =
                        (const invfs_ast_block_entry *)
                        (rb + ent0 + (size_t)i * sizeof *e2);
                    invfs_l2p_entry le;
                    if (!e2->length || !e2->pba) continue;
                    memset(&le, 0, sizeof le);
                    le.type = INVFS_JRN_MAP;
                    le.inode = id;
                    le.lba = e2->block_id;
                    le.pba = e2->pba;
                    le.length = (uint32_t)dg_extent(&v2, e2->pba);
                    le.pad[0] = is_hot ? 20 : 0;
                    le.pad[1] = 0;
                    le.pad[2] = is_hot ? 3 : 1;
                    le.crc = invfs_crc32c(&le, offsetof(invfs_l2p_entry,
                                                        crc));
                    if (jn + sizeof le >
                        (size_t)INVFS_JOURNAL_BLOCKS * INVFS_BLOCK_SIZE)
                        die("v1 journal overflow");
                    memcpy(jrn + jn, &le, sizeof le);
                    jn += sizeof le;
                }
            }
            free(nb);
        }
        free(rb);
        p += (uint64_t)rh.rec_len + 4;
    }

    /* write the v1 journal (flat log; the rest is zeros = the CRC-stop),
     * zeroing the whole area first to kill any slot headers */
    {
        uint8_t *z = calloc(1, BLKIO_BOUNCE);
        uint64_t off = jbase, left = (uint64_t)INVFS_JOURNAL_BLOCKS *
                                     INVFS_BLOCK_SIZE;
        if (!z) die("oom z");
        while (left) {
            size_t n2 = left > BLKIO_BOUNCE ? BLKIO_BOUNCE : (size_t)left;
            if (blkio_pwrite(&v1, off, z, n2) != 0) die("jrn wipe");
            off += n2;
            left -= n2;
        }
        free(z);
        if (jn && blkio_pwrite(&v1, jbase, jrn, jn) != 0)
            die("jrn write");
    }

    /* the v1 inode stream guard + the v1 superblock */
    {
        uint8_t z[INVFS_BLOCK_SIZE];
        memset(z, 0, sizeof z);
        if (blkio_pwrite(&v1, v1pos, z, sizeof z) != 0)
            die("guard write");
        sb.vol_flags &= ~VOLF_ASTV2;
        sb.pad2 = INVFS_JSEL_LEGACY;
        sb.state = INVFS_STATE_CLEAN;
        sb.checksum = invfs_crc32c(&sb,
                                   offsetof(invfs_superblock, checksum));
        if (blkio_pwrite(&v1, 0, &sb, sizeof sb) != 0)
            die("sb write");
    }
    free(jrn);
    rc = blkio_flush(&v1);
    blkio_close(&v1);
    blkio_close(&v2);
    if (rc != 0) die("v1 flush");
    printf("downgrade: %s -> %s (%zu journal maps, stream ends +%lld)\n",
           v2path, v1path, jn / sizeof(invfs_l2p_entry),
           (long long)(v1pos - iarea));
}

/* ---- verify ---------------------------------------------------------- */
static void rdfile(invfs_volume *v, const char *name, const uint8_t *want,
                   size_t n)
{
    uint64_t id = vol_find(v, name);
    uint8_t *got = NULL;
    size_t glen = 0;
    if (!id) { fprintf(stderr, "missing: %s\n", name); die("lost file"); }
    if (vol_read_file(v, id, &got, &glen) != 0) die("read failed");
    if (glen != n || (n && memcmp(got, want, n) != 0)) {
        fprintf(stderr, "content mismatch: %s\n", name);
        die("bit-exact check failed");
    }
    free(got);
}

static void verify(invfs_volume *v)
{
    uint8_t *b;
    const invfs_superblock *sb = vol_sb(v);
    size_t n, i;

    if (!(sb->vol_flags & VOLF_ASTV2)) die("VOLF_ASTV2 not set");
    if (vol_find(v, "gone.bin")) die("gone.bin resurrected");
    if (vol_find(v, "oldname.bin")) die("oldname.bin survived rename");

    /* the heat fold: hot.bin's pads (20/3) became the record TLV. Checked
     * BEFORE any content read (reads accrue +1 per session, folded at
     * close): a fresh conversion shows exactly 20, a re-verified one
     * shows 20 + the intervening verification reads. */
    {
        uint64_t id = vol_find(v, "hot.bin");
        uint8_t hv[4];
        size_t hl = sizeof hv;
        unsigned rh;
        if (vol_get_xattr(v, id, INVFS_XATTR_HEAT, hv, &hl) != 0 || hl < 3)
            die("heat TLV absent");
        rh = hv[0] | ((unsigned)hv[1] << 8);
        if (rh < 20 || hv[2] != 3)
            die("heat TLV wrong");
    }

    b = gen_text(11, 3000);  rdfile(v, "small.txt", b, 3000);  free(b);
    b = gen_bin(22, 200*1024); rdfile(v, "big.bin", b, 200*1024); free(b);
    b = gen_comp(33, 150*1024); rdfile(v, "comp.bin", b, 150*1024); free(b);
    b = gen_bin(44, 48*1024);  rdfile(v, "hot.bin", b, 48*1024); free(b);
    b = gen_bin(66, 24*1024);  rdfile(v, "renamed.bin", b, 24*1024); free(b);
    b = gen_bin(77, 48*1024);  rdfile(v, "meta.bin", b, 48*1024); free(b);
    for (i = 0; i < 8; i++) {
        char nm[32];
        size_t sz = 2500 + i * 500;
        snprintf(nm, sizeof nm, "txt%d.txt", (int)i);
        b = gen_text(100 + i, sz);
        rdfile(v, nm, b, sz);
        free(b);
    }
    /* empty file */
    {
        uint64_t id = vol_find(v, "empty.txt");
        if (!id) die("empty.txt lost");
    }
    /* meta + xattr carried */
    {
        invfs_meta_pub m;
        uint64_t id = vol_find(v, "meta.bin");
        char note[16];
        size_t nl = sizeof note;
        if (vol_get_meta(v, id, &m) != 0) die("meta readback failed");
        if (m.mode != 0601 || m.uid != 1234 || m.gid != 4321 ||
            m.mtime != 1700000000)
            die("meta fields drifted");
        if (vol_get_xattr(v, id, "user.note", note, &nl) != 0 ||
            nl != 10 || memcmp(note, "hello-wp27", 10))
            die("xattr lost");
    }
    /* the WAL is owner-only: no map names a regular file's id */
    {
        const invfs_l2p_entry *t = vol_l2p(v, &n);
        static const char *files[] = {
            "small.txt", "big.bin", "comp.bin", "hot.bin", "renamed.bin",
            "meta.bin", "txt0.txt", "txt1.txt", "txt2.txt", "txt3.txt",
            "txt4.txt", "txt5.txt", "txt6.txt", "txt7.txt"
        };
        for (i = 0; i < n; i++) {
            size_t k;
            if (t[i].type != INVFS_JRN_MAP) continue;
            for (k = 0; k < sizeof files / sizeof *files; k++)
                if (t[i].inode == vol_find(v, files[k]))
                    die("WAL holds a file map (owner-only rule broken)");
        }
        if (!n) die("WAL empty: the tzb owner map did not convert");
    }
    printf("verify: all content bit-exact; meta/xattr/heat carried; WAL "
           "owner-only\n");
}

/* populate-lite: a few RAW files (no sweep, so nothing reaches the shadow
 * zone / dev1 -- the downgrade harness reads dev0 only). verify-lite reads
 * them back. */
static void populate_lite(invfs_volume *v)
{
    uint8_t *b;
    b = gen_bin(202, 90*1024);   wr(v, "lite1.bin", b, 90*1024);  free(b);
    b = gen_comp(203, 48*1024);  wr(v, "lite2.bin", b, 48*1024);  free(b);
    b = gen_bin(204, 40*1024);   wr(v, "litex.bin", b, 40*1024);  free(b);
}

static void verify_lite(invfs_volume *v)
{
    uint8_t *b;
    const invfs_superblock *sb = vol_sb(v);
    if (!(sb->vol_flags & VOLF_ASTV2)) die("VOLF_ASTV2 not set (lite)");
    b = gen_bin(202, 90*1024);  rdfile(v, "lite1.bin", b, 90*1024);  free(b);
    b = gen_comp(203, 48*1024); rdfile(v, "lite2.bin", b, 48*1024);  free(b);
    b = gen_bin(204, 40*1024);  rdfile(v, "litex.bin", b, 40*1024);  free(b);
    printf("verify-lite: bit-exact\n");
}

int main(int argc, char **argv)
{
    int err = 0;
    invfs_volume *v;
    if (argc < 3) die("usage");
    if (strcmp(argv[1], "downgrade") == 0) {
        if (argc < 4) die("usage");
        downgrade(argv[2], argv[3]);
        return 0;
    }
    v = vol_open(argv[2], &err);
    if (!v) die("vol_open failed");
    if (strcmp(argv[1], "populate") == 0)
        populate(v);
    else if (strcmp(argv[1], "verify") == 0)
        verify(v);
    else if (strcmp(argv[1], "populate-lite") == 0)
        populate_lite(v);
    else if (strcmp(argv[1], "verify-lite") == 0)
        verify_lite(v);
    else
        die("unknown mode");
    vol_close(v);
    return 0;
}
EOF

cc -std=gnu11 -O2 -I$REPO/src $(printf -- "-I$REPO/src/%s " core codecs recipes cli vendor7z legacy) -pthread \
   -DINVFS_EMBED_FLACX -DMINIZ_NO_ZLIB_APIS -DBLAKE3_NO_SSE2 -DBLAKE3_NO_SSE41 -DBLAKE3_NO_AVX2 -DBLAKE3_NO_AVX512 \
   -o "$WORK/mig2_harness" "$WORK/mig2_harness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread || fail "harness build"
H=$WORK/mig2_harness

# build_v1 <img>: fresh v2 image -> populate -> sweep (batched; no
# checkpoint) -> downgrade to v1
build_v1() {
    local img="$1"
    rm -f "$img"
    $B/invf-mkfs "$img" 0.5 >/dev/null || fail "mkfs"
    $H populate "$img" || fail "populate"
    INVFS_CHECKPOINT=0 $B/invf-sweep "$img" > "$WORK/sweep.log" 2>&1 || {
        cat "$WORK/sweep.log"; fail "sweep"; }
    cp "$img" "$img.v2keep"
    $H downgrade "$img.v2keep" "$img" || fail "downgrade"
}

verify_img() {
    $H verify "$1" || fail "verify $1"
    $B/invf-fsck "$1" > "$WORK/fsck.log" 2>&1 || { cat "$WORK/fsck.log"; fail "fsck $1"; }
    grep -q "orphans:      0" "$WORK/fsck.log" || { cat "$WORK/fsck.log"; fail "orphans in $1"; }
    grep -q "missing:      0" "$WORK/fsck.log" || { cat "$WORK/fsck.log"; fail "missing in $1"; }
}

echo "== leg A: convert a v1 volume =="
build_v1 wp27m-a.img
# the v1 refusal gate: the engine must refuse the un-converted image,
# loudly, naming the tool
if $B/invf-ls wp27m-a.img > "$WORK/v1ls.log" 2>&1; then
    fail "v1 volume opened without conversion"
fi
grep -q "invf-migrate-v2" "$WORK/v1ls.log" || {
    cat "$WORK/v1ls.log"; fail "refusal does not point at invf-migrate-v2"; }
echo "v1 refusal: loud + points at invf-migrate-v2"
$B/invf-migrate-v2 wp27m-a.img > "$WORK/cvt.log" 2>&1 || {
    cat "$WORK/cvt.log"; fail "conversion failed"; }
cat "$WORK/cvt.log"
verify_img wp27m-a.img
echo "leg A: converted volume verified (content, meta, xattr, heat, WAL)"

echo "== leg B: crash at each protocol point, re-run completes =="
for point in staged armed applied; do
    build_v1 wp27m-b.img
    set +e
    INVFS_MIGRATE_ABORT_AT=$point $B/invf-migrate-v2 wp27m-b.img > "$WORK/cvt-b.log" 2>&1
    set -e
    # the kill must have landed before the commit: re-run finishes it
    $B/invf-migrate-v2 wp27m-b.img >> "$WORK/cvt-b.log" 2>&1 || {
        cat "$WORK/cvt-b.log"; fail "resume after $point failed"; }
    verify_img wp27m-b.img
    echo "  crash at $point: resumed + verified"
done

echo "== leg C: --abort disarms a never-applied conversion =="
build_v1 wp27m-c.img
set +e
INVFS_MIGRATE_ABORT_AT=armed $B/invf-migrate-v2 wp27m-c.img > "$WORK/cvt-c.log" 2>&1
set -e
$B/invf-migrate-v2 --abort wp27m-c.img > "$WORK/abort.log" 2>&1 || {
    cat "$WORK/abort.log"; fail "--abort failed"; }
# the volume is v1 again: the engine refuses it, a fresh conversion succeeds
if $B/invf-ls wp27m-c.img > /dev/null 2>&1; then
    fail "--abort left a mountable (v2?) volume"
fi
$B/invf-migrate-v2 wp27m-c.img > "$WORK/cvt-c2.log" 2>&1 || {
    cat "$WORK/cvt-c2.log"; fail "conversion after --abort failed"; }
verify_img wp27m-c.img
echo "  --abort: disarmed, re-converted, verified"

echo "== leg D: idempotence + double-convert refusal =="
$B/invf-migrate-v2 wp27m-a.img > "$WORK/cvt-again.log" 2>&1 || fail "re-run on v2"
grep -q "already format v2" "$WORK/cvt-again.log" || {
    cat "$WORK/cvt-again.log"; fail "no already-v2 note"; }
verify_img wp27m-a.img
echo "  re-run on a v2 volume: clean no-op"

echo "== leg E: two-device volume (the mirror router) =="
rm -f wp27m-e0.img wp27m-e1.img
$B/invf-mkfs wp27m-e0.img 0.125 wp27m-e1.img 0.25 > "$WORK/mkfs-e.log" 2>&1 \
    || { cat "$WORK/mkfs-e.log"; fail "mkfs 2-device"; }
# populate a handful of files through the engine (they land RAW on dev0),
# then downgrade dev0's metadata to v1 (the converter mirrors the writes)
(
    export INVFS_DEV1=wp27m-e1.img
    $H populate-lite wp27m-e0.img || fail "populate-lite"
)
cp wp27m-e0.img wp27m-e0.img.v2keep
$H downgrade wp27m-e0.img.v2keep wp27m-e0.img || fail "downgrade 2-device"
# the v1 refusal names the tool for a 2-device volume too
if $B/invf-ls wp27m-e0.img > /dev/null 2>&1; then
    fail "2-device v1 volume opened without conversion"
fi
(
    export INVFS_DEV1=wp27m-e1.img
    $B/invf-migrate-v2 wp27m-e0.img > "$WORK/cvt-e.log" 2>&1 || {
        cat "$WORK/cvt-e.log"; fail "2-device conversion failed"; }
    $H verify-lite wp27m-e0.img || fail "verify 2-device"
    $B/invf-fsck wp27m-e0.img > "$WORK/fsck-e.log" 2>&1 || {
        cat "$WORK/fsck-e.log"; fail "fsck 2-device"; }
    grep -q "orphans:      0" "$WORK/fsck-e.log" || {
        cat "$WORK/fsck-e.log"; fail "orphans in the 2-device volume"; }
)
echo "  two-device volume converted + verified (mirror written through)"

echo "MIGRATE-V2 E2E: PASS"
