#!/bin/bash
# test-compact.sh — WP22e e2e: online inode-area compaction (hot tail
# pruning) + invf-sweep --fast. Persistent regression suite.
#
#   Leg A (churn -> compact): an engine-level churn workload (create /
#   rewrite / delete, repeatedly) grows the append-only inode area with
#   dead record versions + tombstones until the dead share exceeds ~30%.
#   The sweep's automatic pass SKIPS while the sweep checkpoint (CKP0) is
#   live (rollback truncates to absolute checkpoint positions) and runs
#   once it is realized: the area shrinks to exactly the live set, every
#   live file (incl. batched text members and a directory subtree) reads
#   bit-exact, fsck + verify --deep clean. INVFS_NO_COMPACT=1 suppresses
#   the automatic pass; --compact forces it alone; a read-only volume is
#   skipped with a message.
#
#   Leg A7 (rollback horizon): a second --compact right after a
#   successful one is a strict no-op ("area already compact"); a
#   checkpoint armed AFTER a compaction still rolls back bit-exact (its
#   absolute positions name the compacted area), post-checkpoint writes
#   vanish, fsck/verify clean.
#
#   Leg A8 (seal interplay): compaction under a LIVE seal proceeds (no
#   CKP0 can exist then -- vol_ckp_begin declines under a seal) and never
#   touches the \x01parity*-owned blocks: verify --deep reports zero
#   parity drift and the reseal is "0 stripes updated".
#
#   Leg B (--fast): a .tar is NOT decomposed, text is NOT batched -- every
#   RAW file takes only the generic per-segment recompress; a second
#   --fast run is a pure no-op; bit-exact, fsck/verify clean.
#
#   Leg C (crash legs, INVFS_COMPACT_ABORT_AT, the INVFS_RESIZE_ABORT_AT
#   pattern): kill -9 at "staged" (pre-arm: old area intact, the stranded
#   staging run is an fsck orphan), "armed", "copying" (a genuinely torn
#   area mid-copy) and "copied" -> the volume latches read-only +
#   needs-recovery, invf-sweep refuses, and invf-fsck -f rolls the staged
#   stream forward (idempotent) -> fsck clean, verify --deep clean,
#   bit-exact, area compacted.
#
# The engine harness is generated below and linked against the built
# engine objects (the test-flushfail.sh convention). Run from the repo
# root after `make` (or via tools/run-e2e.sh). Uses /dev/shm like the
# other soak scripts; image paths are RELATIVE (blkio treats /dev/* as
# raw devices).
set -e
set -o pipefail

REPO="${REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
B=$REPO/bin
WORK=/dev/shm/wp22ecompact
IMG_A=wp22e-cm-a.img    # churn -> compact (+ ckp skip / realize / env off)
IMG_B=wp22e-cm-b.img    # --fast behaviour
IMG_C=wp22e-cm-c.img    # crash: staged
IMG_D=wp22e-cm-d.img    # crash: armed
IMG_E=wp22e-cm-e.img    # crash: copying (torn area)
IMG_F=wp22e-cm-f.img    # crash: copied
IMG_G=wp22e-cm-g.img    # compact twice + rollback-after-compact
IMG_H=wp22e-cm-h.img    # compaction under a live seal
rm -rf "$WORK" && mkdir -p "$WORK/orig" "$WORK/out"
cd /dev/shm
rm -f "$IMG_A" "$IMG_B" "$IMG_C" "$IMG_D" "$IMG_E" "$IMG_F" "$IMG_G" "$IMG_H"

fail() { echo "FAIL: $*" >&2; exit 1; }

# ---- the engine harness (public API only) ---------------------------------
CORE="volume vol_cpack helper_exec vol_png vol_seal vol_repair vol_rollback \
      vol_resize vol_fsck vol_crash vol_exer vol_dedupe vol_textzone \
      vol_heat vol_sweep vol_read vol_write vol_records vol_ast \
      vol_dirs vol_tier arc crc32c lz4 flacx tarx pngx blkio miniz blake3 \
      blake3_dispatch blake3_portable ppmd8 ppmd8enc ppmd8dec \
      ppmd_codec codec bcj_x86 rs vol_meta_merge"
OBJS=""
for m in $CORE; do OBJS="$OBJS $REPO/build/obj/$m.o"; done

cat > "$WORK/cpharness.c" <<'EOF'
/* cpharness.c — WP22e engine-level test driver (generated by
 * tools/test-compact.sh; links the engine objects, public API only).
 *
 *   cpharness churn  <img> <F> <R>   the churn scenario (below)
 *   cpharness verify <img> <F> <R>   assert the final state bit-exactly
 *   cpharness areastat <img>         "used=.. live=.." (inode area bytes)
 *   cpharness ckp      <img>         "present=<0|1>" (CKP0 live)
 *   cpharness cmpend   <img>         "pending=<0|1>" (CMP0 armed)
 *   cpharness wrena    <img>         "write_enabled=<0|1>"
 *   cpharness readonly <img> <0|1>   operator read-only hold + flush
 *
 * The churn scenario (deterministic): files f%03d (base 0) and
 * sub/g%02d (base 100) are REWRITTEN every round r < R with
 * bin_pattern(base, r); one victim per round is deleted+recreated;
 * doomed d%02d (base 200) exist only for r < R/3 (deleted at R/3);
 * cold c%02d.txt (base 300) are written ONCE at round R-1. So every
 * survivor's final content is gen(base, R-1) and the doomed are absent.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "volume.h"
#include "invarifs.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

static void fill_pattern(uint8_t *b, size_t n, uint64_t key)
{
    uint64_t x = key * 0x9E3779B97F4A7C15ull + 0x123456789;
    size_t i;
    for (i = 0; i < n; i++) {
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        b[i] = (uint8_t)(x >> 32);
    }
}

/* printable text, same determinism (the .txt cold files are PPMd-batch
 * candidates -- content must sniff as text) */
static void text_pattern(uint8_t *b, size_t n, uint64_t key)
{
    static const char *WORDS[] = { "the","quick","brown","fox","jumps",
        "over","lazy","dogs","int","static","return","while","for" };
    size_t i = 0;
    uint64_t x = key * 0x9E3779B97F4A7C15ull + 777;
    while (i < n) {
        const char *w = WORDS[(x >> 24) % 13];
        size_t wl = strlen(w), k;
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        for (k = 0; k < wl && i < n; k++) b[i++] = (uint8_t)w[k];
        if (i < n) b[i++] = (i % 71 == 70) ? '\n' : ' ';
    }
}

static size_t file_len(uint64_t base, int r)
{
    return 1200 + (size_t)((base * 997 + (uint64_t)r * 13) % 5200);
}

static void gen_file(uint8_t **buf, size_t *len, uint64_t base, int r,
                     int text)
{
    *len = file_len(base, r);
    *buf = malloc(*len);
    if (!*buf) die("oom");
    if (text) text_pattern(*buf, *len, base * 1000 + (uint64_t)r);
    else      fill_pattern(*buf, *len, base * 1000 + (uint64_t)r);
}

static void put_file(invfs_volume *v, const char *name, uint64_t base, int r,
                     int text)
{
    uint8_t *buf; size_t len;
    gen_file(&buf, &len, base, r, text);
    if (strchr(name, '/')) vol_ensure_path(v, name);
    if (!vol_replace_file(v, name, buf, len)) die("replace_file");
    free(buf);
}

static int cmd_churn(const char *img, long F, long R)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    long f, g, c, d;
    int r;
    char nm[64];
    if (!v) die("open");
    for (r = 0; r < R; r++) {
        for (f = 0; f < F; f++) {
            snprintf(nm, sizeof nm, "f%03ld", f);
            put_file(v, nm, (uint64_t)f, r, 0);
        }
        for (g = 0; g < 4; g++) {
            snprintf(nm, sizeof nm, "sub/g%02ld", g);
            put_file(v, nm, (uint64_t)(100 + g), r, 0);
        }
        /* one victim deleted+recreated per round (kill-by-id churn) */
        {
            long victim = (r * 7) % F;
            snprintf(nm, sizeof nm, "f%03ld", victim);
            if (vol_delete_file(v, nm) != 0) die("victim delete");
            put_file(v, nm, (uint64_t)victim, r, 0);
        }
        /* doomed files: live only for the first third of the rounds */
        for (d = 0; d < 5; d++) {
            snprintf(nm, sizeof nm, "d%02ld", d);
            if (r < R / 3)
                put_file(v, nm, (uint64_t)(200 + d), r, 0);
            else if (r == R / 3)
                vol_delete_file(v, nm);   /* -1 when never created: fine */
        }
        /* cold text files: written once, at the last round */
        if (r == R - 1) {
            for (c = 0; c < 6; c++) {
                snprintf(nm, sizeof nm, "c%02ld.txt", c);
                put_file(v, nm, (uint64_t)(300 + c), r, 1);
            }
        }
    }
    if (vol_flush(v) != 0) die("flush");
    vol_close(v);
    printf("CHURN-OK\n");
    return 0;
}

static void assert_file(invfs_volume *v, const char *name, uint64_t base,
                        int r, int text)
{
    uint64_t id = vol_find(v, name);
    uint8_t *buf = NULL, *want;
    size_t blen = 0, wlen;
    if (!id) die("assert_file: absent");
    if (vol_read_file(v, id, &buf, &blen) != 0) die("assert_file: read");
    gen_file(&want, &wlen, base, r, text);
    if (blen != wlen || memcmp(want, buf, wlen) != 0)
        die("assert_file: content mismatch");
    free(want);
    free(buf);
}

static int cmd_verify(const char *img, long F, long R)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    long f, g, c, d;
    char nm[64];
    if (!v) die("open");
    for (f = 0; f < F; f++) {
        snprintf(nm, sizeof nm, "f%03ld", f);
        assert_file(v, nm, (uint64_t)f, (int)R - 1, 0);
    }
    for (g = 0; g < 4; g++) {
        snprintf(nm, sizeof nm, "sub/g%02ld", g);
        assert_file(v, nm, (uint64_t)(100 + g), (int)R - 1, 0);
    }
    for (c = 0; c < 6; c++) {
        snprintf(nm, sizeof nm, "c%02ld.txt", c);
        assert_file(v, nm, (uint64_t)(300 + c), (int)R - 1, 1);
    }
    for (d = 0; d < 5; d++) {
        snprintf(nm, sizeof nm, "d%02ld", d);
        if (vol_find(v, nm)) die("doomed file present");
    }
    vol_close(v);
    printf("VERIFY-OK\n");
    return 0;
}

int main(int argc, char **argv)
{
    if (argc < 3) return 2;
    if (!strcmp(argv[1], "churn") && argc == 5)
        return cmd_churn(argv[2], atol(argv[3]), atol(argv[4]));
    if (!strcmp(argv[1], "verify") && argc == 5)
        return cmd_verify(argv[2], atol(argv[3]), atol(argv[4]));
    if (!strcmp(argv[1], "areastat") && argc == 3) {
        int err = 0;
        invfs_volume *v = vol_open(argv[2], &err);
        if (!v) die("open");
        printf("used=%llu live=%llu\n",
               (unsigned long long)(vol_inode_area_pos(v) -
                                    vol_inode_area_start(v)),
               (unsigned long long)vol_inode_live_bytes(v));
        vol_close(v);
        return 0;
    }
    if (!strcmp(argv[1], "ckp") && argc == 3) {
        int err = 0;
        invfs_volume *v = vol_open(argv[2], &err);
        if (!v) die("open");
        printf("present=%d\n", vol_ckp_armed(v));
        vol_close(v);
        return 0;
    }
    if (!strcmp(argv[1], "cmpend") && argc == 3) {
        int err = 0;
        invfs_volume *v = vol_open(argv[2], &err);
        if (!v) die("open");
        printf("pending=%d\n", vol_compact_pending(v));
        vol_close(v);
        return 0;
    }
    if (!strcmp(argv[1], "wrena") && argc == 3) {
        int err = 0;
        invfs_volume *v = vol_open(argv[2], &err);
        if (!v) die("open");
        printf("write_enabled=%d\n", vol_write_enabled(v));
        vol_close(v);
        return 0;
    }
    if (!strcmp(argv[1], "readonly") && argc == 4) {
        int err = 0;
        invfs_volume *v = vol_open(argv[2], &err);
        if (!v) die("open");
        vol_set_readonly(v, atoi(argv[3]));
        if (vol_flush(v) != 0) die("flush");
        vol_close(v);
        return 0;
    }
    fprintf(stderr, "bad args\n");
    return 2;
}
EOF

gcc -std=gnu11 -O2 -I$REPO/src -I$REPO/src/core -I$REPO/src/codecs -I$REPO/src/recipes -I$REPO/src/vendor7z -o "$WORK/cpharness" \
    "$WORK/cpharness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread \
    || fail "harness build"
H=$WORK/cpharness

class_of() { $B/meta_probe "$1" --heat "$2" 2>/dev/null | sed -n 's/^class=\([0-9a-z]*\).*/\1/p'; }
used_of()  { "$H" areastat "$1" | sed -n 's/^used=\([0-9]*\).*/\1/p'; }
live_of()  { "$H" areastat "$1" | sed -n 's/.* live=\([0-9]*\)$/\1/p'; }

# WP71h: mapper detection. Every volume the current mkfs produces is a
# mapper volume (MET0 + dynamic metadata extents, sb.meta_mapper_pba != 0):
# the legacy LINEAR inode-area compaction (legs A1-A8 and the CMP0 crash
# legs) is unreachable on them -- vol_inode_compact refuses loudly and the
# mapper-era consolidation is the sweep's meta-merge (vol_meta_merge_run).
# The M-legs below exercise that contract; the legacy legs stay intact for
# pre-WP30 volumes.
is_mapper() { python3 - "$1" <<'PY'
import struct, sys
d = open(sys.argv[1], "rb").read(0xA8)
print(1 if struct.unpack_from("<Q", d, 0x98)[0] else 0)
PY
}
extent_blocks() { $B/invf-stats "$1" 2>/dev/null | \
    sed -n 's/^meta extents (WP30): [0-9]* extent(s), \([0-9]*\) blocks.*/\1/p' | \
    head -1 | sed 's/^$/0/'; }

echo "== [A] churn -> inode area grows -> compaction =="
INVFS_META_FRAC=8 $B/invf-mkfs "$IMG_A" 0.25 >/dev/null || fail "mkfs A"
"$H" churn "$IMG_A" 40 24 || fail "churn A"
"$H" verify "$IMG_A" 40 24 || fail "pre-sweep content wrong"
UA0=$(used_of "$IMG_A"); LA0=$(live_of "$IMG_A")
echo "  after churn: used=$UA0 live=$LA0"
[ "$UA0" -gt 0 ] && [ "$LA0" -gt 0 ] || fail "areastat"
[ $(( (UA0 - LA0) * 10 )) -gt $(( UA0 * 3 )) ] || fail "churn did not produce >30% dead bytes"

MAPPER=$(is_mapper "$IMG_A")
if [ "$MAPPER" = 1 ]; then
echo "== [M1] mapper volume: sweep arms a checkpoint; the linear compaction refuses LOUDLY =="
$B/invf-sweep "$IMG_A" > "$WORK/sweep-m1.log" 2>&1 || { cat "$WORK/sweep-m1.log"; fail "sweep M1"; }
grep -q "checkpoint: #1 armed" "$WORK/sweep-m1.log" || fail "M1: no checkpoint armed"
grep -q "inode compact: skipped (mapper volume" "$WORK/sweep-m1.log" \
    || { cat "$WORK/sweep-m1.log"; fail "M1: no loud mapper-compaction refusal"; }
if grep -q "^inode area compacted: " "$WORK/sweep-m1.log"; then
    fail "M1: linear compaction ran on a mapper volume"
fi
"$H" ckp "$IMG_A" | grep -q "present=1" || fail "M1: CKP0 not live"
"$H" verify "$IMG_A" 40 24 || fail "M1: content wrong"
echo "  loud refusal under the live checkpoint; content intact"

echo "== [M2] --compact on a mapper volume: loud refusal, extent footprint untouched =="
XB0=$(extent_blocks "$IMG_A")
[ "$XB0" -gt 0 ] || fail "M2: no extent footprint reported (invf-stats meta extents line)"
$B/invf-sweep "$IMG_A" --compact > "$WORK/compact-m2.log" 2>&1 || fail "M2: --compact rc"
grep -q "inode compact: skipped (mapper volume" "$WORK/compact-m2.log" \
    || { cat "$WORK/compact-m2.log"; fail "M2: no mapper skip message"; }
if grep -q "^inode area compacted: " "$WORK/compact-m2.log"; then fail "M2: compacted"; fi
XB1=$(extent_blocks "$IMG_A")
[ "$XB0" = "$XB1" ] || fail "M2: extent footprint moved ($XB0 -> $XB1)"
"$H" verify "$IMG_A" 40 24 || fail "M2: content wrong after the refused compact"
$B/invf-fsck "$IMG_A" | grep -q "^OK$" || fail "M2: fsck not clean under the live checkpoint"
echo "  footprint stable at $XB1 blocks; fsck clean"

echo "== [M3] realize + re-sweep: the mapper-era consolidation is the meta-merge =="
$B/invf-sweep "$IMG_A" --realize > "$WORK/realize-m3.log" 2>&1 || { cat "$WORK/realize-m3.log"; fail "realize M3"; }
grep -q "realized" "$WORK/realize-m3.log" || fail "M3: no realize line"
"$H" ckp "$IMG_A" | grep -q "present=0" || fail "M3: checkpoint survived realize"
$B/invf-sweep "$IMG_A" > "$WORK/sweep-m3.log" 2>&1 || { cat "$WORK/sweep-m3.log"; fail "sweep M3"; }
"$H" verify "$IMG_A" 40 24 || fail "M3: content wrong after realize+re-sweep"
$B/invf-fsck "$IMG_A" | grep -q "^OK$" || fail "M3: fsck not clean"
$B/invf-verify "$IMG_A" --deep | grep -q " 0 corrupt," || fail "M3: verify not clean"
XB2=$(extent_blocks "$IMG_A")
echo "  merge-on-sweep contract OK (extent footprint $XB2 blocks); content bit-exact"
$B/invf-sweep "$IMG_A" --realize >/dev/null 2>&1 || true
echo "== [A4-A8] linear-compaction legs: SKIPPED on a mapper volume (CMP0 machinery unreachable; the meta-merge owns consolidation) =="
else

echo "== [A1] sweep: checkpoint live -> auto-compaction skipped =="
$B/invf-sweep "$IMG_A" > "$WORK/sweep-a1.log" 2>&1 || { cat "$WORK/sweep-a1.log"; fail "sweep A1"; }
grep -q "checkpoint: #1 armed" "$WORK/sweep-a1.log" || fail "A1: no checkpoint armed"
grep -q "inode compact: skipped (sweep checkpoint" "$WORK/sweep-a1.log" \
    || { cat "$WORK/sweep-a1.log"; fail "A1: no checkpoint-skip message"; }
if grep -q "^inode area compacted: " "$WORK/sweep-a1.log"; then
    fail "A1: compacted under a live checkpoint"
fi
"$H" ckp "$IMG_A" | grep -q "present=1" || fail "A1: CKP0 not live"
UA1S=$(used_of "$IMG_A")
echo "  auto-compaction skipped under the live checkpoint"

echo "== [A2] --compact with CKP0 live: skipped with a message =="
$B/invf-sweep "$IMG_A" --compact > "$WORK/compact-a2.log" 2>&1 || fail "A2 rc"
grep -q "inode compact: skipped (sweep checkpoint" "$WORK/compact-a2.log" \
    || { cat "$WORK/compact-a2.log"; fail "A2: no skip message"; }
if grep -q "compacted" "$WORK/compact-a2.log"; then fail "A2: compacted under a live checkpoint"; fi
[ "$(used_of "$IMG_A")" = "$UA1S" ] || fail "A2: area moved"
# the refusal is total: content + structures untouched, fsck clean
"$H" verify "$IMG_A" 40 24 || fail "A2: content wrong after the refused compact"
$B/invf-fsck "$IMG_A" > "$WORK/fsck-a2.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-a2.log" \
    || { cat "$WORK/fsck-a2.log"; fail "A2: fsck not clean under the live checkpoint"; }
echo "  volume untouched (content bit-exact, fsck OK)"

echo "== [A3] checkpoint realized -> compaction runs (auto) =="
$B/invf-sweep "$IMG_A" --realize > "$WORK/realize-a3.log" 2>&1 \
    || { cat "$WORK/realize-a3.log"; fail "realize A3"; }
grep -q "checkpoint: previous run realized" "$WORK/realize-a3.log" \
    || fail "A3: no realize line"
grep -q "^inode area compacted: " "$WORK/realize-a3.log" \
    || { cat "$WORK/realize-a3.log"; fail "A3: no compaction line"; }
grep "^inode area compacted: " "$WORK/realize-a3.log"
"$H" ckp "$IMG_A" | grep -q "present=0" || fail "A3: checkpoint survived"
UA1=$(used_of "$IMG_A"); LA1=$(live_of "$IMG_A")
echo "  after compaction: used=$UA1 live=$LA1 (post-sweep used was $UA1S)"
[ "$UA1" -lt "$UA1S" ] || fail "A3: area did not shrink"
[ "$UA1" = "$LA1" ] || fail "A3: compacted area is not exactly the live set"
"$H" verify "$IMG_A" 40 24 || fail "A3: content wrong after compaction"
# batched text survived the cut (the \x01tzb owner is a live record too)
[ "$(class_of "$IMG_A" c00.txt)" = "7" ] || fail "A3: c00.txt not TEXT post-compaction"
$B/invf-ls "$IMG_A" | grep -q "sub/g00" || fail "A3: directory subtree lost"
$B/invf-verify "$IMG_A" --deep | tail -1 | grep -q " 0 corrupt," \
    || fail "A3: verify --deep not clean"
$B/invf-fsck "$IMG_A" > "$WORK/fsck-a3.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-a3.log" || { cat "$WORK/fsck-a3.log"; fail "A3: fsck not clean"; }
echo "  live files bit-exact, batched text + subtree intact, fsck/verify clean"

echo "== [A4] quiescent re-sweep: no waste, no compaction =="
# WP27: the churn legs left every file write-hot (wheat ~= #rounds). The
# next sweeps do real decay work -- one record append per heat-carrying
# file per run (v1 hid exactly that churn in the journal pads; format v2
# carries heat in the records themselves, so the dead versions pile up in
# the inode area and the auto-compaction legitimately reclaims them).
# Cool the heat with idle sweeps first; the final re-sweep must be
# quiescent (nothing to decay, nothing to sweep) and compact nothing.
for i in $(seq 30); do
    $B/invf-sweep "$IMG_A" >/dev/null 2>&1 || fail "A4 cooling sweep $i"
done
$B/invf-sweep "$IMG_A" > "$WORK/sweep-a4.log" 2>&1 || fail "sweep A4"
if grep -q "^inode area compacted: " "$WORK/sweep-a4.log"; then
    fail "A4: compaction refired on a compact area"
fi
"$H" verify "$IMG_A" 40 24 || fail "A4: content wrong"

echo "== [A5] INVFS_NO_COMPACT=1 disables the automatic pass =="
"$H" churn "$IMG_A" 40 12 >/dev/null || fail "churn A5"
# run 1 (env off): the RAW rewrites are swept, blocks retire into the
# retention registry, CKP0 stays live -- compaction is gated by the
# checkpoint anyway; run 2 (env off) is the quiescent checkpoint-free end
# state where ONLY the env can be what suppresses the pass
INVFS_NO_COMPACT=1 $B/invf-sweep "$IMG_A" > "$WORK/sweep-a5a.log" 2>&1 \
    || { cat "$WORK/sweep-a5a.log"; fail "sweep A5a"; }
INVFS_NO_COMPACT=1 $B/invf-sweep "$IMG_A" > "$WORK/sweep-a5b.log" 2>&1 \
    || { cat "$WORK/sweep-a5b.log"; fail "sweep A5b"; }
"$H" ckp "$IMG_A" | grep -q "present=0" || fail "A5: checkpoint still live"
UA2=$(used_of "$IMG_A"); LA2=$(live_of "$IMG_A")
[ $(( (UA2 - LA2) * 10 )) -gt $(( UA2 * 3 )) ] || fail "A5: no waste to compact"
if grep -q "^inode area compacted: " "$WORK/sweep-a5b.log"; then
    fail "A5: INVFS_NO_COMPACT=1 did not suppress the pass"
fi
# and the same end state without the env compacts
$B/invf-sweep "$IMG_A" > "$WORK/sweep-a5c.log" 2>&1 || fail "sweep A5c"
grep -q "^inode area compacted: " "$WORK/sweep-a5c.log" \
    || { cat "$WORK/sweep-a5c.log"; fail "A5: next sweep did not compact"; }
[ "$(used_of "$IMG_A")" = "$(live_of "$IMG_A")" ] || fail "A5: area != live set"
"$H" verify "$IMG_A" 40 12 || fail "A5: content wrong"
echo "  env suppresses, next plain sweep compacts, content intact"

echo "== [A6] read-only volume: --compact skipped with a message =="
"$H" readonly "$IMG_A" 1 || fail "latch A"
$B/invf-sweep "$IMG_A" --compact > "$WORK/compact-a6.log" 2>&1 || fail "A6 rc"
grep -q "inode compact: skipped (volume is read-only" "$WORK/compact-a6.log" \
    || { cat "$WORK/compact-a6.log"; fail "A6: no read-only skip message"; }
"$H" readonly "$IMG_A" 0 || fail "unlatch A"
"$H" verify "$IMG_A" 40 12 || fail "A6: content wrong"
$B/invf-fsck "$IMG_A" | tail -1 | grep -q "^OK$" || fail "A6: fsck not clean"

echo "== [A7] rollback AFTER a compaction: the later checkpoint is bit-exact =="
INVFS_META_FRAC=8 $B/invf-mkfs "$IMG_G" 0.25 >/dev/null || fail "mkfs G"
"$H" churn "$IMG_G" 40 24 >/dev/null || fail "churn G"
# compaction #1: the forced pass alone, no checkpoint anywhere
$B/invf-sweep "$IMG_G" --compact > "$WORK/compact-g1.log" 2>&1 || fail "G: compact #1 rc"
grep -q "^inode area compacted: " "$WORK/compact-g1.log" \
    || { cat "$WORK/compact-g1.log"; fail "G: compact #1 did not run"; }
UG0=$(used_of "$IMG_G")
[ "$UG0" = "$(live_of "$IMG_G")" ] || fail "G: compacted area != live set"

echo "== [A7a] compact twice: the second pass is a strict no-op =="
$B/invf-sweep "$IMG_G" --compact > "$WORK/compact-g2.log" 2>&1 || fail "G: compact #2 rc"
grep -q "inode compact: nothing to do (area already compact" "$WORK/compact-g2.log" \
    || { cat "$WORK/compact-g2.log"; fail "G: second compact not a no-op"; }
if grep -q "^inode area compacted: " "$WORK/compact-g2.log"; then
    fail "G: second compact rewrote the area"
fi
[ "$(used_of "$IMG_G")" = "$UG0" ] || fail "G: second compact moved the area"
"$H" verify "$IMG_G" 40 24 || fail "G: content wrong after the no-op compact"
echo "  idempotent: area already compact, content intact"

echo "== [A7b] checkpoint armed post-compaction -> overwrite storm -> rollback =="
$B/invf-sweep "$IMG_G" > "$WORK/sweep-g.log" 2>&1 \
    || { cat "$WORK/sweep-g.log"; fail "G: sweep"; }
grep -q "checkpoint: #1 armed" "$WORK/sweep-g.log" || fail "G: no checkpoint armed"
grep -q "retained blocks held for rollback" "$WORK/sweep-g.log" \
    || { cat "$WORK/sweep-g.log"; fail "G: checkpoint did not stay live (nothing retained)"; }
# the rollback-horizon refusal fires on the auto pass too, post-compaction
grep -q "inode compact: skipped (sweep checkpoint" "$WORK/sweep-g.log" \
    || fail "G: auto-compaction not refused under the live checkpoint"
"$H" ckp "$IMG_G" | grep -q "present=1" || fail "G: CKP0 not live"
"$H" verify "$IMG_G" 40 24 || fail "G: content wrong post-sweep"
# post-checkpoint writes: a brand-new file + an overwrite of a record that
# lives in the COMPACTED area (positions the checkpoint names)
python3 -c "import os; open('$WORK/orig/g-new.bin','wb').write(os.urandom(50000)); open('$WORK/orig/g-f000.bin','wb').write(os.urandom(60000))"
$B/invf-cp "$IMG_G" "$WORK/orig/g-new.bin" g-new.bin >/dev/null || fail "G: cp new file"
$B/invf-cp "$IMG_G" "$WORK/orig/g-f000.bin" f000 >/dev/null || fail "G: overwrite f000"
$B/invf-cat "$IMG_G" g-new.bin "$WORK/out/g-new.bin" >/dev/null 2>&1 || fail "G: new file unreadable"
cmp -s "$WORK/orig/g-new.bin" "$WORK/out/g-new.bin" || fail "G: post-checkpoint state not live"
$B/invf-rollback "$IMG_G" > "$WORK/rb-g.log" 2>&1 \
    || { cat "$WORK/rb-g.log"; fail "G: rollback failed"; }
grep -q "rolled back to checkpoint #1" "$WORK/rb-g.log" || fail "G: no rollback line"
"$H" ckp "$IMG_G" | grep -q "present=0" || fail "G: CKP0 survived the rollback"
# bit-exact the pre-sweep state: f000's compacted version resurrected, the
# sweep's transformations and the post-checkpoint writes all gone
"$H" verify "$IMG_G" 40 24 || fail "G: post-rollback content not bit-exact"
if $B/invf-ls "$IMG_G" | grep -q "g-new.bin"; then
    fail "G: post-checkpoint file survived the rollback"
fi
$B/invf-fsck "$IMG_G" > "$WORK/fsck-g.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-g.log" || { cat "$WORK/fsck-g.log"; fail "G: fsck not clean"; }
$B/invf-verify "$IMG_G" --deep > "$WORK/verify-g.log" 2>&1 || true
grep -q " 0 corrupt," "$WORK/verify-g.log" || fail "G: verify --deep not clean"
echo "  rollback over a compacted area: bit-exact, post-checkpoint writes vanish"

echo "== [A8] a live seal: compaction proceeds and never touches parity =="
INVFS_META_FRAC=8 $B/invf-mkfs "$IMG_H" 0.25 >/dev/null || fail "mkfs H"
"$H" churn "$IMG_H" 40 24 >/dev/null || fail "churn H"
$B/invf-sweep "$IMG_H" --seal > "$WORK/seal-h1.log" 2>&1 \
    || { cat "$WORK/seal-h1.log"; fail "H: sweep --seal"; }
SEAL_LINE=$(grep "^\[seal\] " "$WORK/seal-h1.log")
STRIPES=$(echo "$SEAL_LINE" | sed 's/^\[seal\] \([0-9]*\) stripes.*/\1/')
[ "$STRIPES" -ge 1 ] 2>/dev/null || { cat "$WORK/seal-h1.log"; fail "H: nothing sealed"; }
"$H" ckp "$IMG_H" | grep -q "present=1" || fail "H: first sweep left no checkpoint"
# clear the checkpoint WITHOUT compacting (the env suppresses the auto
# pass); under the live seal the next arm declines by construction
INVFS_NO_COMPACT=1 $B/invf-sweep "$IMG_H" --realize > "$WORK/realize-h.log" 2>&1 \
    || { cat "$WORK/realize-h.log"; fail "H: realize"; }
grep -q "checkpoint: previous run realized" "$WORK/realize-h.log" \
    || fail "H: realize did not happen"
grep -q "checkpoint: declined (a redundancy seal is live" "$WORK/realize-h.log" \
    || { cat "$WORK/realize-h.log"; fail "H: ckp arm under a live seal did not decline"; }
if grep -q "^inode area compacted: " "$WORK/realize-h.log"; then
    fail "H: INVFS_NO_COMPACT=1 did not suppress the pass"
fi
"$H" ckp "$IMG_H" | grep -q "present=0" || fail "H: checkpoint still live"
UH0=$(used_of "$IMG_H"); LH0=$(live_of "$IMG_H")
[ $(( (UH0 - LH0) * 10 )) -gt $(( UH0 * 3 )) ] || fail "H: no waste to compact"
# the forced pass under the live seal (no checkpoint can exist): compacts
$B/invf-sweep "$IMG_H" --compact > "$WORK/compact-h.log" 2>&1 || fail "H: --compact rc"
grep -q "^inode area compacted: " "$WORK/compact-h.log" \
    || { cat "$WORK/compact-h.log"; fail "H: compaction under a live seal did not run"; }
if grep -q "skipped (sweep checkpoint" "$WORK/compact-h.log"; then
    fail "H: phantom checkpoint refusal under a seal"
fi
# parity provably untouched: deep verify clean, reseal reports zero drift
$B/invf-verify "$IMG_H" --deep > "$WORK/verify-h.log" 2>&1 || true
grep -q " 0 corrupt," "$WORK/verify-h.log" || { cat "$WORK/verify-h.log"; fail "H: corrupt files post-compact"; }
grep -q "parity: $STRIPES sealed stripes, 0 mismatched, 0 missing, 0 extra" \
    "$WORK/verify-h.log" || { cat "$WORK/verify-h.log"; fail "H: parity drifted"; }
"$H" verify "$IMG_H" 40 24 || fail "H: content wrong"
$B/invf-sweep "$IMG_H" --seal > "$WORK/seal-h2.log" 2>&1 || fail "H: reseal rc"
grep -q "; 0 stripes updated, " "$WORK/seal-h2.log" \
    || { cat "$WORK/seal-h2.log"; fail "H: compaction moved a sealed stripe"; }
$B/invf-fsck "$IMG_H" > "$WORK/fsck-h.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-h.log" || { cat "$WORK/fsck-h.log"; fail "H: fsck not clean"; }
echo "  compacted under the live seal; all $STRIPES parity stripes bit-identical"

fi

echo "== [B] --fast: generic only (no decomposition, no batching) =="
python3 - <<'PY'
import io, os, tarfile
d = "/dev/shm/wp22ecompact/orig"
txt = ("the quick brown fox jumps over the lazy dog\n"
       "int static return while for struct char void\n") * 400
open(os.path.join(d, "a.txt"), "w").write(txt)
out = io.BytesIO()
with tarfile.open(fileobj=out, mode="w") as tf:
    for name in ("m1.txt", "m2.txt"):
        data = txt.encode()
        ti = tarfile.TarInfo(name); ti.size = len(data)
        tf.addfile(ti, io.BytesIO(data))
open(os.path.join(d, "t.tar"), "wb").write(out.getvalue())
open(os.path.join(d, "r.bin"), "wb").write(os.urandom(150_000))
PY
$B/invf-mkfs "$IMG_B" 0.25 >/dev/null || fail "mkfs B"
for f in a.txt t.tar r.bin; do
    $B/invf-cp "$IMG_B" "$WORK/orig/$f" "$f" >/dev/null || fail "cp $f"
done
$B/invf-sweep "$IMG_B" --fast > "$WORK/sweep-b.log" 2>&1 \
    || { cat "$WORK/sweep-b.log"; fail "sweep --fast B"; }
grep -q "sweep done: swept=3 skipped=0 failed=0" "$WORK/sweep-b.log" \
    || { cat "$WORK/sweep-b.log"; fail "B: expected swept=3 skipped=0 failed=0"; }
# a .tar must NOT be decomposed, text must NOT be batched
[ "$(class_of "$IMG_B" t.tar)" = "4" ] || fail "B: t.tar not GENERIC"
[ "$(class_of "$IMG_B" a.txt)" = "4" ] || fail "B: a.txt not GENERIC"
[ "$(class_of "$IMG_B" r.bin)" = "1" ] || fail "B: r.bin not UNCOMPRESSIBLE"
if $B/invf-ls "$IMG_B" | grep -q "t.tar!"; then fail "B: t.tar was decomposed"; fi
for f in a.txt t.tar r.bin; do
    $B/invf-cat "$IMG_B" "$f" "$WORK/out/$f" >/dev/null 2>&1 || fail "B: cat $f"
    cmp -s "$WORK/orig/$f" "$WORK/out/$f" || fail "B: $f not bit-exact"
done
# reruns are pure no-ops (nothing RAW any more). WP71h: the exact skip
# count depends on the internal-owner lifecycle (a checkpoint armed for
# this very run keeps the \x01reten registry owner live during the walk:
# 3 files + owner = 4; without it, 3), so accept both -- the contract is
# "sweeps nothing, fails nothing".
$B/invf-sweep "$IMG_B" --fast > "$WORK/sweep-b2.log" 2>&1 || fail "sweep B2"
grep -q "sweep done: swept=0" "$WORK/sweep-b2.log" \
    || { cat "$WORK/sweep-b2.log"; fail "B: second --fast swept something"; }
grep -q "failed=0" "$WORK/sweep-b2.log" || fail "B: second --fast had failures"
UB2=$(used_of "$IMG_B")
$B/invf-sweep "$IMG_B" --fast > "$WORK/sweep-b3.log" 2>&1 || fail "sweep B3"
grep -qE "sweep done: swept=0 skipped=[0-9]+ failed=0" "$WORK/sweep-b3.log" \
    || { cat "$WORK/sweep-b3.log"; fail "B: third --fast not a no-op"; }
[ "$(used_of "$IMG_B")" = "$UB2" ] || fail "B: quiescent --fast moved the area"
$B/invf-verify "$IMG_B" --deep | tail -1 | grep -q " 0 corrupt," \
    || fail "B: verify --deep not clean"
$B/invf-fsck "$IMG_B" > "$WORK/fsck-b.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-b.log" || { cat "$WORK/fsck-b.log"; fail "B: fsck not clean"; }
echo "  RAW files -> generic, tar intact, text unbatched, rerun a no-op"

# ---- crash legs -------------------------------------------------------------
# $1=image $2=abort stage $3=files $4=rounds
crash_leg() {
    local img=$1 stage=$2 F=$3 R=$4
    local ub rc
    echo "== [crash:$stage] kill -9 mid-compaction, recover =="
    $B/invf-mkfs "$img" 0.25 >/dev/null || fail "mkfs $img"
    if [ "$(is_mapper "$img")" = 1 ]; then
        echo "  crash:$stage SKIPPED on a mapper volume: the CMP0 linear-
  compaction crash protocol is unreachable there (vol_inode_compact refuses;
  consolidation is the sweep meta-merge, whose crash-safety rides the ordinary
  record-append + journal machinery covered by test-mapper-crash)"
        return 0
    fi
    "$H" churn "$img" "$F" "$R" >/dev/null || fail "churn $img"
    ub=$(used_of "$img")
    set +e
    INVFS_COMPACT_ABORT_AT=$stage $B/invf-sweep "$img" --compact \
        > "$WORK/abort-$stage.log" 2>&1
    rc=$?
    set -e
    [ "$rc" = "137" ] || { cat "$WORK/abort-$stage.log"; fail "$stage: rc=$rc, want 137"; }
    if [ "$stage" = "staged" ]; then
        # pre-arm: the old area is byte-intact, no latch, no descriptor;
        # the stranded staging run is an ordinary orphan for fsck
        "$H" cmpend "$img" | grep -q "pending=0" || fail "$stage: CMP0 armed?!"
        "$H" wrena "$img" | grep -q "write_enabled=1" || fail "$stage: volume latched?!"
        [ "$(used_of "$img")" = "$ub" ] || fail "$stage: area moved pre-arm"
        set +e
        $B/invf-fsck "$img" -f > "$WORK/fsck-$stage.log" 2>&1
        rc=$?
        set -e
        [ "$rc" = "0" ] || [ "$rc" = "3" ] || { cat "$WORK/fsck-$stage.log"; fail "$stage: fsck -f rc=$rc"; }
        grep -qE "^  orphans:      [1-9]" "$WORK/fsck-$stage.log" \
            || { cat "$WORK/fsck-$stage.log"; fail "$stage: stranded staging not an orphan"; }
        $B/invf-fsck "$img" | tail -1 | grep -q "^OK$" || fail "$stage: fsck not clean"
        "$H" verify "$img" "$F" "$R" || fail "$stage: content wrong"
        # a plain re-run completes the pass
        $B/invf-sweep "$img" --compact > "$WORK/compact-$stage.log" 2>&1 \
            || fail "$stage: re-compact failed"
        grep -q "^inode area compacted: " "$WORK/compact-$stage.log" \
            || fail "$stage: re-run did not compact"
    else
        # armed/copying/copied: CMP0 + the read-only latch survive; the
        # volume must latch needs-recovery, sweep refuses, fsck -f rolls
        # the verified staging forward (idempotent)
        "$H" cmpend "$img" | grep -q "pending=1" || fail "$stage: CMP0 not armed"
        "$H" wrena "$img" | grep -q "write_enabled=0" || fail "$stage: volume not latched"
        $B/invf-fsck "$img" > "$WORK/fsckro-$stage.log" 2>&1 || true
        grep -q "an interrupted inode-area compaction is pending" \
            "$WORK/fsckro-$stage.log" \
            || { cat "$WORK/fsckro-$stage.log"; fail "$stage: no pending notice"; }
        set +e
        $B/invf-sweep "$img" > "$WORK/sweepref-$stage.log" 2>&1
        rc=$?
        set -e
        [ "$rc" != "0" ] || fail "$stage: sweep ran with CMP0 armed"
        grep -q "interrupted inode-area compaction is pending" \
            "$WORK/sweepref-$stage.log" || fail "$stage: sweep did not refuse"
        set +e
        $B/invf-fsck "$img" -f > "$WORK/fsck-$stage.log" 2>&1
        rc=$?
        set -e
        [ "$rc" = "0" ] || [ "$rc" = "3" ] || { cat "$WORK/fsck-$stage.log"; fail "$stage: fsck -f rc=$rc"; }
        grep -q "compaction: interrupted pass rolled forward" \
            "$WORK/fsck-$stage.log" || { cat "$WORK/fsck-$stage.log"; fail "$stage: no roll-forward"; }
        $B/invf-fsck "$img" | tail -1 | grep -q "^OK$" || fail "$stage: fsck not clean"
        $B/invf-verify "$img" --deep | tail -1 | grep -q " 0 corrupt," \
            || fail "$stage: verify --deep not clean"
        "$H" verify "$img" "$F" "$R" || fail "$stage: content wrong"
        "$H" cmpend "$img" | grep -q "pending=0" || fail "$stage: CMP0 survived recovery"
        # the recovered area is the compacted one
        [ "$(used_of "$img")" -lt "$ub" ] || fail "$stage: area not compacted"
        [ "$(used_of "$img")" = "$(live_of "$img")" ] || fail "$stage: area != live set"
    fi
    echo "  $stage: recovered, bit-exact, fsck/verify clean"
}

crash_leg "$IMG_C" staged  40 24
crash_leg "$IMG_D" armed   40 24
# "copying" needs a >1 MiB live stream (two copy chunks) for a real
# mid-copy tear: many small files
crash_leg "$IMG_E" copying 3400 2
crash_leg "$IMG_F" copied  40 24

echo
echo "COMPACT E2E: PASS"
