#!/bin/bash
# test-v3-fsync-crash.sh — WP80: the fsync-durability crash test for Meta-v3.
#
# The contract (docs/architecture/META-V3.md §4): once vol_sync (FUSE
# .fsync/.fdatasync) returns 0, the acknowledged write is durable against
# power loss. This test proves it end to end without a real power cut:
#
#   1. mkfs a v3 image.
#   2. create durable.bin (256 KiB) and vol_sync() it -- the fsync ack.
#   3. create unsynced.bin (128 KiB), then SIGKILL the process WITHOUT
#      vol_close (no final flush, no CLEAN superblock). This is the power
#      loss: the only thing pinning durable.bin is the fsync barrier.
#   4. assert the on-disk superblock is still DIRTY (a CLEAN mark would
#      mean the close ran, i.e. the crash was not abrupt).
#   5. reopen and assert durable.bin is present AND bit-exact, and that
#      unsynced.bin is complete-or-absent (v3 barriers every delta append,
#      so it is expected to be complete -- but the contract only promises
#      it is never torn).
#   6. fsck + verify --deep come back clean.
#
# On v3 there is no un-barriered *metadata* tail to zero: vol_delta_append
# barriers each record before publishing it (see META-V3.md §4.3), so the
# kill IS the strongest available simulation -- there is nothing the fsync
# left un-barriered that could be dropped to make the file vanish.
#
# Run from the repo root after `make`, or via
#   INVFS_E2E_AGENT=wp80-durability bash tools/run-e2e.sh tools/test-v3-fsync-crash.sh
# Image paths are RELATIVE (blkio treats /dev/* as raw devices).
set -e
set -o pipefail

REPO="${REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
B=$REPO/bin
WORK=/dev/shm/wp80-crash
IMG=wp80-crash.img
rm -rf "$WORK" && mkdir -p "$WORK"
cd /dev/shm
rm -f "$IMG"

fail() { echo "FAIL: $*" >&2; exit 1; }

OBJS="$(sed "s|^|$REPO/|" "$REPO/build/core_objs.txt")"

cat > "$WORK/crash_harness.c" <<'EOF'
/* crash_harness.c — WP80 fsync-durability driver (generated by
 * tools/test-v3-fsync-crash.sh; links the built engine objects). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <signal.h>
#include "volume.h"
#include "invarifs.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

static void fill_pattern(uint8_t *b, size_t n, uint64_t seed)
{
    uint64_t x = seed ? seed : 0x9E3779B97F4A7C15ull;
    size_t i;
    for (i = 0; i < n; i++) {
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        b[i] = (uint8_t)(x >> 32);
    }
}

static void assert_file(invfs_volume *v, const char *name, size_t len,
                        uint64_t seed)
{
    uint64_t id = vol_find(v, name);
    uint8_t *buf = NULL, *want;
    size_t blen = 0;
    if (!id) die("assert_file: absent");
    if (vol_read_file(v, id, &buf, &blen) != 0) die("assert_file: read");
    if (blen != len) die("assert_file: size");
    want = malloc(len);
    if (!want) die("oom");
    fill_pattern(want, len, seed);
    if (memcmp(want, buf, len) != 0) die("assert_file: content mismatch");
    free(want);
    free(buf);
}

static uint64_t create_pattern(invfs_volume *v, const char *name,
                               size_t len, uint64_t seed)
{
    uint8_t *buf = malloc(len);
    uint64_t id;
    if (!buf) die("oom");
    fill_pattern(buf, len, seed);
    id = vol_create_file(v, name, buf, len);
    free(buf);
    if (!id) die("create_pattern");
    return id;
}

/* write + fsync, then die abruptly: no vol_close, no CLEAN superblock */
static int cmd_crashfsync(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "durable.bin", 256 * 1024, 0xD0);
    if (vol_sync(v) != 0) die("vol_sync (the fsync ack) failed");
    /* a later, un-fsync'd write: v3 makes it durable too, but the contract
     * only promises complete-or-absent */
    create_pattern(v, "unsynced.bin", 128 * 1024, 0x55);
    fflush(NULL);
    fprintf(stderr, "V3CRASH-READY: fsync acknowledged; killing without close\n");
    raise(SIGKILL);
    return 0;   /* not reached */
}

static int cmd_check(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    /* the fsync-acknowledged write must be present and bit-exact */
    assert_file(v, "durable.bin", 256 * 1024, 0xD0);
    /* complete-or-absent, never torn */
    if (vol_find(v, "unsynced.bin"))
        assert_file(v, "unsynced.bin", 128 * 1024, 0x55);
    vol_close(v);
    printf("V3CRASH-CHECK-OK\n");
    return 0;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: harness <cmd> <img>\n");
        return 2;
    }
    if (strcmp(argv[1], "crashfsync") == 0 && argc == 3)
        return cmd_crashfsync(argv[2]);
    if (strcmp(argv[1], "check") == 0 && argc == 3)
        return cmd_check(argv[2]);
    fprintf(stderr, "bad args\n");
    return 2;
}
EOF

gcc -std=gnu11 -O2 -I$REPO/src -I$REPO/src/core -I$REPO/src/codecs -I$REPO/src/recipes -I$REPO/src/vendor7z -o "$WORK/crash_harness" \
    "$WORK/crash_harness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread \
    || fail "harness build"
H=$WORK/crash_harness

echo "== WP80: fsync-acknowledged v3 write survives an abrupt power loss =="
$B/invf-mkfs $IMG 0.0625 >"$WORK/mkfs.log" || fail "mkfs"
# a freshly formatted image is CLEAN (0xCA); vol_mark_dirty marks it DIRTY (0xDA) when opened RW
python3 - "$IMG" <<'PY' || fail "fresh image not CLEAN"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x20)
sys.exit(0 if struct.unpack_from("<I", sb, 0x18)[0] == 0xCA else 1)
PY
set +e
"$H" crashfsync $IMG >"$WORK/crash.log" 2>&1
RC=$?
set -e
[ "$RC" = "137" ] || { cat "$WORK/crash.log"; fail "expected SIGKILL (137), got $RC"; }
grep -q "V3CRASH-READY" "$WORK/crash.log" || { cat "$WORK/crash.log"; fail "fsync ack not reached"; }
# the crash was abrupt: the superblock must still be DIRTY (no CLEAN write)
python3 - "$IMG" <<'PY' || fail "superblock went CLEAN before close (barrier ordering broken?)"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x20)
state = struct.unpack_from("<I", sb, 0x18)[0]
sys.exit(0 if state == 0xDA else 1)
PY
# reopen: the acknowledged file must be there, bit-exact
"$H" check $IMG || fail "check"
$B/invf-fsck $IMG >"$WORK/fsck.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck.log" || { cat "$WORK/fsck.log"; fail "fsck not OK"; }
$B/invf-verify $IMG --deep >"$WORK/verify.log" 2>&1 || fail "verify"
grep -q " 0 corrupt," "$WORK/verify.log" || fail "verify reported corrupt"
echo "   durable.bin present + bit-exact after kill; unsynced complete-or-absent; fsck/verify clean"
echo "PASS: WP80 v3 fsync-durability crash test"
