#!/bin/bash
# test-flushfail.sh — WP22c e2e: the two durability bugs the dm-flakey
# tier found (tools/flakey/FINDINGS.md), reproduced deterministically on
# plain image files (no root/dm needed), plus the fsck/verify agreement
# invariant. Persistent regression suite.
#
#   Leg A (F1): the INVFS_SYNC_FAIL_AT hook simulates the leg-2 error
#   window: the Nth vol_sync of the process zeroes the un-barriered
#   inode-area tail (what a dropped writeback leaves behind) and reports
#   EIO. Asserts: the failure is LOUD at the failing sync, the volume
#   latches (later mutations refused), the append cursor is re-anchored
#   at the last barriered position, and after a clean close + reopen the
#   barriered file is present and bit-exact while the un-barriered one is
#   absent on v2 (complete-or-absent, never silently lost after an ack).
#   WP80: v3 is the only format mkfs writes now. Its delta append is
#   itself barriered (see docs/architecture/META.md), so the second
#   create is durable BEFORE the failing sync; the failure still latches
#   and refuses later mutations, and the file comes back bit-exact
#   (complete-or-absent, here: complete).
#
#   Leg B (F2 rename): a fast-path rename must kill the SOURCE name's own
#   record (the pre-fix tombstone named the shared id's newest record --
#   the copy -- and killed nothing at replay, leaving both names live).
#   Asserts in-session and post-reopen: source absent, target bit-exact.
#
#   Leg C (F2 shared-id retire): deleting one name of a hardlinked pair
#   must not drop the mappings the survivor resolves through (the old
#   retire dropped the shared id's L2P wholesale -> present-but-
#   unreadable). Asserts the survivor reads bit-exact in-session and
#   after reopen, fsck + verify clean.
#
#   Leg D (F2 fsck honesty): a live record whose mappings are gone (built
#   offline: hardlinked survivor + legacy tombstone + zeroed journal
#   tail -- the leg-5 artifact's shape) must be SEEN by fsck: l2p_miss
#   counted, the file named, rc=3 -- and verify --deep must say CORRUPT
#   for the same file. Pre-fix fsck reported OK with 0 misses.
#
#   Leg E (F2 container rename): renaming a swept container file (TARR:
#   num_children==0 but payload in "name!partN"/"name!recipe" siblings)
#   must take the sibling-aware slow path, not the hardlink fast path --
#   the hardlink would move the anchor and strand the recipe under the
#   old name (the renamed container never reads again). Asserts the
#   renamed container reads bit-exact in-session and after reopen.
#
# The engine harness is generated below and linked against the built
# engine objects (the test-astv2.sh convention). Run from the repo root
# after `make`. Uses /dev/shm like the other soak scripts; image paths
# are RELATIVE (blkio treats /dev/* as raw devices).
set -e
set -o pipefail

REPO="${REPO:-$(cd "$(dirname "$0")/.." && pwd)}"   # override with the worktree when testing a branch
B=$REPO/bin
WORK=/dev/shm/wp22c
IMG_A=wp22c-a.img     # leg A: sync failure latch + re-anchor
IMG_B=wp22c-b.img     # leg B: rename kills the source name
IMG_C=wp22c-c.img     # leg C: shared-id retire keeps the survivor readable
IMG_D=wp22c-d.img     # leg D: fsck/verify agree on a dangling live record
IMG_E=wp22c-e.img     # leg E: swept-container rename moves the siblings
rm -rf "$WORK" && mkdir -p "$WORK"
cd /dev/shm
rm -f "$IMG_A" "$IMG_B" "$IMG_C" "$IMG_D" "$IMG_E"

fail() { echo "FAIL: $*" >&2; exit 1; }

# WP80: on-disk format probe (format_version byte at 0x90; 0 = v0 generation).
img_is_meta() {
    python3 - "$1" <<'PY'
import sys
try:
    with open(sys.argv[1], "rb") as f:
        sb = f.read(0x91)
except OSError:
    sys.exit(1)
sys.exit(0 if len(sb) >= 0x91 and sb[0x90] == 0 else 1)
PY
}

# ---- the engine harness ------------------------------------------------
# canonical core object list emitted by `make all` (build/core_objs.txt)
OBJS="$(sed "s|^|$REPO/|" "$REPO/build/core_objs.txt")"

cat > "$WORK/ff_harness.c" <<'EOF'
/* ff_harness.c — WP22c engine-level test driver (generated by
 * tools/test-flushfail.sh; links the engine objects, public API + the
 * on-disk structs for the offline sabotage leg). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "volume.h"
#include "invarifs.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

static void fill_pattern(uint8_t *b, size_t n, uint64_t seed)
{
    uint64_t x = seed ? seed : 0x9E3779B97F4A7C15ull;
    size_t i;
    for (i = 0; i < n; i++) {
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        b[i] = (uint8_t)(x >> 32);
    }
}

static void assert_file(invfs_volume *v, const char *name, size_t len,
                        uint64_t seed)
{
    uint64_t id = vol_find(v, name);
    uint8_t *buf = NULL, *want;
    size_t blen = 0;
    if (!id) die("assert_file: absent");
    if (vol_read_file(v, id, &buf, &blen) != 0) die("assert_file: read");
    if (blen != len) die("assert_file: size");
    want = malloc(len);
    if (!want) die("oom");
    fill_pattern(want, len, seed);
    if (memcmp(want, buf, len) != 0) die("assert_file: content mismatch");
    free(want);
    free(buf);
}

/* WP80: the leg-A post-crash assertion depends on the format. On v3 the
 * delta append is barriered, so an un-fsync'd create is already durable;
 * on v2 it is not. Read the on-disk format marker directly. */
static int img_is_meta(const char *img)
{
    FILE *f = fopen(img, "rb");
    invfs_superblock sb;
    int v3 = 0;
    if (f && fread(&sb, sizeof sb, 1, f) == 1)
        v3 = (sb.vol_flags & VOLF_META) != 0;
    if (f) fclose(f);
    return v3;
}

static uint64_t create_pattern(invfs_volume *v, const char *name,
                               size_t len, uint64_t seed)
{
    uint8_t *buf = malloc(len);
    uint64_t id;
    if (!buf) die("oom");
    fill_pattern(buf, len, seed);
    id = vol_create_file(v, name, buf, len);
    free(buf);
    if (!id) die("create_pattern");
    return id;
}

/* ---- leg A: failed barrier -> latch + re-anchor ----------------------- */
static int cmd_f1run(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t anchor;
    if (!v) die("open");
    /* pinned file: committed and barriered on the healthy device */
    create_pattern(v, "pin1.bin", 100 * 1024, 11);
    if (vol_sync(v) != 0) die("first sync failed on a healthy image");
    anchor = vol_inode_area_pos(v);
    /* the un-barriered file: committed, then the storm hits at the sync */
    create_pattern(v, "hole1.bin", 200 * 1024, 22);
    if (vol_sync(v) == 0)
        die("second sync succeeded despite INVFS_SYNC_FAIL_AT");
    /* loud at the failing op; latched from here on */
    if (vol_write_enabled(v))
        die("volume not latched after a failed sync");
    /* the append cursor must never sit past unpersisted bytes */
    if (vol_inode_area_pos(v) != anchor)
        die("append cursor not re-anchored at the last barrier");
    /* later mutations fail loudly instead of appending into the hole */
    if (vol_create_file(v, "post.bin", (const uint8_t *)"x", 1) != 0)
        die("create accepted on a latched volume");
    vol_close(v);
    printf("F1RUN-OK\n");
    return 0;
}

static int cmd_f1check(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    assert_file(v, "pin1.bin", 100 * 1024, 11);
    /* complete-or-absent: never torn, never silently lost after an ack.
     * v3's per-append barrier makes the un-fsync'd create durable, so it
     * must be present and bit-exact; v2 loses the un-barriered tail. */
    if (img_is_meta(img)) {
        assert_file(v, "hole1.bin", 200 * 1024, 22);
    } else if (vol_find(v, "hole1.bin")) {
        die("hole1.bin survived a failed sync");
    }
    if (vol_find(v, "post.bin"))  die("post.bin exists");
    vol_close(v);
    printf("F1CHECK-OK\n");
    return 0;
}

/* ---- leg B: a fast-path rename retires the source's own record -------- */
static int cmd_f2rename(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "fileA.bin", 300 * 1024, 33);
    if (vol_rename(v, "fileA.bin", "fileB.bin") != 0) die("rename");
    /* in-session: the source name must be gone immediately */
    if (vol_find(v, "fileA.bin")) die("source name survived the rename");
    if (!vol_find(v, "fileB.bin")) die("target name missing after rename");
    vol_close(v);
    /* and the same after a full reopen (the on-disk tombstone must hit) */
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, "fileA.bin")) die("source name resurrected at reopen");
    assert_file(v, "fileB.bin", 300 * 1024, 33);
    vol_close(v);
    printf("F2RENAME-OK\n");
    return 0;
}

/* ---- leg C: a shared-id retire must keep the survivor's mappings ------ */
static int cmd_f2link(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "fileC.bin", 160 * 1024, 44);
    if (vol_hardlink(v, "fileC.bin", "linkC.bin") != 0) die("hardlink");
    if (vol_delete_file(v, "fileC.bin") != 0) die("delete");
    assert_file(v, "linkC.bin", 160 * 1024, 44);   /* in-session */
    vol_close(v);
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, "fileC.bin")) die("deleted name still present");
    assert_file(v, "linkC.bin", 160 * 1024, 44);   /* after replay */
    vol_close(v);
    printf("F2LINK-OK\n");
    return 0;
}

/* ---- leg D: build the dangling live record (the leg-5 shape) ---------- */
static int cmd_f2mkdangle(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t vid;
    if (!v) die("open");
    /* bystander FIRST: the victim's mappings must be the journal tail */
    create_pattern(v, "bystanderB.bin", 32 * 1024, 55);
    vid = create_pattern(v, "victimV.bin", 160 * 1024, 66);
    /* the survivor shares the victim's id (the rename fast path's shape) */
    if (vol_hardlink(v, "victimV.bin", "survivorS.bin") != 0)
        die("hardlink");
    vol_close(v);
    printf("F2MKDANGLE-OK victim_id=%llu\n", (unsigned long long)vid);
    return 0;
}

/* WP27: there are no file maps in the journal to drop -- the dangling
 * shape is the live record whose entries carry invalid pbas. Offline:
 * delete the victim's name through the engine (the id's blocks stay
 * referenced by the survivor twin's record), then zero the survivor's
 * live record's entry pbas in the image + restamp its CRC. The open
 * scan's consistent cut hides the record (never live); fsck counts the
 * invalid-pba entries as the miss and -f quarantines. */
static int cmd_f2sabotage(const char *img, uint64_t victim_id)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t last_pos = 0;
    if (!v) die("open");
    (void)victim_id;
    if (vol_delete_file(v, "victimV.bin") != 0) die("delete victim");
    if (vol_flush(v) != 0) die("flush");

    /* WP70: use vol_inode_next (mapper-aware) to locate the survivor record.
     * The legacy linear scan of the contiguous inode area missed records that
     * live in dynamic mapper extents (WP30). */
    {
        uint64_t pos = vol_inode_area_start(v);
        for (;;) {
            uint32_t magic, rl;
            uint64_t id, sz;
            char nm[INVFS_MAX_NAME + 1];
            uint64_t next = vol_inode_next(v, pos, &magic, &id, &sz,
                                           nm, sizeof nm, &rl);
            if (!next) break;
            if (magic == INODE_REC_MAGIC && strcmp(nm, "survivorS.bin") == 0)
                last_pos = pos;
            pos = next;
        }
    }
    vol_close(v);

    if (!last_pos) die("survivor record not found");

    /* offline: zero the survivor record's entry pbas + restamp its CRC */
    {
        FILE *f = fopen(img, "r+b");
        if (!f) die("fopen");
        {
            uint8_t *rb;
            invfs_inode_rec rh;
            invfs_ast_hdr ah;
            size_t base, ent0;
            uint32_t i, ncrc;
            if (fseek(f, (long)last_pos, SEEK_SET) != 0) die("seek");
            if (fread(&rh, sizeof rh, 1, f) != 1) die("rec head");
            if (rh.rec_len < INVFS_REC_HDR_LEN + 1 ||
                rh.rec_len > INVFS_MAX_REC_LEN)
                die("rec_len");
            rb = malloc(rh.rec_len);
            if (!rb) die("oom");
            if (fseek(f, (long)last_pos, SEEK_SET) != 0 ||
                fread(rb, rh.rec_len, 1, f) != 1) die("rec read");
            base = (size_t)(invfs_rec_cbody((const invfs_inode_rec *)rb) - rb);
            if (invfs_ast_hdr_parse(rb + base, rh.rec_len - base, &ah) != 0)
                die("recipe parse");
            ent0 = base + ah.hdr_len;
            if (ent0 + (size_t)ah.num_blocks *
                    sizeof(invfs_ast_block_entry) > rh.rec_len)
                die("entries oob");
            for (i = 0; i < ah.num_blocks; i++) {
                invfs_ast_block_entry *e = (invfs_ast_block_entry *)
                    (rb + ent0 + (size_t)i * sizeof *e);
                e->pba = 0;
            }
            ncrc = invfs_crc32c(rb, rh.rec_len);
            if (fseek(f, (long)last_pos, SEEK_SET) != 0 ||
                fwrite(rb, rh.rec_len, 1, f) != 1 ||
                fwrite(&ncrc, 4, 1, f) != 1)
                die("rec rewrite");
            free(rb);
        }
        fclose(f);
    }
    printf("F2SABOTAGE-OK\n");
    return 0;
}

/* ---- leg G: a compaction crash at each stage is consistent-cut -------- */
static int cmd_f3fill(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    /* the pinned file: committed and barriered BEFORE the crash run */
    create_pattern(v, "pinA.bin", 96 * 1024, 77);
    if (vol_sync(v) != 0) die("sync");
    vol_close(v);
    printf("F3FILL-OK\n");
    return 0;
}

/* the create below dies SIGKILL (in its pre_record flush) */
static int cmd_f3crash(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "newB.bin", 128 * 1024, 88);
    vol_close(v);
    printf("F3CRASH-survived\n");   /* reached only when the hook is off */
    return 0;
}

static int cmd_f3check(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    /* the pinned file must be intact; the crashed one is present-and-
     * bit-exact or absent (complete-or-absent) -- never torn */
    assert_file(v, "pinA.bin", 96 * 1024, 77);
    if (vol_find(v, "newB.bin"))
        assert_file(v, "newB.bin", 128 * 1024, 88);
    vol_close(v);
    printf("F3CHECK-OK\n");
    return 0;
}

/* leg G2 variant: the pinned file came from the OLD (flat-log) binaries,
 * so only the crashed create's complete-or-absent is checked here; the
 * pinned file's bit-exactness is asserted by the leg via invf-cat | cmp */
static int cmd_f3checkb(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    if (vol_find(v, "newB.bin"))
        assert_file(v, "newB.bin", 128 * 1024, 88);
    vol_close(v);
    printf("F3CHECKB-OK\n");
    return 0;
}

/* ---- leg I: bitmap/journal divergence (WP22d open-time reconcile) ---- */
/* create the survivor, sync, and print the pba of its first segment (the
 * leg then clears that bit in the on-disk bitmap, simulating a bitmap
 * page dropped by a window while the journal append landed) */
static int cmd_f4mkdiv(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t id, pba = 0;
    if (!v) die("open");
    id = create_pattern(v, "survivorS.bin", 192 * 1024, 55);
    if (vol_sync(v) != 0) die("sync");
    /* WP27: the segment's pba lives in the record's AST entry now; the
     * WAL is owner-only and never carries file maps */
    {
        uint64_t pos = vol_inode_area_start(v);
        while (pos) {
            uint32_t magic, rl;
            uint64_t ino, fsz, np;
            np = vol_inode_next(v, pos, &magic, &ino, &fsz, NULL, 0, &rl);
            if (!np) break;
            pos = np;
            if (magic != INODE_REC_MAGIC || ino != id) continue;
            {
                uint8_t *rb = malloc(rl);
                invfs_ast_hdr ah;
                if (rb && vol_read_raw(v, np - rl - 4, rb, rl) == 0) {
                    size_t base = (size_t)(invfs_rec_cbody(
                                       (const invfs_inode_rec *)rb) - rb);
                    if (invfs_ast_hdr_parse(rb + base, rl - base, &ah) == 0 &&
                        ah.num_blocks >= 1) {
                        const invfs_ast_block_entry *e =
                            (const invfs_ast_block_entry *)
                            (rb + base + ah.hdr_len);
                        if (e->length && e->pba)
                            pba = e->pba;
                    }
                }
                free(rb);
            }
            if (pba) break;
        }
    }
    if (!pba) die("no segment pba for the survivor");
    printf("F4MKDIV-OK pba=%llu\n", (unsigned long long)pba);
    vol_close(v);
    return 0;
}

/* after the sabotage: the open must reconcile (the survivor's block is
 * forced used), then a fresh write must NOT be allocated on it */
static int cmd_f4checkdiv(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    assert_file(v, "survivorS.bin", 192 * 1024, 55);
    create_pattern(v, "attackerA.bin", 256 * 1024, 66);
    if (vol_sync(v) != 0) die("sync");
    assert_file(v, "survivorS.bin", 192 * 1024, 55);
    assert_file(v, "attackerA.bin", 256 * 1024, 66);
    vol_close(v);
    printf("F4CHECKDIV-OK\n");
    return 0;
}

/* WP27: mark the volume DIRTY with a valid CRC (the drop-window crash
 * shape; python lacks crc32c, so this runs here where invfs_crc32c is
 * linked in) */
static int cmd_f4dirty(const char *img)
{
    FILE *f = fopen(img, "r+b");
    invfs_superblock sb;
    if (!f) die("fopen");
    if (fseek(f, 0, SEEK_SET) != 0 ||
        fread(&sb, sizeof sb, 1, f) != 1) die("sb read");
    sb.state = INVFS_STATE_DIRTY;
    sb.checksum = invfs_crc32c(&sb, offsetof(invfs_superblock, checksum));
    if (fseek(f, 0, SEEK_SET) != 0 ||
        fwrite(&sb, sizeof sb, 1, f) != 1) die("sb write");
    fclose(f);
    printf("F4DIRTY-OK\n");
    return 0;
}

/* ---- leg E: renaming a swept container keeps its siblings ----------- */
static int cmd_f2cp(const char *img, const char *host, const char *name)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    FILE *f;
    long len;
    uint8_t *buf;
    uint64_t id;
    if (!v) die("open");
    f = fopen(host, "rb");
    if (!f) die("host fopen");
    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||
        fseek(f, 0, SEEK_SET) != 0) die("host size");
    buf = malloc((size_t)len);
    if (!buf) die("oom");
    if (fread(buf, 1, (size_t)len, f) != (size_t)len) die("host read");
    fclose(f);
    id = vol_create_file(v, name, buf, (size_t)len);
    free(buf);
    if (!id) die("create");
    vol_close(v);
    printf("F2CP-OK\n");
    return 0;
}

/* rename name->newname, then bit-compare newname against the host file,
 * in-session and after a full reopen */
static int cmd_f2mv(const char *img, const char *name, const char *newname,
                    const char *host)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    FILE *f;
    long len;
    uint8_t *want, *got = NULL;
    size_t glen = 0;
    uint64_t id;
    int rc = 1;
    if (!v) die("open");
    f = fopen(host, "rb");
    if (!f) die("host fopen");
    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||
        fseek(f, 0, SEEK_SET) != 0) die("host size");
    want = malloc((size_t)len);
    if (!want) die("oom");
    if (fread(want, 1, (size_t)len, f) != (size_t)len) die("host read");
    fclose(f);
    if (vol_rename(v, name, newname) != 0) die("rename");
    if (vol_find(v, name)) die("container source name survived the rename");
    id = vol_find(v, newname);
    if (!id) die("renamed container missing");
    if (vol_read_file(v, id, &got, &glen) != 0)
        die("renamed container unreadable in-session");
    if (glen != (size_t)len || memcmp(want, got, glen) != 0)
        die("renamed container content mismatch in-session");
    free(got); got = NULL;
    vol_close(v);
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, name)) die("container source resurrected at reopen");
    id = vol_find(v, newname);
    if (!id) die("renamed container missing after reopen");
    if (vol_read_file(v, id, &got, &glen) != 0)
        die("renamed container unreadable after reopen");
    if (glen != (size_t)len || memcmp(want, got, glen) != 0)
        die("renamed container content mismatch after reopen");
    rc = 0;
    free(got);
    free(want);
    vol_close(v);
    if (rc == 0) printf("F2MV-OK\n");
    return rc;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: harness <cmd> <img> [args]\n");
        return 2;
    }
    if (strcmp(argv[1], "f1run") == 0 && argc == 3)
        return cmd_f1run(argv[2]);
    if (strcmp(argv[1], "f1check") == 0 && argc == 3)
        return cmd_f1check(argv[2]);
    if (strcmp(argv[1], "f2rename") == 0 && argc == 3)
        return cmd_f2rename(argv[2]);
    if (strcmp(argv[1], "f2link") == 0 && argc == 3)
        return cmd_f2link(argv[2]);
    if (strcmp(argv[1], "f2mkdangle") == 0 && argc == 3)
        return cmd_f2mkdangle(argv[2]);
    if (strcmp(argv[1], "f2sabotage") == 0 && argc == 4)
        return cmd_f2sabotage(argv[2], strtoull(argv[3], NULL, 0));
    if (strcmp(argv[1], "f3fill") == 0 && argc == 3)
        return cmd_f3fill(argv[2]);
    if (strcmp(argv[1], "f3crash") == 0 && argc == 3)
        return cmd_f3crash(argv[2]);
    if (strcmp(argv[1], "f3check") == 0 && argc == 3)
        return cmd_f3check(argv[2]);
    if (strcmp(argv[1], "f3checkb") == 0 && argc == 3)
        return cmd_f3checkb(argv[2]);
    if (strcmp(argv[1], "f4mkdiv") == 0 && argc == 3)
        return cmd_f4mkdiv(argv[2]);
    if (strcmp(argv[1], "f4checkdiv") == 0 && argc == 3)
        return cmd_f4checkdiv(argv[2]);
    if (strcmp(argv[1], "f4dirty") == 0 && argc == 3)
        return cmd_f4dirty(argv[2]);
    if (strcmp(argv[1], "f2cp") == 0 && argc == 5)
        return cmd_f2cp(argv[2], argv[3], argv[4]);
    if (strcmp(argv[1], "f2mv") == 0 && argc == 6)
        return cmd_f2mv(argv[2], argv[3], argv[4], argv[5]);
    fprintf(stderr, "bad args\n");
    return 2;
}
EOF

gcc -std=gnu11 -O2 -I$REPO/src -I$REPO/src/core -I$REPO/src/codecs -I$REPO/src/recipes -I$REPO/src/vendor7z -o "$WORK/ff_harness" \
    "$WORK/ff_harness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread \
    || fail "harness build"
H=$WORK/ff_harness

# ---- leg A: F1 -- failed sync latches + re-anchors ----------------------
echo "== leg A: failed barrier -> latch, re-anchor, complete-or-absent =="
$B/invf-mkfs $IMG_A 0.0625 >"$WORK/mkfs-a.log" || fail "mkfs A"
# the 2nd vol_sync of the process reports EIO (and drops the un-barriered
# v2 inode-area tail; on v3 the delta append is already barriered)
INVFS_SYNC_FAIL_AT=2 "$H" f1run $IMG_A 2>"$WORK/f1run.log" || {
    cat "$WORK/f1run.log"; fail "f1run"; }
grep -q "latched" "$WORK/f1run.log" || { cat "$WORK/f1run.log"; fail "no latch log"; }
"$H" f1check $IMG_A || fail "f1check"
# recovery ladder: the volume stayed DIRTY (the latch persisted), the
# un-barriered tail's blocks (if any) are reclaimed, the volume ends
# structurally clean. On v2 fsck -f exits 3 ("issues found") for the
# orphans it just freed -- the honest answer to a real loss; on v3 nothing
# was lost, so the ladder simply comes back clean.
set +e
$B/invf-fsck $IMG_A -f >"$WORK/fsck-a1.log" 2>&1
set -e
$B/invf-fsck $IMG_A >"$WORK/fsck-a2.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-a2.log" || { cat "$WORK/fsck-a2.log"; fail "fsck not clean post-recovery"; }
$B/invf-verify $IMG_A --deep >"$WORK/verify-a.log" 2>&1 || fail "verify A"
grep -q " 0 corrupt," "$WORK/verify-a.log" || fail "verify A reported corrupt"
echo "   pinned file bit-exact, complete-or-absent held, latch held, fsck clean"

# ---- leg B: F2 -- the rename kills the source's own record --------------
echo "== leg B: fast-path rename retires the source name =="
$B/invf-mkfs $IMG_B 0.0625 >"$WORK/mkfs-b.log" || fail "mkfs B"
"$H" f2rename $IMG_B || fail "f2rename"
$B/invf-fsck $IMG_B >"$WORK/fsck-b.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-b.log" || { cat "$WORK/fsck-b.log"; fail "fsck B not OK"; }
$B/invf-verify $IMG_B --deep >"$WORK/verify-b.log" 2>&1 || fail "verify B"
grep -q " 0 corrupt," "$WORK/verify-b.log" || fail "verify B reported corrupt"
echo "   source name retired (in-session and after reopen), target bit-exact"

# ---- leg C: F2 -- shared-id retire keeps the survivor's mappings --------
echo "== leg C: shared-id retire keeps the survivor readable =="
$B/invf-mkfs $IMG_C 0.0625 >"$WORK/mkfs-c.log" || fail "mkfs C"
"$H" f2link $IMG_C || fail "f2link"
$B/invf-fsck $IMG_C >"$WORK/fsck-c.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-c.log" || { cat "$WORK/fsck-c.log"; fail "fsck C not OK"; }
$B/invf-verify $IMG_C --deep >"$WORK/verify-c.log" 2>&1 || fail "verify C"
grep -q " 0 corrupt," "$WORK/verify-c.log" || fail "verify C reported corrupt"
echo "   survivor bit-exact in-session and after reopen; fsck/verify clean"

# ---- WP80: v2-only legs D-I are skipped on a Meta-v3 volume ------------
# invf-mkfs writes Meta-v3 only (v2 is retired in v0.5.0). Legs D-I below
# exercise the retired v2 machinery: the contiguous inode-area record
# stream and its vol_inode_next walk (D, I), the flat/slotted v2 journal
# and mid-compaction crash stages (F, G, G2, H), and the CKP0 sweep
# rename leg (E). None of that exists on a v3 volume,
# so they cannot run. The v3 equivalents of rename/retire/fsck honesty are
# covered by tools/test-meta.sh, test-meta-fold.sh and
# test-meta-delta.sh. Legs A-C above run on the live format.
if img_is_meta "$IMG_A"; then
    echo "== legs D-I: SKIP (v2-only machinery retired on Meta; see test-meta*.sh) =="
    echo "PASS: WP22c (v3: flush/sync failure latch + rename/retire)"
    exit 0
fi

# ---- leg D: WP22d -- the dangling live record is cut + quarantined ------
# (pre-WP22d this leg asserted fsck only COUNTED the miss; the consistent
# cut now HIDES the dangling record and fsck -f quarantines it, so the
# final fsck comes back OK with the loss explicitly listed)
echo "== leg D: fsck reports the cut, hides the dangling record, -f quarantines =="
$B/invf-mkfs $IMG_D 0.0625 >"$WORK/mkfs-d.log" || fail "mkfs D"
VID=$("$H" f2mkdangle $IMG_D | sed -n 's/.*victim_id=//p')
[ -n "$VID" ] || fail "victim id"
"$H" f2sabotage $IMG_D "$VID" || fail "f2sabotage"
# the cut: the survivor is hidden at open (the log is loud about it)
$B/invf-ls $IMG_D >"$WORK/ls-d.log" 2>"$WORK/ls-d.err" || true
grep -q "survivorS.bin" "$WORK/ls-d.log" && { cat "$WORK/ls-d.log"; fail "dangling survivor is listed"; }
grep -q "bystanderB.bin" "$WORK/ls-d.log" || { cat "$WORK/ls-d.log"; fail "bystander lost too"; }
grep -q "record cut: survivorS.bin" "$WORK/ls-d.err" \
    || { cat "$WORK/ls-d.err"; fail "open did not log the cut"; }
set +e
$B/invf-fsck $IMG_D >"$WORK/fsck-d.log" 2>&1
FSCK_RC=$?
set -e
[ $FSCK_RC -eq 3 ] || { cat "$WORK/fsck-d.log"; fail "fsck rc=$FSCK_RC (want 3)"; }
grep -q "l2p_miss: survivorS.bin" "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not name the lost file"; }
grep -q "l2p misses:   3 " "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not count 3 lost segments"; }
grep -q "lost files:   1" "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not count the lost file"; }
# verify --deep agrees: the hidden file is not served, nothing is corrupt
$B/invf-verify $IMG_D --deep >"$WORK/verify-d.log" 2>&1 \
    || { cat "$WORK/verify-d.log"; fail "verify D not clean"; }
grep -q " 0 corrupt," "$WORK/verify-d.log" || fail "verify D reported corrupt"
# fsck -f: quarantine; the final fsck comes back OK with the loss listed
set +e
$B/invf-fsck $IMG_D -f >"$WORK/fsck-df.log" 2>&1
FSCKF_RC=$?
set -e
[ $FSCKF_RC -eq 3 ] || { cat "$WORK/fsck-df.log"; fail "fsck -f rc=$FSCKF_RC (want 3)"; }
grep -q "file quarantined" "$WORK/fsck-df.log" \
    || { cat "$WORK/fsck-df.log"; fail "fsck -f did not quarantine"; }
$B/invf-fsck $IMG_D >"$WORK/fsck-d2.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-d2.log" \
    || { cat "$WORK/fsck-d2.log"; fail "fsck not OK post-quarantine"; }
grep -q "lost files:   0" "$WORK/fsck-d2.log" \
    || { cat "$WORK/fsck-d2.log"; fail "the loss was not quarantined away"; }
echo "   fsck rc=3 + names the loss, file hidden at open, -f quarantines -> OK"

echo "== leg E: swept-container rename moves the sibling payload =="
$B/invf-mkfs $IMG_E 0.125 >"$WORK/mkfs-e.log" || fail "mkfs E"
python3 - "$WORK/t.tar" <<'PY'
import io, sys, tarfile
out = io.BytesIO()
with tarfile.open(fileobj=out, mode="w") as tf:
    for name in ("m1.txt", "m2.txt"):
        data = ("the quick brown fox jumps over lazy dogs\n"
                "int static return while for struct char void\n") * 400
        ti = tarfile.TarInfo(name)
        ti.size = len(data)
        tf.addfile(ti, io.BytesIO(data.encode()))
open(sys.argv[1], "wb").write(out.getvalue())
PY
"$H" f2cp $IMG_E "$WORK/t.tar" t.tar || fail "f2cp"
# sweep it into the TARR container shape (decomposition + part batching)
$B/invf-sweep $IMG_E >"$WORK/sweep-e.log" 2>&1 || { cat "$WORK/sweep-e.log"; fail "sweep E"; }
# the TARR decomposition is proven by the CONTAINER{TARR} class stamp
[ "$($B/meta_probe $IMG_E --heat t.tar 2>/dev/null | sed -n 's/^class=\([0-9a-z]*\).*/\1/p')" = "3" ] \
    || { cat "$WORK/sweep-e.log"; fail "t.tar not CONTAINER post-sweep"; }
"$H" f2mv $IMG_E t.tar t2.tar "$WORK/t.tar" || fail "f2mv"
$B/invf-fsck $IMG_E >"$WORK/fsck-e.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-e.log" || { cat "$WORK/fsck-e.log"; fail "fsck E not OK"; }
set +e
$B/invf-verify $IMG_E --deep >"$WORK/verify-e.log" 2>&1
VE=$?
set -e
[ $VE -eq 0 ] || { cat "$WORK/verify-e.log"; fail "verify E"; }
grep -q " 0 corrupt," "$WORK/verify-e.log" || fail "verify E reported corrupt"
echo "   swept container renamed: bit-exact in-session + after reopen, fsck/verify clean"

# Legs F-I were the WP22d journal legs: legacy->slot migration on first
# flush, mid-compaction crash at each of the three commit points, mid-
# migration crash, an old volume migrating under new binaries, and the
# bitmap/record divergence the open-time guard reconciled. Every one of
# them drives the mapping journal -- its slot image, its selector flip,
# its replay, its legacy migration -- and every fixture they need is a
# volume in the format this build refuses to open. They are deleted with
# the journal (wp/purge-v2-l2p-journal); the recovery behaviour they were
# written for is covered on this format by legs A-E and by
# no_v2_surface_test.

echo "PASS: WP22c (flush/sync failure latch + rename/retire/fsck liveness)"
