#!/bin/bash
# test-flushfail.sh — WP22c e2e: the two durability bugs the dm-flakey
# tier found (tools/flakey/FINDINGS.md), reproduced deterministically on
# plain image files (no root/dm needed), plus the fsck/verify agreement
# invariant. Persistent regression suite.
#
#   Leg A (F1): the INVFS_SYNC_FAIL_AT hook simulates the leg-2 error
#   window: the Nth vol_sync of the process zeroes the un-barriered
#   inode-area tail (what a dropped writeback leaves behind) and reports
#   EIO. Asserts: the failure is LOUD at the failing sync, the volume
#   latches (later mutations refused), the append cursor is re-anchored
#   at the last barriered position, and after a clean close + reopen the
#   barriered file is present and bit-exact while the un-barriered one is
#   absent (complete-or-absent, never silently lost after an ack).
#
#   Leg B (F2 rename): a fast-path rename must kill the SOURCE name's own
#   record (the pre-fix tombstone named the shared id's newest record --
#   the copy -- and killed nothing at replay, leaving both names live).
#   Asserts in-session and post-reopen: source absent, target bit-exact.
#
#   Leg C (F2 shared-id retire): deleting one name of a hardlinked pair
#   must not drop the mappings the survivor resolves through (the old
#   retire dropped the shared id's L2P wholesale -> present-but-
#   unreadable). Asserts the survivor reads bit-exact in-session and
#   after reopen, fsck + verify clean.
#
#   Leg D (F2 fsck honesty): a live record whose mappings are gone (built
#   offline: hardlinked survivor + legacy tombstone + zeroed journal
#   tail -- the leg-5 artifact's shape) must be SEEN by fsck: l2p_miss
#   counted, the file named, rc=3 -- and verify --deep must say CORRUPT
#   for the same file. Pre-fix fsck reported OK with 0 misses.
#
#   Leg E (F2 container rename): renaming a swept container file (TARR:
#   num_children==0 but payload in "name!partN"/"name!recipe" siblings)
#   must take the sibling-aware slow path, not the hardlink fast path --
#   the hardlink would move the anchor and strand the recipe under the
#   old name (the renamed container never reads again). Asserts the
#   renamed container reads bit-exact in-session and after reopen.
#
# The engine harness is generated below and linked against the built
# engine objects (the test-astv2.sh convention). Run from the repo root
# after `make`. Uses /dev/shm like the other soak scripts; image paths
# are RELATIVE (blkio treats /dev/* as raw devices).
set -e
set -o pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
B=$REPO/bin
WORK=/dev/shm/wp22c
IMG_A=wp22c-a.img     # leg A: sync failure latch + re-anchor
IMG_B=wp22c-b.img     # leg B: rename kills the source name
IMG_C=wp22c-c.img     # leg C: shared-id retire keeps the survivor readable
IMG_D=wp22c-d.img     # leg D: fsck/verify agree on a dangling live record
IMG_E=wp22c-e.img     # leg E: swept-container rename moves the siblings
rm -rf "$WORK" && mkdir -p "$WORK"
cd /dev/shm
rm -f "$IMG_A" "$IMG_B" "$IMG_C" "$IMG_D" "$IMG_E"

fail() { echo "FAIL: $*" >&2; exit 1; }

# ---- the engine harness ------------------------------------------------
CORE="volume vol_cpack vol_png vol_seal vol_repair vol_rollback \
      vol_resize vol_fsck vol_crash vol_exer vol_dedupe vol_textzone \
      vol_heat vol_sweep vol_read vol_write vol_records vol_ast \
      vol_dirs vol_tier arc crc32c lz4 flacx tarx pngx blkio miniz blake3 \
      blake3_dispatch blake3_portable ppmd8 ppmd8enc ppmd8dec \
      ppmd_codec codec bcj_x86 rs"
OBJS=""
for m in $CORE; do OBJS="$OBJS $REPO/build/obj/$m.o"; done

cat > "$WORK/ff_harness.c" <<'EOF'
/* ff_harness.c — WP22c engine-level test driver (generated by
 * tools/test-flushfail.sh; links the engine objects, public API + the
 * on-disk structs for the offline sabotage leg). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "volume.h"
#include "invarifs.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

static void fill_pattern(uint8_t *b, size_t n, uint64_t seed)
{
    uint64_t x = seed ? seed : 0x9E3779B97F4A7C15ull;
    size_t i;
    for (i = 0; i < n; i++) {
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        b[i] = (uint8_t)(x >> 32);
    }
}

static void assert_file(invfs_volume *v, const char *name, size_t len,
                        uint64_t seed)
{
    uint64_t id = vol_find(v, name);
    uint8_t *buf = NULL, *want;
    size_t blen = 0;
    if (!id) die("assert_file: absent");
    if (vol_read_file(v, id, &buf, &blen) != 0) die("assert_file: read");
    if (blen != len) die("assert_file: size");
    want = malloc(len);
    if (!want) die("oom");
    fill_pattern(want, len, seed);
    if (memcmp(want, buf, len) != 0) die("assert_file: content mismatch");
    free(want);
    free(buf);
}

static uint64_t create_pattern(invfs_volume *v, const char *name,
                               size_t len, uint64_t seed)
{
    uint8_t *buf = malloc(len);
    uint64_t id;
    if (!buf) die("oom");
    fill_pattern(buf, len, seed);
    id = vol_create_file(v, name, buf, len);
    free(buf);
    if (!id) die("create_pattern");
    return id;
}

/* ---- leg A: failed barrier -> latch + re-anchor ----------------------- */
static int cmd_f1run(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t anchor;
    if (!v) die("open");
    /* pinned file: committed and barriered on the healthy device */
    create_pattern(v, "pin1.bin", 100 * 1024, 11);
    if (vol_sync(v) != 0) die("first sync failed on a healthy image");
    anchor = vol_inode_area_pos(v);
    /* the un-barriered file: committed, then the storm hits at the sync */
    create_pattern(v, "hole1.bin", 200 * 1024, 22);
    if (vol_sync(v) == 0)
        die("second sync succeeded despite INVFS_SYNC_FAIL_AT");
    /* loud at the failing op; latched from here on */
    if (vol_write_enabled(v))
        die("volume not latched after a failed sync");
    /* the append cursor must never sit past unpersisted bytes */
    if (vol_inode_area_pos(v) != anchor)
        die("append cursor not re-anchored at the last barrier");
    /* later mutations fail loudly instead of appending into the hole */
    if (vol_create_file(v, "post.bin", (const uint8_t *)"x", 1) != 0)
        die("create accepted on a latched volume");
    vol_close(v);
    printf("F1RUN-OK\n");
    return 0;
}

static int cmd_f1check(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    assert_file(v, "pin1.bin", 100 * 1024, 11);
    if (vol_find(v, "hole1.bin")) die("hole1.bin survived a failed sync");
    if (vol_find(v, "post.bin"))  die("post.bin exists");
    vol_close(v);
    printf("F1CHECK-OK\n");
    return 0;
}

/* ---- leg B: a fast-path rename retires the source's own record -------- */
static int cmd_f2rename(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "fileA.bin", 300 * 1024, 33);
    if (vol_rename(v, "fileA.bin", "fileB.bin") != 0) die("rename");
    /* in-session: the source name must be gone immediately */
    if (vol_find(v, "fileA.bin")) die("source name survived the rename");
    if (!vol_find(v, "fileB.bin")) die("target name missing after rename");
    vol_close(v);
    /* and the same after a full reopen (the on-disk tombstone must hit) */
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, "fileA.bin")) die("source name resurrected at reopen");
    assert_file(v, "fileB.bin", 300 * 1024, 33);
    vol_close(v);
    printf("F2RENAME-OK\n");
    return 0;
}

/* ---- leg C: a shared-id retire must keep the survivor's mappings ------ */
static int cmd_f2link(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "fileC.bin", 160 * 1024, 44);
    if (vol_hardlink(v, "fileC.bin", "linkC.bin") != 0) die("hardlink");
    if (vol_delete_file(v, "fileC.bin") != 0) die("delete");
    assert_file(v, "linkC.bin", 160 * 1024, 44);   /* in-session */
    vol_close(v);
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, "fileC.bin")) die("deleted name still present");
    assert_file(v, "linkC.bin", 160 * 1024, 44);   /* after replay */
    vol_close(v);
    printf("F2LINK-OK\n");
    return 0;
}

/* ---- leg D: build the dangling live record (the leg-5 shape) ---------- */
static int cmd_f2mkdangle(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t vid;
    if (!v) die("open");
    /* bystander FIRST: the victim's mappings must be the journal tail */
    create_pattern(v, "bystanderB.bin", 32 * 1024, 55);
    vid = create_pattern(v, "victimV.bin", 160 * 1024, 66);
    /* the survivor shares the victim's id (the rename fast path's shape) */
    if (vol_hardlink(v, "victimV.bin", "survivorS.bin") != 0)
        die("hardlink");
    vol_close(v);
    printf("F2MKDANGLE-OK victim_id=%llu\n", (unsigned long long)vid);
    return 0;
}

/* the drop-window analogue (WP22d: the on-disk journal is no longer
 * rewriteable test collateral, so the maps are dropped through the
 * engine): the victim's name is deleted (the shared-id guard keeps the
 * maps), then the shared id's mappings are UNMAP-journaled away. The
 * survivor's record stays live with no mappings -- exactly what the
 * leg-5 artifact held. */
static int cmd_f2sabotage(const char *img, uint64_t victim_id)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    const invfs_l2p_entry *t;
    size_t n = 0, i, nl = 0;
    uint64_t *lbas;
    if (!v) die("open");
    if (vol_delete_file(v, "victimV.bin") != 0) die("delete victim");
    t = vol_l2p(v, &n);
    lbas = malloc(n * sizeof *lbas);
    if (!lbas) die("oom");
    for (i = 0; i < n; i++)
        if (t[i].type == INVFS_JRN_MAP && t[i].inode == victim_id)
            lbas[nl++] = t[i].lba;
    if (!nl) die("no victim mappings found");
    for (i = 0; i < nl; i++)
        vol_l2p_remove(v, victim_id, lbas[i]);
    free(lbas);
    if (vol_flush(v) != 0) die("flush");
    vol_close(v);
    printf("F2SABOTAGE-OK\n");
    return 0;
}

/* ---- leg G: a compaction crash at each stage is consistent-cut -------- */
static int cmd_f3fill(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    /* the pinned file: committed and barriered BEFORE the crash run */
    create_pattern(v, "pinA.bin", 96 * 1024, 77);
    if (vol_sync(v) != 0) die("sync");
    vol_close(v);
    printf("F3FILL-OK\n");
    return 0;
}

/* with INVFS_JRN_FORCE_COMPACT=1 + INVFS_COMPACT_ABORT_AT set, the create
 * below dies SIGKILL mid-compaction (in its pre_record flush) */
static int cmd_f3crash(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "newB.bin", 128 * 1024, 88);
    vol_close(v);
    printf("F3CRASH-survived\n");   /* reached only when the hook is off */
    return 0;
}

static int cmd_f3check(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    /* the pinned file must be intact; the crashed one is present-and-
     * bit-exact or absent (complete-or-absent) -- never torn */
    assert_file(v, "pinA.bin", 96 * 1024, 77);
    if (vol_find(v, "newB.bin"))
        assert_file(v, "newB.bin", 128 * 1024, 88);
    vol_close(v);
    printf("F3CHECK-OK\n");
    return 0;
}

/* leg G2 variant: the pinned file came from the OLD (flat-log) binaries,
 * so only the crashed create's complete-or-absent is checked here; the
 * pinned file's bit-exactness is asserted by the leg via invf-cat | cmp */
static int cmd_f3checkb(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    if (vol_find(v, "newB.bin"))
        assert_file(v, "newB.bin", 128 * 1024, 88);
    vol_close(v);
    printf("F3CHECKB-OK\n");
    return 0;
}

/* ---- leg I: bitmap/journal divergence (WP22d open-time reconcile) ---- */
/* create the survivor, sync, and print the pba of its first segment (the
 * leg then clears that bit in the on-disk bitmap, simulating a bitmap
 * page dropped by a window while the journal append landed) */
static int cmd_f4mkdiv(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t id, pba = 0, len;
    size_t n = 0, i;
    const invfs_l2p_entry *t;
    if (!v) die("open");
    id = create_pattern(v, "survivorS.bin", 192 * 1024, 55);
    if (vol_sync(v) != 0) die("sync");
    t = vol_l2p(v, &n);
    for (i = 0; i < n; i++)
        if (t[i].type == INVFS_JRN_MAP && t[i].inode == id) {
            pba = t[i].pba; break;
        }
    if (!pba) die("no mapping for the survivor");
    printf("F4MKDIV-OK pba=%llu\n", (unsigned long long)pba);
    vol_close(v);
    return 0;
}

/* after the sabotage: the open must reconcile (the survivor's block is
 * forced used), then a fresh write must NOT be allocated on it */
static int cmd_f4checkdiv(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    assert_file(v, "survivorS.bin", 192 * 1024, 55);
    create_pattern(v, "attackerA.bin", 256 * 1024, 66);
    if (vol_sync(v) != 0) die("sync");
    assert_file(v, "survivorS.bin", 192 * 1024, 55);
    assert_file(v, "attackerA.bin", 256 * 1024, 66);
    vol_close(v);
    printf("F4CHECKDIV-OK\n");
    return 0;
}

/* ---- leg E: renaming a swept container keeps its siblings ----------- */
static int cmd_f2cp(const char *img, const char *host, const char *name)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    FILE *f;
    long len;
    uint8_t *buf;
    uint64_t id;
    if (!v) die("open");
    f = fopen(host, "rb");
    if (!f) die("host fopen");
    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||
        fseek(f, 0, SEEK_SET) != 0) die("host size");
    buf = malloc((size_t)len);
    if (!buf) die("oom");
    if (fread(buf, 1, (size_t)len, f) != (size_t)len) die("host read");
    fclose(f);
    id = vol_create_file(v, name, buf, (size_t)len);
    free(buf);
    if (!id) die("create");
    vol_close(v);
    printf("F2CP-OK\n");
    return 0;
}

/* rename must REFUSE (-4) while a sweep checkpoint is live: a rollback
 * would tear the pair (the copy decapitated, the source resurrected) */
static int cmd_f2mvrefuse(const char *img, const char *name,
                          const char *newname)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    int rc;
    if (!v) die("open");
    rc = vol_rename(v, name, newname);
    if (rc != -4) die("rename under a live checkpoint not refused");
    if (!vol_find(v, name)) die("source gone after a refused rename");
    if (vol_find(v, newname)) die("target appeared after a refused rename");
    vol_close(v);
    printf("F2MVREFUSE-OK\n");
    return 0;
}

/* rename name->newname, then bit-compare newname against the host file,
 * in-session and after a full reopen */
static int cmd_f2mv(const char *img, const char *name, const char *newname,
                    const char *host)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    FILE *f;
    long len;
    uint8_t *want, *got = NULL;
    size_t glen = 0;
    uint64_t id;
    int rc = 1;
    if (!v) die("open");
    f = fopen(host, "rb");
    if (!f) die("host fopen");
    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||
        fseek(f, 0, SEEK_SET) != 0) die("host size");
    want = malloc((size_t)len);
    if (!want) die("oom");
    if (fread(want, 1, (size_t)len, f) != (size_t)len) die("host read");
    fclose(f);
    if (vol_rename(v, name, newname) != 0) die("rename");
    if (vol_find(v, name)) die("container source name survived the rename");
    id = vol_find(v, newname);
    if (!id) die("renamed container missing");
    if (vol_read_file(v, id, &got, &glen) != 0)
        die("renamed container unreadable in-session");
    if (glen != (size_t)len || memcmp(want, got, glen) != 0)
        die("renamed container content mismatch in-session");
    free(got); got = NULL;
    vol_close(v);
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, name)) die("container source resurrected at reopen");
    id = vol_find(v, newname);
    if (!id) die("renamed container missing after reopen");
    if (vol_read_file(v, id, &got, &glen) != 0)
        die("renamed container unreadable after reopen");
    if (glen != (size_t)len || memcmp(want, got, glen) != 0)
        die("renamed container content mismatch after reopen");
    rc = 0;
    free(got);
    free(want);
    vol_close(v);
    if (rc == 0) printf("F2MV-OK\n");
    return rc;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: harness <cmd> <img> [args]\n");
        return 2;
    }
    if (strcmp(argv[1], "f1run") == 0 && argc == 3)
        return cmd_f1run(argv[2]);
    if (strcmp(argv[1], "f1check") == 0 && argc == 3)
        return cmd_f1check(argv[2]);
    if (strcmp(argv[1], "f2rename") == 0 && argc == 3)
        return cmd_f2rename(argv[2]);
    if (strcmp(argv[1], "f2link") == 0 && argc == 3)
        return cmd_f2link(argv[2]);
    if (strcmp(argv[1], "f2mkdangle") == 0 && argc == 3)
        return cmd_f2mkdangle(argv[2]);
    if (strcmp(argv[1], "f2sabotage") == 0 && argc == 4)
        return cmd_f2sabotage(argv[2], strtoull(argv[3], NULL, 0));
    if (strcmp(argv[1], "f3fill") == 0 && argc == 3)
        return cmd_f3fill(argv[2]);
    if (strcmp(argv[1], "f3crash") == 0 && argc == 3)
        return cmd_f3crash(argv[2]);
    if (strcmp(argv[1], "f3check") == 0 && argc == 3)
        return cmd_f3check(argv[2]);
    if (strcmp(argv[1], "f3checkb") == 0 && argc == 3)
        return cmd_f3checkb(argv[2]);
    if (strcmp(argv[1], "f4mkdiv") == 0 && argc == 3)
        return cmd_f4mkdiv(argv[2]);
    if (strcmp(argv[1], "f4checkdiv") == 0 && argc == 3)
        return cmd_f4checkdiv(argv[2]);
    if (strcmp(argv[1], "f2cp") == 0 && argc == 5)
        return cmd_f2cp(argv[2], argv[3], argv[4]);
    if (strcmp(argv[1], "f2mvrefuse") == 0 && argc == 5)
        return cmd_f2mvrefuse(argv[2], argv[3], argv[4]);
    if (strcmp(argv[1], "f2mv") == 0 && argc == 6)
        return cmd_f2mv(argv[2], argv[3], argv[4], argv[5]);
    fprintf(stderr, "bad args\n");
    return 2;
}
EOF

gcc -std=gnu11 -O2 -I$REPO/src-extracted/VFS/src -o "$WORK/ff_harness" \
    "$WORK/ff_harness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread \
    || fail "harness build"
H=$WORK/ff_harness

# ---- leg A: F1 -- failed sync latches + re-anchors ----------------------
echo "== leg A: failed barrier -> latch, re-anchor, complete-or-absent =="
$B/invf-mkfs $IMG_A 0.0625 >"$WORK/mkfs-a.log" || fail "mkfs A"
# the 2nd vol_sync of the process drops the un-barriered tail + reports EIO
INVFS_SYNC_FAIL_AT=2 "$H" f1run $IMG_A 2>"$WORK/f1run.log" || {
    cat "$WORK/f1run.log"; fail "f1run"; }
grep -q "latched" "$WORK/f1run.log" || { cat "$WORK/f1run.log"; fail "no latch log"; }
"$H" f1check $IMG_A || fail "f1check"
# recovery ladder: the volume stayed DIRTY (the latch persisted), the
# holed file's blocks are reclaimed, the volume ends structurally clean
# (fsck -f exits 3 -- "issues found" -- for the orphans it just freed;
# the honest answer to a real loss, not a crash)
set +e
$B/invf-fsck $IMG_A -f >"$WORK/fsck-a1.log" 2>&1
set -e
$B/invf-fsck $IMG_A >"$WORK/fsck-a2.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-a2.log" || { cat "$WORK/fsck-a2.log"; fail "fsck not clean post-recovery"; }
$B/invf-verify $IMG_A --deep >"$WORK/verify-a.log" 2>&1 || fail "verify A"
grep -q " 0 corrupt," "$WORK/verify-a.log" || fail "verify A reported corrupt"
echo "   pinned file bit-exact, holed file absent, latch held, fsck clean"

# ---- leg B: F2 -- the rename kills the source's own record --------------
echo "== leg B: fast-path rename retires the source name =="
$B/invf-mkfs $IMG_B 0.0625 >"$WORK/mkfs-b.log" || fail "mkfs B"
"$H" f2rename $IMG_B || fail "f2rename"
$B/invf-fsck $IMG_B >"$WORK/fsck-b.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-b.log" || { cat "$WORK/fsck-b.log"; fail "fsck B not OK"; }
$B/invf-verify $IMG_B --deep >"$WORK/verify-b.log" 2>&1 || fail "verify B"
grep -q " 0 corrupt," "$WORK/verify-b.log" || fail "verify B reported corrupt"
echo "   source name retired (in-session and after reopen), target bit-exact"

# ---- leg C: F2 -- shared-id retire keeps the survivor's mappings --------
echo "== leg C: shared-id retire keeps the survivor readable =="
$B/invf-mkfs $IMG_C 0.0625 >"$WORK/mkfs-c.log" || fail "mkfs C"
"$H" f2link $IMG_C || fail "f2link"
$B/invf-fsck $IMG_C >"$WORK/fsck-c.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-c.log" || { cat "$WORK/fsck-c.log"; fail "fsck C not OK"; }
$B/invf-verify $IMG_C --deep >"$WORK/verify-c.log" 2>&1 || fail "verify C"
grep -q " 0 corrupt," "$WORK/verify-c.log" || fail "verify C reported corrupt"
echo "   survivor bit-exact in-session and after reopen; fsck/verify clean"

# ---- leg D: WP22d -- the dangling live record is cut + quarantined ------
# (pre-WP22d this leg asserted fsck only COUNTED the miss; the consistent
# cut now HIDES the dangling record and fsck -f quarantines it, so the
# final fsck comes back OK with the loss explicitly listed)
echo "== leg D: fsck reports the cut, hides the dangling record, -f quarantines =="
$B/invf-mkfs $IMG_D 0.0625 >"$WORK/mkfs-d.log" || fail "mkfs D"
VID=$("$H" f2mkdangle $IMG_D | sed -n 's/.*victim_id=//p')
[ -n "$VID" ] || fail "victim id"
"$H" f2sabotage $IMG_D "$VID" || fail "f2sabotage"
# the cut: the survivor is hidden at open (the log is loud about it)
$B/invf-ls $IMG_D >"$WORK/ls-d.log" 2>"$WORK/ls-d.err" || true
grep -q "survivorS.bin" "$WORK/ls-d.log" && { cat "$WORK/ls-d.log"; fail "dangling survivor is listed"; }
grep -q "bystanderB.bin" "$WORK/ls-d.log" || { cat "$WORK/ls-d.log"; fail "bystander lost too"; }
grep -q "l2p cut: survivorS.bin" "$WORK/ls-d.err" \
    || { cat "$WORK/ls-d.err"; fail "open did not log the cut"; }
set +e
$B/invf-fsck $IMG_D >"$WORK/fsck-d.log" 2>&1
FSCK_RC=$?
set -e
[ $FSCK_RC -eq 3 ] || { cat "$WORK/fsck-d.log"; fail "fsck rc=$FSCK_RC (want 3)"; }
grep -q "l2p_miss: survivorS.bin" "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not name the lost file"; }
grep -q "l2p misses:   3 " "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not count 3 lost segments"; }
grep -q "lost files:   1" "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not count the lost file"; }
# verify --deep agrees: the hidden file is not served, nothing is corrupt
$B/invf-verify $IMG_D --deep >"$WORK/verify-d.log" 2>&1 \
    || { cat "$WORK/verify-d.log"; fail "verify D not clean"; }
grep -q " 0 corrupt," "$WORK/verify-d.log" || fail "verify D reported corrupt"
# fsck -f: quarantine; the final fsck comes back OK with the loss listed
set +e
$B/invf-fsck $IMG_D -f >"$WORK/fsck-df.log" 2>&1
FSCKF_RC=$?
set -e
[ $FSCKF_RC -eq 3 ] || { cat "$WORK/fsck-df.log"; fail "fsck -f rc=$FSCKF_RC (want 3)"; }
grep -q "file quarantined" "$WORK/fsck-df.log" \
    || { cat "$WORK/fsck-df.log"; fail "fsck -f did not quarantine"; }
$B/invf-fsck $IMG_D >"$WORK/fsck-d2.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-d2.log" \
    || { cat "$WORK/fsck-d2.log"; fail "fsck not OK post-quarantine"; }
grep -q "lost files:   0" "$WORK/fsck-d2.log" \
    || { cat "$WORK/fsck-d2.log"; fail "the loss was not quarantined away"; }
echo "   fsck rc=3 + names the loss, file hidden at open, -f quarantines -> OK"

echo "== leg E: swept-container rename moves the sibling payload =="
$B/invf-mkfs $IMG_E 0.125 >"$WORK/mkfs-e.log" || fail "mkfs E"
python3 - "$WORK/t.tar" <<'PY'
import io, sys, tarfile
out = io.BytesIO()
with tarfile.open(fileobj=out, mode="w") as tf:
    for name in ("m1.txt", "m2.txt"):
        data = ("the quick brown fox jumps over lazy dogs\n"
                "int static return while for struct char void\n") * 400
        ti = tarfile.TarInfo(name)
        ti.size = len(data)
        tf.addfile(ti, io.BytesIO(data.encode()))
open(sys.argv[1], "wb").write(out.getvalue())
PY
"$H" f2cp $IMG_E "$WORK/t.tar" t.tar || fail "f2cp"
# sweep it into the TARR container shape (decomposition + part batching)
$B/invf-sweep $IMG_E >"$WORK/sweep-e.log" 2>&1 || { cat "$WORK/sweep-e.log"; fail "sweep E"; }
# the TARR decomposition is proven by the CONTAINER{TARR} class stamp
[ "$($B/meta_probe $IMG_E --heat t.tar 2>/dev/null | sed -n 's/^class=\([0-9a-z]*\).*/\1/p')" = "3" ] \
    || { cat "$WORK/sweep-e.log"; fail "t.tar not CONTAINER post-sweep"; }
# WP21+WP22c: while the sweep's checkpoint is live a rename must REFUSE
# (a rollback would tear the pair), and it must not move anything
"$H" f2mvrefuse $IMG_E t.tar t2.tar || fail "f2mvrefuse"
# resolve the checkpoint (realize), then the rename moves everything
$B/invf-sweep $IMG_E --realize >"$WORK/realize-e.log" 2>&1 \
    || { cat "$WORK/realize-e.log"; fail "realize E"; }
"$H" f2mv $IMG_E t.tar t2.tar "$WORK/t.tar" || fail "f2mv"
$B/invf-fsck $IMG_E >"$WORK/fsck-e.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-e.log" || { cat "$WORK/fsck-e.log"; fail "fsck E not OK"; }
set +e
$B/invf-verify $IMG_E --deep >"$WORK/verify-e.log" 2>&1
VE=$?
set -e
[ $VE -eq 0 ] || { cat "$WORK/verify-e.log"; fail "verify E"; }
grep -q " 0 corrupt," "$WORK/verify-e.log" || fail "verify E reported corrupt"
echo "   swept container renamed: bit-exact in-session + after reopen, fsck/verify clean"

# ---- leg F: WP22d journal migration (legacy -> slots on first flush) ---
echo "== leg F: legacy journal migrates on first flush, slots work =="
IMGF=wp22d-f.img
rm -f "$IMGF"
$B/invf-mkfs $IMGF 0.0625 >"$WORK/mkfs-f.log" || fail "mkfs F"
# a fresh volume is born legacy (pad2 == 0)
python3 - "$IMGF" <<'PY' || fail "fresh volume not legacy (pad2)"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x90)
pad2 = struct.unpack_from("<I", sb, 0x8C)[0]
sys.exit(0 if pad2 == 0 else 1)
PY
"$H" f2rename $IMGF || fail "f2rename F"   # create + rename (mutations)
# after the first flush the volume is slotted (pad2 == 2 -> slot 1; the
# legacy flat log's start lives in slot 0's region, so migration images
# into slot 1 to keep the fallback intact until the flip lands)
python3 - "$IMGF" <<'PY' || fail "volume did not migrate to slots"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x90)
pad2 = struct.unpack_from("<I", sb, 0x8C)[0]
sys.exit(0 if pad2 == 2 else 1)
PY
INVFS_DEBUG=1 $B/invf-ls $IMGF 2>/dev/null | grep -q "slot 1" \
    || fail "replay did not pick slot 1"
$B/invf-fsck $IMGF >"$WORK/fsck-f.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-f.log" || { cat "$WORK/fsck-f.log"; fail "fsck F not OK"; }
echo "   born legacy -> migrated to slot 1 on first flush; fsck OK"

# ---- leg G: WP22d mid-compaction crash is consistent-cut ---------------
echo "== leg G: mid-compaction crash (image/barrier/flip) -> consistent cut =="
IMGG=wp22d-g.img
for stage in image barrier1 flip; do
    rm -f "$IMGG"
    $B/invf-mkfs $IMGG 0.0625 >"$WORK/mkfs-g.log" || fail "mkfs G"
    "$H" f3fill $IMGG || fail "f3fill $stage"
    set +e
    INVFS_JRN_FORCE_COMPACT=1 INVFS_COMPACT_ABORT_AT=$stage \
        "$H" f3crash $IMGG >"$WORK/f3crash-$stage.log" 2>&1
    RC=$?
    set -e
    [ "$RC" = "137" ] || { cat "$WORK/f3crash-$stage.log"; fail "G($stage): expected SIGKILL (137), got $RC"; }
    "$H" f3check $IMGG || fail "f3check $stage"
    # the killed create's orphaned blocks are reclaimed by the ladder's
    # fsck -f (orphan reclaim), then the volume is clean
    $B/invf-fsck $IMGG -f >"$WORK/fsck-gf-$stage.log" 2>&1 || true
    $B/invf-fsck $IMGG >"$WORK/fsck-g-$stage.log" 2>&1 || true
    grep -q "^OK$" "$WORK/fsck-g-$stage.log" \
        || { cat "$WORK/fsck-g-$stage.log"; fail "fsck G($stage) not OK"; }
    echo "   stage=$stage: pinned file intact, crashed file complete-or-absent, fsck OK"
done

# ---- leg G2: WP22d crash mid-MIGRATION (legacy -> slot 1) ---------------
# The legacy fixture must be built by binaries that predate the slot
# format (a new-binary flush would migrate immediately): OLDB points at a
# pre-WP22d build (make it with: git worktree add /tmp/invfs-base HEAD~ &&
# make -C /tmp/invfs-base). Skipped (not failed) when absent.
OLDB=${OLDB:-/tmp/invfs-base/bin}
if [ -x "$OLDB/invf-mkfs" ] && [ -x "$OLDB/invf-cp" ]; then
    echo "== leg G2: crash mid-migration (image/barrier/flip) -> legacy fallback =="
    IMGG2=wp22d-g2.img
    for stage in image barrier1 flip; do
        rm -f "$IMGG2"
        $OLDB/invf-mkfs $IMGG2 0.0625 >"$WORK/mkfs-g2.log" || fail "mkfs G2"
        # pinned file, durable under the OLD (flat-log) binaries
        echo "pinned content $(date +%s)" > "$WORK/pin.txt"
        $OLDB/invf-cp $IMGG2 "$WORK/pin.txt" pinA.txt >/dev/null || fail "G2 cp"
        python3 - "$IMGG2" <<'PY' || fail "G2 fixture not legacy (pad2)"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x90)
sys.exit(0 if struct.unpack_from("<I", sb, 0x8C)[0] == 0 else 1)
PY
        # the new binary's first flush migrates legacy -> slot 1; die inside
        set +e
        INVFS_COMPACT_ABORT_AT=$stage \
            "$H" f3crash $IMGG2 >"$WORK/f3crash-g2-$stage.log" 2>&1
        RC=$?
        set -e
        [ "$RC" = "137" ] || { cat "$WORK/f3crash-g2-$stage.log"; fail "G2($stage): expected SIGKILL (137), got $RC"; }
        # the pinned file must be intact whichever side of the flip we died on
        "$H" f3checkb $IMGG2 >"$WORK/f3check-g2-$stage.log" 2>&1 || true
        grep -q F3CHECKB-OK "$WORK/f3check-g2-$stage.log" \
            || { cat "$WORK/f3check-g2-$stage.log"; fail "G2($stage) check"; }
        $B/invf-cat $IMGG2 pinA.txt "$WORK/pin.out" >/dev/null 2>&1 \
            || fail "G2($stage): pinA.txt unreadable"
        cmp -s "$WORK/pin.txt" "$WORK/pin.out" \
            || fail "G2($stage): pinA.txt not bit-exact"
        $B/invf-fsck $IMGG2 -f >"$WORK/fsck-g2f-$stage.log" 2>&1 || true
        $B/invf-fsck $IMGG2 >"$WORK/fsck-g2-$stage.log" 2>&1 || true
        grep -q "^OK$" "$WORK/fsck-g2-$stage.log" \
            || { cat "$WORK/fsck-g2-$stage.log"; fail "fsck G2($stage) not OK"; }
        echo "   stage=$stage: migration crash -> pinned file intact, fsck OK"
    done
    # stage "torndrop": the deterministic silent-drop shape -- kill at the
    # image barrier, then CORRUPT the slot-1 image bytes (what drop_writes
    # leaves behind when the barrier lies). pad2 still says legacy, so
    # replay must fall back to the intact flat log, not the torn slot.
    rm -f "$IMGG2"
    $OLDB/invf-mkfs $IMGG2 0.0625 >"$WORK/mkfs-g2.log" || fail "mkfs G2t"
    echo "pinned content $(date +%s)" > "$WORK/pin.txt"
    $OLDB/invf-cp $IMGG2 "$WORK/pin.txt" pinA.txt >/dev/null || fail "G2t cp"
    set +e
    INVFS_COMPACT_ABORT_AT=barrier1 \
        "$H" f3crash $IMGG2 >"$WORK/f3crash-g2-td.log" 2>&1
    RC=$?
    set -e
    [ "$RC" = "137" ] || { cat "$WORK/f3crash-g2-td.log"; fail "G2(torndrop): expected SIGKILL, got $RC"; }
    python3 - "$IMGG2" <<'PY' || fail "G2t sabotage"
import struct, sys
img = sys.argv[1]
with open(img, "r+b") as f:
    sb = f.read(0x90)
    mzs, = struct.unpack_from("<Q", sb, 0x28)   # metadata_zone_start
    tb,  = struct.unpack_from("<Q", sb, 0x20)   # total_blocks
    bm_blocks = (tb // 8 + 4095) // 4096
    slot1 = (mzs + bm_blocks + 4096) * 4096     # slot 1 header block
    f.seek(slot1)
    hdr = f.read(28)
    assert hdr[0:4] == b"JRN0", "slot-1 header missing"
    image_bytes, = struct.unpack_from("<Q", hdr, 12)
    assert image_bytes > 0
    f.seek(slot1 + 4096)                        # the image's first page
    f.write(b"\xAA" * 4096)                     # ...dropped mid-flight
PY
    "$H" f3checkb $IMGG2 >"$WORK/f3check-g2-td.log" 2>&1 || true
    grep -q F3CHECKB-OK "$WORK/f3check-g2-td.log" \
        || { cat "$WORK/f3check-g2-td.log"; fail "G2(torndrop) check"; }
    grep -q "pre-migration flat log" "$WORK/f3check-g2-td.log" \
        || { cat "$WORK/f3check-g2-td.log"; fail "G2(torndrop): legacy fallback not taken"; }
    $B/invf-cat $IMGG2 pinA.txt "$WORK/pin.out" >/dev/null 2>&1 \
        || fail "G2(torndrop): pinA.txt unreadable"
    cmp -s "$WORK/pin.txt" "$WORK/pin.out" \
        || fail "G2(torndrop): pinA.txt not bit-exact"
    $B/invf-fsck $IMGG2 -f >"$WORK/fsck-g2f-td.log" 2>&1 || true
    $B/invf-fsck $IMGG2 >"$WORK/fsck-g2-td.log" 2>&1 || true
    grep -q "^OK$" "$WORK/fsck-g2-td.log" \
        || { cat "$WORK/fsck-g2-td.log"; fail "fsck G2(torndrop) not OK"; }
    echo "   stage=torndrop: torn slot-1 image -> legacy flat-log fallback, pinned file intact, fsck OK"
else
    echo "== leg G2: SKIPPED (no pre-WP22d binaries at $OLDB) =="
fi

# ---- leg H: WP22d old-volume migration (built by pre-WP22d binaries) ---
# A volume fully written by the OLD (flat-log) binaries -- import, sweep,
# a delete -- must mount under the NEW binaries, migrate the journal on
# its first flush, sweep, and stay bit-exact throughout. Same OLDB gate
# as leg G2.
if [ -x "$OLDB/invf-mkfs" ] && [ -x "$OLDB/invf-sweep" ]; then
    echo "== leg H: pre-WP22d volume mounts, migrates, sweeps, bit-exact =="
    IMGH=wp22d-h.img
    rm -f "$IMGH"
    mkdir -p "$WORK/hgen"
    python3 - "$WORK/hgen" <<'PY' || fail "H gen"
import os, random, sys
rng = random.Random(22)
d = sys.argv[1]
for i in range(6):
    with open(os.path.join(d, "h%d.bin" % i), "wb") as f:
        f.write(os.urandom(rng.randrange(30000, 300000)))
with open(os.path.join(d, "note.txt"), "w") as f:
    f.write("pre-WP22d volume\n" * 40)
PY
    $OLDB/invf-mkfs $IMGH 0.0625 >"$WORK/mkfs-h.log" || fail "mkfs H"
    for f in "$WORK/hgen"/*; do
        $OLDB/invf-cp $IMGH "$f" "$(basename "$f")" >/dev/null || fail "H cp $f"
    done
    $OLDB/invf-sweep $IMGH >"$WORK/sweep-h-old.log" 2>&1 || fail "H old sweep"
    # (the old sweep's retires leave UNMAPs in the flat log -- the
    #  trickiest shape a migration can inherit)
    python3 - "$IMGH" <<'PY' || fail "H fixture not legacy"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x90)
sys.exit(0 if struct.unpack_from("<I", sb, 0x8C)[0] == 0 else 1)
PY
    # NEW binaries: content bit-exact before any new-binary write
    $B/invf-cat $IMGH h3.bin "$WORK/h3.out" >/dev/null 2>&1 || fail "H cat h3"
    cmp -s "$WORK/hgen/h3.bin" "$WORK/h3.out" || fail "H h3 mismatch pre-migration"
    # NOTE: there is no read-only probe of the pre-migration state here --
    # the WP19 heat path dirties+flushes even a pure read at close, and
    # that flush is exactly what migrates the journal. The migration is
    # what the rest of the leg exercises.
    # the first mutating session migrates: sweep under the NEW binaries
    $B/invf-sweep $IMGH >"$WORK/sweep-h-new.log" 2>&1 || fail "H new sweep"
    python3 - "$IMGH" <<'PY' || fail "H: no slot selector after the new sweep"
import struct, sys
sb = open(sys.argv[1], "rb").read(0x90)
sys.exit(0 if struct.unpack_from("<I", sb, 0x8C)[0] in (1, 2) else 1)
PY
    for f in "$WORK/hgen"/*; do
        n=$(basename "$f")
        $B/invf-cat $IMGH "$n" "$WORK/h.out" >/dev/null 2>&1 || fail "H cat $n post-migration"
        cmp -s "$f" "$WORK/h.out" || fail "H $n mismatch post-migration"
    done
    $B/invf-verify $IMGH --deep >"$WORK/verify-h.log" 2>&1 || fail "H verify"
    grep -q " 0 corrupt," "$WORK/verify-h.log" || fail "H verify corrupt"
    $B/invf-fsck $IMGH >"$WORK/fsck-h.log" 2>&1 || true
    grep -q "^OK$" "$WORK/fsck-h.log" || { cat "$WORK/fsck-h.log"; fail "fsck H not OK"; }
    echo "   pre-WP22d volume: mount + migrate + sweep + verify all bit-exact"
else
    echo "== leg H: SKIPPED (no pre-WP22d binaries at $OLDB) =="
fi

# ---- leg I: WP22d bitmap/journal divergence reconcile at open ---------
# A drop window can take a flush's bitmap pages and spare its journal
# append; the disk bitmap then calls a MAPPED block free, and the next
# allocation would hand it out from under its live file (the leg-5
# soak's clobbered-segment case). vol_open reconciles the one-sided
# direction: every journal-mapped block is forced used (never cleared).
echo "== leg I: a dropped bitmap bit is reconciled at open, no clobber =="
IMGI=wp22d-i.img
rm -f "$IMGI"
$B/invf-mkfs $IMGI 0.0625 >"$WORK/mkfs-i.log" || fail "mkfs I"
PBA=$("$H" f4mkdiv $IMGI | sed -n 's/F4MKDIV-OK pba=//p')
[ -n "$PBA" ] || fail "I: no survivor pba"
python3 - "$IMGI" "$PBA" <<'PY' || fail "I: sabotage"
import struct, sys
img, pba = sys.argv[1], int(sys.argv[2])
with open(img, "r+b") as f:
    sb = f.read(0x90)
    mzs, = struct.unpack_from("<Q", sb, 0x28)
    f.seek(mzs * 4096 + pba // 8)
    byte = f.read(1)[0]
    assert byte & (1 << (pba % 8)), "bit not set pre-sabotage"
    f.seek(mzs * 4096 + pba // 8)
    f.write(bytes([byte & ~(1 << (pba % 8))]))
PY
# the open inside f4checkdiv must log the divergence repair
"$H" f4checkdiv $IMGI >"$WORK/f4check.log" 2>&1 || { cat "$WORK/f4check.log"; fail "f4checkdiv"; }
grep -q "bitmap/journal divergence" "$WORK/f4check.log" \
    || { cat "$WORK/f4check.log"; fail "I: open did not reconcile the dropped bit"; }
$B/invf-fsck $IMGI >"$WORK/fsck-i.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-i.log" || { cat "$WORK/fsck-i.log"; fail "fsck I not OK"; }
echo "   mapped block's dropped used-bit repaired at open; attacker write went elsewhere; fsck OK"


echo "PASS: WP22c (flush/sync failure latch + rename/retire/fsck liveness)"
