#!/bin/bash
# test-flushfail.sh — WP22c e2e: the two durability bugs the dm-flakey
# tier found (tools/flakey/FINDINGS.md), reproduced deterministically on
# plain image files (no root/dm needed), plus the fsck/verify agreement
# invariant. Persistent regression suite.
#
#   Leg A (F1): the INVFS_SYNC_FAIL_AT hook simulates the leg-2 error
#   window: the Nth vol_sync of the process zeroes the un-barriered
#   inode-area tail (what a dropped writeback leaves behind) and reports
#   EIO. Asserts: the failure is LOUD at the failing sync, the volume
#   latches (later mutations refused), the append cursor is re-anchored
#   at the last barriered position, and after a clean close + reopen the
#   barriered file is present and bit-exact while the un-barriered one is
#   absent (complete-or-absent, never silently lost after an ack).
#
#   Leg B (F2 rename): a fast-path rename must kill the SOURCE name's own
#   record (the pre-fix tombstone named the shared id's newest record --
#   the copy -- and killed nothing at replay, leaving both names live).
#   Asserts in-session and post-reopen: source absent, target bit-exact.
#
#   Leg C (F2 shared-id retire): deleting one name of a hardlinked pair
#   must not drop the mappings the survivor resolves through (the old
#   retire dropped the shared id's L2P wholesale -> present-but-
#   unreadable). Asserts the survivor reads bit-exact in-session and
#   after reopen, fsck + verify clean.
#
#   Leg D (F2 fsck honesty): a live record whose mappings are gone (built
#   offline: hardlinked survivor + legacy tombstone + zeroed journal
#   tail -- the leg-5 artifact's shape) must be SEEN by fsck: l2p_miss
#   counted, the file named, rc=3 -- and verify --deep must say CORRUPT
#   for the same file. Pre-fix fsck reported OK with 0 misses.
#
#   Leg E (F2 container rename): renaming a swept container file (TARR:
#   num_children==0 but payload in "name!partN"/"name!recipe" siblings)
#   must take the sibling-aware slow path, not the hardlink fast path --
#   the hardlink would move the anchor and strand the recipe under the
#   old name (the renamed container never reads again). Asserts the
#   renamed container reads bit-exact in-session and after reopen.
#
# The engine harness is generated below and linked against the built
# engine objects (the test-astv2.sh convention). Run from the repo root
# after `make`. Uses /dev/shm like the other soak scripts; image paths
# are RELATIVE (blkio treats /dev/* as raw devices).
set -e
set -o pipefail

REPO=/home/user/InvariantFS
B=$REPO/bin
WORK=/dev/shm/wp22c
IMG_A=wp22c-a.img     # leg A: sync failure latch + re-anchor
IMG_B=wp22c-b.img     # leg B: rename kills the source name
IMG_C=wp22c-c.img     # leg C: shared-id retire keeps the survivor readable
IMG_D=wp22c-d.img     # leg D: fsck/verify agree on a dangling live record
IMG_E=wp22c-e.img     # leg E: swept-container rename moves the siblings
rm -rf "$WORK" && mkdir -p "$WORK"
cd /dev/shm
rm -f "$IMG_A" "$IMG_B" "$IMG_C" "$IMG_D" "$IMG_E"

fail() { echo "FAIL: $*" >&2; exit 1; }

# ---- the engine harness ------------------------------------------------
CORE="volume vol_cpack vol_png vol_seal vol_repair vol_rollback \
      vol_resize vol_fsck vol_crash vol_exer vol_dedupe vol_textzone \
      vol_heat vol_sweep vol_read vol_write vol_records vol_ast \
      vol_dirs arc crc32c lz4 flacx tarx pngx blkio miniz blake3 \
      blake3_dispatch blake3_portable ppmd8 ppmd8enc ppmd8dec \
      ppmd_codec codec bcj_x86 rs"
OBJS=""
for m in $CORE; do OBJS="$OBJS $REPO/build/obj/$m.o"; done

cat > "$WORK/ff_harness.c" <<'EOF'
/* ff_harness.c — WP22c engine-level test driver (generated by
 * tools/test-flushfail.sh; links the engine objects, public API + the
 * on-disk structs for the offline sabotage leg). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "volume.h"
#include "invarifs.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

static void fill_pattern(uint8_t *b, size_t n, uint64_t seed)
{
    uint64_t x = seed ? seed : 0x9E3779B97F4A7C15ull;
    size_t i;
    for (i = 0; i < n; i++) {
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        b[i] = (uint8_t)(x >> 32);
    }
}

static void assert_file(invfs_volume *v, const char *name, size_t len,
                        uint64_t seed)
{
    uint64_t id = vol_find(v, name);
    uint8_t *buf = NULL, *want;
    size_t blen = 0;
    if (!id) die("assert_file: absent");
    if (vol_read_file(v, id, &buf, &blen) != 0) die("assert_file: read");
    if (blen != len) die("assert_file: size");
    want = malloc(len);
    if (!want) die("oom");
    fill_pattern(want, len, seed);
    if (memcmp(want, buf, len) != 0) die("assert_file: content mismatch");
    free(want);
    free(buf);
}

static uint64_t create_pattern(invfs_volume *v, const char *name,
                               size_t len, uint64_t seed)
{
    uint8_t *buf = malloc(len);
    uint64_t id;
    if (!buf) die("oom");
    fill_pattern(buf, len, seed);
    id = vol_create_file(v, name, buf, len);
    free(buf);
    if (!id) die("create_pattern");
    return id;
}

/* ---- leg A: failed barrier -> latch + re-anchor ----------------------- */
static int cmd_f1run(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t anchor;
    if (!v) die("open");
    /* pinned file: committed and barriered on the healthy device */
    create_pattern(v, "pin1.bin", 100 * 1024, 11);
    if (vol_sync(v) != 0) die("first sync failed on a healthy image");
    anchor = vol_inode_area_pos(v);
    /* the un-barriered file: committed, then the storm hits at the sync */
    create_pattern(v, "hole1.bin", 200 * 1024, 22);
    if (vol_sync(v) == 0)
        die("second sync succeeded despite INVFS_SYNC_FAIL_AT");
    /* loud at the failing op; latched from here on */
    if (vol_write_enabled(v))
        die("volume not latched after a failed sync");
    /* the append cursor must never sit past unpersisted bytes */
    if (vol_inode_area_pos(v) != anchor)
        die("append cursor not re-anchored at the last barrier");
    /* later mutations fail loudly instead of appending into the hole */
    if (vol_create_file(v, "post.bin", (const uint8_t *)"x", 1) != 0)
        die("create accepted on a latched volume");
    vol_close(v);
    printf("F1RUN-OK\n");
    return 0;
}

static int cmd_f1check(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    assert_file(v, "pin1.bin", 100 * 1024, 11);
    if (vol_find(v, "hole1.bin")) die("hole1.bin survived a failed sync");
    if (vol_find(v, "post.bin"))  die("post.bin exists");
    vol_close(v);
    printf("F1CHECK-OK\n");
    return 0;
}

/* ---- leg B: a fast-path rename retires the source's own record -------- */
static int cmd_f2rename(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "fileA.bin", 300 * 1024, 33);
    if (vol_rename(v, "fileA.bin", "fileB.bin") != 0) die("rename");
    /* in-session: the source name must be gone immediately */
    if (vol_find(v, "fileA.bin")) die("source name survived the rename");
    if (!vol_find(v, "fileB.bin")) die("target name missing after rename");
    vol_close(v);
    /* and the same after a full reopen (the on-disk tombstone must hit) */
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, "fileA.bin")) die("source name resurrected at reopen");
    assert_file(v, "fileB.bin", 300 * 1024, 33);
    vol_close(v);
    printf("F2RENAME-OK\n");
    return 0;
}

/* ---- leg C: a shared-id retire must keep the survivor's mappings ------ */
static int cmd_f2link(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    if (!v) die("open");
    create_pattern(v, "fileC.bin", 160 * 1024, 44);
    if (vol_hardlink(v, "fileC.bin", "linkC.bin") != 0) die("hardlink");
    if (vol_delete_file(v, "fileC.bin") != 0) die("delete");
    assert_file(v, "linkC.bin", 160 * 1024, 44);   /* in-session */
    vol_close(v);
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, "fileC.bin")) die("deleted name still present");
    assert_file(v, "linkC.bin", 160 * 1024, 44);   /* after replay */
    vol_close(v);
    printf("F2LINK-OK\n");
    return 0;
}

/* ---- leg D: build the dangling live record (the leg-5 shape) ---------- */
static int cmd_f2mkdangle(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t vid;
    if (!v) die("open");
    /* bystander FIRST: the victim's mappings must be the journal tail */
    create_pattern(v, "bystanderB.bin", 32 * 1024, 55);
    vid = create_pattern(v, "victimV.bin", 160 * 1024, 66);
    /* the survivor shares the victim's id (the rename fast path's shape) */
    if (vol_hardlink(v, "victimV.bin", "survivorS.bin") != 0)
        die("hardlink");
    vol_close(v);
    printf("F2MKDANGLE-OK victim_id=%llu\n", (unsigned long long)vid);
    return 0;
}

/* offline sabotage (volume CLOSED): zero the victim's journal entries
 * (replay stops at the first one) and append a legacy kill-by-id
 * tombstone for the victim's name. The survivor's record stays live with
 * no mappings -- exactly what the leg-5 artifact holds. */
static int cmd_f2sabotage(const char *img, uint64_t victim_id)
{
    FILE *f = fopen(img, "r+b");
    invfs_superblock sb;
    uint64_t bitmap_blocks, journal_off, ia_off, ia_end, jp, p;
    if (!f) die("fopen");
    if (fread(&sb, sizeof sb, 1, f) != 1) die("sb read");
    bitmap_blocks = (sb.total_blocks / 8 + INVFS_BLOCK_SIZE - 1) /
                    INVFS_BLOCK_SIZE;
    journal_off = (sb.metadata_zone_start + bitmap_blocks) *
                  INVFS_BLOCK_SIZE;
    ia_off = (sb.metadata_zone_start + bitmap_blocks + INVFS_JOURNAL_BLOCKS)
             * (uint64_t)INVFS_BLOCK_SIZE;
    ia_end = (sb.metadata_zone_start + sb.metadata_zone_blocks) *
             (uint64_t)INVFS_BLOCK_SIZE;
    /* zero the journal from the victim's first entry on */
    jp = journal_off;
    for (;;) {
        invfs_l2p_entry e;
        if (fseek(f, (long)jp, SEEK_SET) != 0 ||
            fread(&e, sizeof e, 1, f) != 1) break;
        if (invfs_crc32c(&e, offsetof(invfs_l2p_entry, crc)) != e.crc)
            break;
        if (e.type == INVFS_JRN_MAP && e.inode == victim_id) {
            uint8_t z[sizeof(invfs_l2p_entry)];
            memset(z, 0, sizeof z);
            if (fseek(f, (long)jp, SEEK_SET) != 0 ||
                fwrite(z, sizeof z, 1, f) != 1) die("entry zero");
        }
        jp += sizeof e;
    }
    /* append the legacy tombstone at the inode-area tail */
    p = ia_off;
    for (;;) {
        invfs_inode_rec rh;
        uint8_t *rec;
        uint32_t crc_stored;
        if (p + sizeof rh + 4 > ia_end) die("area full");
        if (fseek(f, (long)p, SEEK_SET) != 0 ||
            fread(&rh, sizeof rh, 1, f) != 1) break;
        if (rh.magic != INODE_REC_MAGIC && rh.magic != TOMBSTONE_MAGIC)
            break;
        if (rh.rec_len < sizeof rh || p + rh.rec_len + 4 > ia_end)
            die("area scan hit a bad record");
        rec = malloc(rh.rec_len);
        if (!rec) die("oom");
        if (fseek(f, (long)p, SEEK_SET) != 0 ||
            fread(rec, rh.rec_len, 1, f) != 1 ||
            fread(&crc_stored, 4, 1, f) != 1) die("rec read");
        if (invfs_crc32c(rec, rh.rec_len) != crc_stored) break;
        free(rec);
        p += rh.rec_len + 4;
    }
    {
        invfs_inode_rec rec;
        uint32_t crc;
        memset(&rec, 0, sizeof rec);
        rec.magic = TOMBSTONE_MAGIC;
        rec.rec_len = (uint32_t)sizeof rec;
        rec.inode_id = victim_id;
        rec.file_size = 0;              /* legacy kill-by-id */
        rec.name_len = 11;
        memcpy(rec.name, "victimV.bin", 11);
        crc = invfs_crc32c(&rec, sizeof rec);
        if (fseek(f, (long)p, SEEK_SET) != 0 ||
            fwrite(&rec, sizeof rec, 1, f) != 1 ||
            fwrite(&crc, 4, 1, f) != 1) die("tombstone write");
    }
    fclose(f);
    printf("F2SABOTAGE-OK\n");
    return 0;
}

/* ---- leg E: renaming a swept container keeps its siblings ----------- */
static int cmd_f2cp(const char *img, const char *host, const char *name)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    FILE *f;
    long len;
    uint8_t *buf;
    uint64_t id;
    if (!v) die("open");
    f = fopen(host, "rb");
    if (!f) die("host fopen");
    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||
        fseek(f, 0, SEEK_SET) != 0) die("host size");
    buf = malloc((size_t)len);
    if (!buf) die("oom");
    if (fread(buf, 1, (size_t)len, f) != (size_t)len) die("host read");
    fclose(f);
    id = vol_create_file(v, name, buf, (size_t)len);
    free(buf);
    if (!id) die("create");
    vol_close(v);
    printf("F2CP-OK\n");
    return 0;
}

/* rename must REFUSE (-4) while a sweep checkpoint is live: a rollback
 * would tear the pair (the copy decapitated, the source resurrected) */
static int cmd_f2mvrefuse(const char *img, const char *name,
                          const char *newname)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    int rc;
    if (!v) die("open");
    rc = vol_rename(v, name, newname);
    if (rc != -4) die("rename under a live checkpoint not refused");
    if (!vol_find(v, name)) die("source gone after a refused rename");
    if (vol_find(v, newname)) die("target appeared after a refused rename");
    vol_close(v);
    printf("F2MVREFUSE-OK\n");
    return 0;
}

/* rename name->newname, then bit-compare newname against the host file,
 * in-session and after a full reopen */
static int cmd_f2mv(const char *img, const char *name, const char *newname,
                    const char *host)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    FILE *f;
    long len;
    uint8_t *want, *got = NULL;
    size_t glen = 0;
    uint64_t id;
    int rc = 1;
    if (!v) die("open");
    f = fopen(host, "rb");
    if (!f) die("host fopen");
    if (fseek(f, 0, SEEK_END) != 0 || (len = ftell(f)) < 0 ||
        fseek(f, 0, SEEK_SET) != 0) die("host size");
    want = malloc((size_t)len);
    if (!want) die("oom");
    if (fread(want, 1, (size_t)len, f) != (size_t)len) die("host read");
    fclose(f);
    if (vol_rename(v, name, newname) != 0) die("rename");
    if (vol_find(v, name)) die("container source name survived the rename");
    id = vol_find(v, newname);
    if (!id) die("renamed container missing");
    if (vol_read_file(v, id, &got, &glen) != 0)
        die("renamed container unreadable in-session");
    if (glen != (size_t)len || memcmp(want, got, glen) != 0)
        die("renamed container content mismatch in-session");
    free(got); got = NULL;
    vol_close(v);
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (vol_find(v, name)) die("container source resurrected at reopen");
    id = vol_find(v, newname);
    if (!id) die("renamed container missing after reopen");
    if (vol_read_file(v, id, &got, &glen) != 0)
        die("renamed container unreadable after reopen");
    if (glen != (size_t)len || memcmp(want, got, glen) != 0)
        die("renamed container content mismatch after reopen");
    rc = 0;
    free(got);
    free(want);
    vol_close(v);
    if (rc == 0) printf("F2MV-OK\n");
    return rc;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: harness <cmd> <img> [args]\n");
        return 2;
    }
    if (strcmp(argv[1], "f1run") == 0 && argc == 3)
        return cmd_f1run(argv[2]);
    if (strcmp(argv[1], "f1check") == 0 && argc == 3)
        return cmd_f1check(argv[2]);
    if (strcmp(argv[1], "f2rename") == 0 && argc == 3)
        return cmd_f2rename(argv[2]);
    if (strcmp(argv[1], "f2link") == 0 && argc == 3)
        return cmd_f2link(argv[2]);
    if (strcmp(argv[1], "f2mkdangle") == 0 && argc == 3)
        return cmd_f2mkdangle(argv[2]);
    if (strcmp(argv[1], "f2sabotage") == 0 && argc == 4)
        return cmd_f2sabotage(argv[2], strtoull(argv[3], NULL, 0));
    if (strcmp(argv[1], "f2cp") == 0 && argc == 5)
        return cmd_f2cp(argv[2], argv[3], argv[4]);
    if (strcmp(argv[1], "f2mvrefuse") == 0 && argc == 5)
        return cmd_f2mvrefuse(argv[2], argv[3], argv[4]);
    if (strcmp(argv[1], "f2mv") == 0 && argc == 6)
        return cmd_f2mv(argv[2], argv[3], argv[4], argv[5]);
    fprintf(stderr, "bad args\n");
    return 2;
}
EOF

gcc -std=gnu11 -O2 -I$REPO/src-extracted/VFS/src -o "$WORK/ff_harness" \
    "$WORK/ff_harness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread \
    || fail "harness build"
H=$WORK/ff_harness

# ---- leg A: F1 -- failed sync latches + re-anchors ----------------------
echo "== leg A: failed barrier -> latch, re-anchor, complete-or-absent =="
$B/invf-mkfs $IMG_A 0.0625 >"$WORK/mkfs-a.log" || fail "mkfs A"
# the 2nd vol_sync of the process drops the un-barriered tail + reports EIO
INVFS_SYNC_FAIL_AT=2 "$H" f1run $IMG_A 2>"$WORK/f1run.log" || {
    cat "$WORK/f1run.log"; fail "f1run"; }
grep -q "latched" "$WORK/f1run.log" || { cat "$WORK/f1run.log"; fail "no latch log"; }
"$H" f1check $IMG_A || fail "f1check"
# recovery ladder: the volume stayed DIRTY (the latch persisted), the
# holed file's blocks are reclaimed, the volume ends structurally clean
# (fsck -f exits 3 -- "issues found" -- for the orphans it just freed;
# the honest answer to a real loss, not a crash)
set +e
$B/invf-fsck $IMG_A -f >"$WORK/fsck-a1.log" 2>&1
set -e
$B/invf-fsck $IMG_A >"$WORK/fsck-a2.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-a2.log" || { cat "$WORK/fsck-a2.log"; fail "fsck not clean post-recovery"; }
$B/invf-verify $IMG_A --deep >"$WORK/verify-a.log" 2>&1 || fail "verify A"
grep -q " 0 corrupt," "$WORK/verify-a.log" || fail "verify A reported corrupt"
echo "   pinned file bit-exact, holed file absent, latch held, fsck clean"

# ---- leg B: F2 -- the rename kills the source's own record --------------
echo "== leg B: fast-path rename retires the source name =="
$B/invf-mkfs $IMG_B 0.0625 >"$WORK/mkfs-b.log" || fail "mkfs B"
"$H" f2rename $IMG_B || fail "f2rename"
$B/invf-fsck $IMG_B >"$WORK/fsck-b.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-b.log" || { cat "$WORK/fsck-b.log"; fail "fsck B not OK"; }
$B/invf-verify $IMG_B --deep >"$WORK/verify-b.log" 2>&1 || fail "verify B"
grep -q " 0 corrupt," "$WORK/verify-b.log" || fail "verify B reported corrupt"
echo "   source name retired (in-session and after reopen), target bit-exact"

# ---- leg C: F2 -- shared-id retire keeps the survivor's mappings --------
echo "== leg C: shared-id retire keeps the survivor readable =="
$B/invf-mkfs $IMG_C 0.0625 >"$WORK/mkfs-c.log" || fail "mkfs C"
"$H" f2link $IMG_C || fail "f2link"
$B/invf-fsck $IMG_C >"$WORK/fsck-c.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-c.log" || { cat "$WORK/fsck-c.log"; fail "fsck C not OK"; }
$B/invf-verify $IMG_C --deep >"$WORK/verify-c.log" 2>&1 || fail "verify C"
grep -q " 0 corrupt," "$WORK/verify-c.log" || fail "verify C reported corrupt"
echo "   survivor bit-exact in-session and after reopen; fsck/verify clean"

# ---- leg D: F2 -- fsck sees what verify sees ----------------------------
echo "== leg D: fsck counts the dangling live record (agrees with verify) =="
$B/invf-mkfs $IMG_D 0.0625 >"$WORK/mkfs-d.log" || fail "mkfs D"
VID=$("$H" f2mkdangle $IMG_D | sed -n 's/.*victim_id=//p')
[ -n "$VID" ] || fail "victim id"
"$H" f2sabotage $IMG_D "$VID" || fail "f2sabotage"
set +e
$B/invf-fsck $IMG_D >"$WORK/fsck-d.log" 2>&1
FSCK_RC=$?
set -e
[ $FSCK_RC -eq 3 ] || { cat "$WORK/fsck-d.log"; fail "fsck rc=$FSCK_RC (want 3)"; }
grep -q "l2p_miss: survivorS.bin" "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not name the survivor"; }
grep -q "l2p misses:   3 " "$WORK/fsck-d.log" \
    || { cat "$WORK/fsck-d.log"; fail "fsck did not count 3 lost segments"; }
set +e
$B/invf-verify $IMG_D --deep >"$WORK/verify-d.log" 2>&1
VERIFY_RC=$?
set -e
[ $VERIFY_RC -ne 0 ] || fail "verify clean on a dangling record"
grep -q "CORRUPT: survivorS.bin" "$WORK/verify-d.log" \
    || { cat "$WORK/verify-d.log"; fail "verify did not name the survivor"; }
grep -q "bystanderB.bin" "$WORK/verify-d.log" || true   # context only
echo "   fsck rc=3 + l2p_miss survivorS.bin, verify CORRUPT: agree"

# ---- leg E: F2 -- renaming a swept container keeps its siblings --------
echo "== leg E: swept-container rename moves the sibling payload =="
$B/invf-mkfs $IMG_E 0.125 >"$WORK/mkfs-e.log" || fail "mkfs E"
python3 - "$WORK/t.tar" <<'PY'
import io, sys, tarfile
out = io.BytesIO()
with tarfile.open(fileobj=out, mode="w") as tf:
    for name in ("m1.txt", "m2.txt"):
        data = ("the quick brown fox jumps over lazy dogs\n"
                "int static return while for struct char void\n") * 400
        ti = tarfile.TarInfo(name)
        ti.size = len(data)
        tf.addfile(ti, io.BytesIO(data.encode()))
open(sys.argv[1], "wb").write(out.getvalue())
PY
"$H" f2cp $IMG_E "$WORK/t.tar" t.tar || fail "f2cp"
# sweep it into the TARR container shape (decomposition + part batching)
$B/invf-sweep $IMG_E >"$WORK/sweep-e.log" 2>&1 || { cat "$WORK/sweep-e.log"; fail "sweep E"; }
# the TARR decomposition is proven by the CONTAINER{TARR} class stamp
[ "$($B/meta_probe $IMG_E --heat t.tar 2>/dev/null | sed -n 's/^class=\([0-9a-z]*\).*/\1/p')" = "3" ] \
    || { cat "$WORK/sweep-e.log"; fail "t.tar not CONTAINER post-sweep"; }
# WP21+WP22c: while the sweep's checkpoint is live a rename must REFUSE
# (a rollback would tear the pair), and it must not move anything
"$H" f2mvrefuse $IMG_E t.tar t2.tar || fail "f2mvrefuse"
# resolve the checkpoint (realize), then the rename moves everything
$B/invf-sweep $IMG_E --realize >"$WORK/realize-e.log" 2>&1 \
    || { cat "$WORK/realize-e.log"; fail "realize E"; }
"$H" f2mv $IMG_E t.tar t2.tar "$WORK/t.tar" || fail "f2mv"
$B/invf-fsck $IMG_E >"$WORK/fsck-e.log" 2>&1 || true
grep -q "^OK$" "$WORK/fsck-e.log" || { cat "$WORK/fsck-e.log"; fail "fsck E not OK"; }
set +e
$B/invf-verify $IMG_E --deep >"$WORK/verify-e.log" 2>&1
VE=$?
set -e
[ $VE -eq 0 ] || { cat "$WORK/verify-e.log"; fail "verify E"; }
grep -q " 0 corrupt," "$WORK/verify-e.log" || fail "verify E reported corrupt"
echo "   swept container renamed: bit-exact in-session + after reopen, fsck/verify clean"

echo "PASS: WP22c (flush/sync failure latch + rename/retire/fsck liveness)"
