#!/bin/bash
# test-astv2.sh — WP22a e2e: AST recipe header v2 (H2, >4 GB files),
# the READONLY space-latch return path (H5), and the fsck -f l2p_miss
# gate (H6). Persistent regression suite.
#
#   Leg A (H2): a 4 GB + 2 segments file written through an engine write
#   session (the same path FUSE .write funnels into -- the mount leg of
#   that size is the same code at 100x the wall time, so the suite stays
#   at the engine level per the WP22a brief). The file is mostly
#   zero-filled (a truncate-extended hole: InvariantFS materializes holes
#   as real zero segments, there is no sparse storage) plus three
#   deterministic random windows: head, straddling the 4 GB boundary,
#   tail. Asserts: the big record carries a v2 recipe header, a small
#   file in the same volume keeps v1 (byte-stable rule), all windows
#   read back bit-exact after a reopen, holes read as zeros, and
#   fsck / verify --deep / invf-stat are clean.
#
#   Leg B (H5): fill a small volume until the ordinary write path
#   refuses (reserve hit), drain the reserve via a seal (parity allocs
#   dip into it) until the hard_min floor latches the volume READONLY,
#   then delete files -- the latch must auto-release above
#   hard_min + 2% and the release must persist across a reopen.
#
#   Leg C (H6): destroy one journal mapping + its bitmap bits offline
#   (a torn journal tail: pure l2p_miss, no orphans/missing), mark the
#   volume DIRTY, then invf-fsck -f must repair anyway (the old gate
#   refused and the volume stayed read-only forever), listing the victim
#   by name + lost range. The victim keeps failing reads with EIO per
#   missing segment; the volume mounts RW after the repair.
#
# The engine harness is generated below and linked against the built
# engine objects (the codec_test pattern). Run from the repo root after
# `make`. Uses /dev/shm like the other soak scripts; image paths are
# RELATIVE (blkio treats /dev/* as raw devices).
set -e
set -o pipefail

REPO=/home/user/InvariantFS
B=$REPO/bin
WORK=/dev/shm/wp22a
IMG_A=wp22a-a.img     # leg A: v2 header
IMG_B=wp22a-b.img     # leg B: H5 latch
IMG_C=wp22a-c.img     # leg C: H6 l2p_miss
rm -rf "$WORK" && mkdir -p "$WORK"
cd /dev/shm
rm -f "$IMG_A" "$IMG_B" "$IMG_C"

fail() { echo "FAIL: $*" >&2; exit 1; }

# ---- the engine harness ------------------------------------------------
CORE="volume vol_cpack vol_png vol_seal vol_repair vol_rollback \
      vol_resize vol_fsck vol_crash vol_exer vol_dedupe vol_textzone \
      vol_heat vol_sweep vol_read vol_write vol_records vol_ast \
      vol_dirs arc crc32c lz4 flacx tarx pngx blkio miniz blake3 \
      blake3_dispatch blake3_portable ppmd8 ppmd8enc ppmd8dec \
      ppmd_codec codec bcj_x86 rs"
OBJS=""
for m in $CORE; do OBJS="$OBJS $REPO/build/obj/$m.o"; done

cat > "$WORK/astv2_harness.c" <<'EOF'
/* astv2_harness.c — WP22a engine-level test driver (generated by
 * tools/test-astv2.sh; links the engine objects, uses only the public
 * volume.h/invarifs.h API). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "volume.h"
#include "invarifs.h"

static void die(const char *m) { fprintf(stderr, "HARNESS-FAIL: %s\n", m); exit(1); }

/* deterministic incompressible-ish window content (xorshift64 stream) */
static void fill_pattern(uint8_t *b, size_t n, uint64_t seed)
{
    uint64_t x = seed ? seed : 0x9E3779B97F4A7C15ull;
    size_t i;
    for (i = 0; i < n; i++) {
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        b[i] = (uint8_t)(x >> 32);
    }
}

/* ---- leg A: window table shared by write-big / verify-big ---- */
#define FOUR_G 0x100000000ull
static uint64_t g_fsz;
static uint64_t win_off[3];
static const uint64_t win_len[3] = { 1u << 20, 512u << 10, 65536 + 13 };

static void win_setup(uint64_t fsz)
{
    g_fsz = fsz;
    win_off[0] = 0;                          /* head */
    win_off[1] = FOUR_G - 4096;              /* straddles the 4 GB line */
    win_off[2] = fsz - win_len[2];           /* tail to EOF (partial seg) */
}

static int cmd_write_big(const char *img, const char *name, uint64_t fsz)
{
    int err = 0, w;
    invfs_volume *v = vol_open(img, &err);
    invfs_wsession *ws = NULL;
    if (!v) die("open");
    if (!vol_write_begin(v, name, 1, &ws) || !ws) die("write_begin");
    if (vol_write_truncate(ws, fsz) != 0) die("truncate");
    win_setup(fsz);
    for (w = 0; w < 3; w++) {
        uint8_t *buf = malloc((size_t)win_len[w]);
        size_t done = 0;
        if (!buf) die("oom");
        fill_pattern(buf, (size_t)win_len[w], 0x1000 + (uint64_t)w);
        while (done < win_len[w]) {
            size_t piece = (size_t)(win_len[w] - done);
            if (piece > (1u << 20)) piece = 1u << 20;
            if (vol_write_range(ws, win_off[w] + done, buf + done, piece) != 0)
                die("write_range");
            done += piece;
        }
        free(buf);
    }
    if (vol_write_commit(ws) != 0) die("commit");
    vol_write_abort(ws);   /* committed: frees the session memory only */
    /* a small file in the same volume must keep the v1 header */
    {
        uint8_t small[4096];
        fill_pattern(small, sizeof small, 7);
        if (!vol_create_file(v, "small.bin", small, sizeof small))
            die("small create");
    }
    if (vol_flush(v) != 0) die("flush");
    vol_close(v);
    printf("WRITE-OK\n");
    return 0;
}

static int cmd_verify_big(const char *img, const char *name, uint64_t fsz,
                          uint64_t w2seed)
{
    int err = 0, w;
    invfs_volume *v = vol_open(img, &err);
    uint64_t id, got_sz = 0;
    if (!v) die("open");
    id = vol_find(v, name);
    if (!id) die("find");
    if (vol_stat_full(v, name, NULL, &got_sz, NULL) != 0 || got_sz != fsz)
        die("stat size mismatch");
    win_setup(fsz);
    /* the three written windows, bit-exact, in 64 KB ranged reads */
    for (w = 0; w < 3; w++) {
        uint8_t *want = malloc((size_t)win_len[w]);
        uint8_t *got  = malloc((size_t)win_len[w]);
        size_t done = 0;
        if (!want || !got) die("oom");
        /* after a rewrite leg the straddling window carries its new seed */
        fill_pattern(want, (size_t)win_len[w],
                     w == 1 && w2seed ? w2seed : 0x1000 + (uint64_t)w);
        while (done < win_len[w]) {
            size_t piece = (size_t)(win_len[w] - done);
            int rc;
            if (piece > INVFS_SEGMENT_SIZE) piece = INVFS_SEGMENT_SIZE;
            rc = vol_read_range(v, id, win_off[w] + done, piece, got + done);
            if (rc != (int)piece) die("read_range short");
            done += piece;
        }
        if (memcmp(want, got, (size_t)win_len[w]) != 0)
            die("window content mismatch");
        free(want); free(got);
    }
    /* a hole between windows must read back as zeros */
    {
        uint8_t *z = malloc(1u << 20);
        size_t i;
        int rc = vol_read_range(v, id, 2ull << 30, 1u << 20, z);
        if (rc != (1 << 20)) die("hole read short");
        for (i = 0; i < (1u << 20); i++)
            if (z[i]) die("hole not zero");
        free(z);
    }
    vol_close(v);
    printf("VERIFY-OK\n");
    return 0;
}

/* rewrite-in-place leg: patch the straddling window of an EXISTING v2
 * file (no truncate): exercises wsession_load_old parsing the v2 recipe
 * and aliasing its 65k+ segments into the fork, then recommitting v2 */
static int cmd_rewrite_big(const char *img, const char *name, uint64_t fsz)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    invfs_wsession *ws = NULL;
    uint8_t *buf;
    size_t done = 0;
    if (!v) die("open");
    win_setup(fsz);
    if (!vol_write_begin(v, name, 0, &ws) || !ws) die("write_begin");
    buf = malloc((size_t)win_len[1]);
    if (!buf) die("oom");
    fill_pattern(buf, (size_t)win_len[1], 0xBEEF);
    while (done < win_len[1]) {
        size_t piece = (size_t)(win_len[1] - done);
        if (piece > (1u << 20)) piece = 1u << 20;
        if (vol_write_range(ws, win_off[1] + done, buf + done, piece) != 0)
            die("write_range");
        done += piece;
    }
    free(buf);
    if (vol_write_commit(ws) != 0) die("commit");
    vol_write_abort(ws);
    if (vol_flush(v) != 0) die("flush");
    vol_close(v);
    printf("REWRITE-OK\n");
    return 0;
}

/* print + check the recipe header of the live record for `name` */
static int cmd_hdrcheck(const char *img, const char *name, uint32_t want_ver)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t id, pos;
    uint32_t rl = 0, rec_rl = 0;
    invfs_ast_hdr ah;
    uint8_t *rec = NULL;
    int found = 0;
    if (!v) die("open");
    id = vol_find(v, name);
    if (!id) die("find");
    pos = vol_inode_area_start(v);
    for (;;) {
        uint32_t magic; uint64_t ino, fsz;
        uint64_t np = vol_inode_next(v, pos, &magic, &ino, &fsz,
                                     NULL, 0, &rl);
        if (!np) break;
        pos = np;
        if (magic != INODE_REC_MAGIC || ino != id) continue;
        free(rec);
        rec = malloc(rl);
        if (!rec || vol_read_raw(v, np - rl - 4, rec, rl) != 0)
            die("rec read");
        rec_rl = rl;   /* per-match: rl is overwritten by later records */
        found = 1;   /* newest match wins (append-only area) */
    }
    if (!found) die("record not found");
    if (invfs_ast_hdr_parse(rec + sizeof(invfs_inode_rec),
                            rec_rl - sizeof(invfs_inode_rec), &ah) != 0)
        die("header parse");
    printf("HDR %s version=%u file_size=%llu num_blocks=%u hdr_len=%u\n",
           name, ah.version, (unsigned long long)ah.file_size,
           ah.num_blocks, ah.hdr_len);
    free(rec);
    vol_close(v);
    return ah.version == want_ver ? 0 : 1;
}

/* ---- leg B: H5 latch fill / release ---- */
static int cmd_latch(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint8_t *mb;
    char nm[64];
    unsigned n = 0, d = 0;
    invfs_seal_report rep;
    if (!v) die("open");
    mb = malloc(1u << 20);
    if (!mb) die("oom");
    fill_pattern(mb, 1u << 20, 99);
    /* fill until the ordinary write path refuses (reserve floor reached) */
    for (;;) {
        snprintf(nm, sizeof nm, "f%05u", n);
        if (!vol_create_file(v, nm, mb, 1u << 20)) break;
        n++;
        if (n > 8192) die("fill loop runaway");
    }
    fprintf(stderr, "latch: fill stopped at %u files, free=%llu\n",
            n, (unsigned long long)vol_free_blocks_cached(v));
    /* drain the reserve: seal parity allocs dip into it (use_reserve=1)
     * until the hard_min floor latches the volume READONLY */
    if (vol_seal(v, 0, &rep) != 0)
        fprintf(stderr, "latch: seal rc!=0 (parity shortfall is expected)\n");
    if (!(vol_sb(v)->vol_flags & VOLF_READONLY))
        die("latch never fired");
    if (vol_write_enabled(v))
        die("write still enabled at latch");
    fprintf(stderr, "latch: ON free=%llu\n",
            (unsigned long long)vol_free_blocks_cached(v));
    /* H5: deletes must work on a latched volume -- each one frees blocks,
     * and above hard_min+2% the latch must auto-release */
    for (d = 0; d < n && !vol_write_enabled(v); d++) {
        snprintf(nm, sizeof nm, "f%05u", d);
        if (vol_delete_file(v, nm) != 0)
            die("delete refused on a latched volume");
    }
    if (!vol_write_enabled(v))
        die("latch never released");
    fprintf(stderr, "latch: released after %u deletes, free=%llu\n",
            d, (unsigned long long)vol_free_blocks_cached(v));
    /* headroom for the post-latch writes: the unlatch watermark is below
     * the ordinary reserve floor (hard_min + 2% < reserve + hard_min), so
     * free a few more files -- being RW is not the same as fitting a
     * 1 MB write's atomic precheck */
    for (; d < n && vol_free_blocks_cached(v) < 1600; d++) {
        snprintf(nm, sizeof nm, "f%05u", d);
        if (vol_delete_file(v, nm) != 0)
            die("headroom delete failed");
    }
    /* writes are accepted again */
    if (!vol_create_file(v, "post.bin", mb, 1u << 20))
        die("post-latch create failed");
    vol_close(v);
    /* the release must have persisted: reopen must come up RW */
    v = vol_open(img, &err);
    if (!v) die("reopen");
    if (!vol_write_enabled(v))
        die("latch persisted across reopen");
    if (!vol_create_file(v, "post2.bin", mb, 1u << 20))
        die("post-reopen create failed");
    vol_close(v);
    free(mb);
    printf("LATCH-OK files=%u deletes=%u\n", n, d);
    return 0;
}

/* ---- leg C: H6 l2p_miss ---- */
static int cmd_mkh6(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint8_t *buf;
    uint64_t vid;
    if (!v) die("open");
    buf = malloc(160 * 1024);
    if (!buf) die("oom");
    /* bystander FIRST: the victim's tail segment must be the journal's
     * last live entry for the sabotage to hit it */
    fill_pattern(buf, 32 * 1024, 55);
    if (!vol_create_file(v, "bystander.bin", buf, 32 * 1024))
        die("bystander create");
    fill_pattern(buf, 160 * 1024, 66);
    if (!vol_create_file(v, "victim.bin", buf, 160 * 1024))
        die("victim create");
    vid = vol_find(v, "victim.bin");
    if (!vid) die("victim find");
    vol_close(v);
    free(buf);
    printf("H6-MKOK victim_id=%llu\n", (unsigned long long)vid);
    return 0;
}

/* offline sabotage (volume CLOSED): zero the journal's last live entry
 * (the victim's tail segment) and clear its bitmap bits -- a torn journal
 * tail: pure l2p_miss, no orphans/missing -- then mark the volume DIRTY. */
static int cmd_sabotage(const char *img, uint64_t victim_id)
{
    FILE *f = fopen(img, "r+b");
    invfs_superblock sb;
    uint64_t bitmap_blocks, journal_off, jp;
    invfs_l2p_entry last;
    int found = 0;
    if (!f) die("fopen");
    if (fread(&sb, sizeof sb, 1, f) != 1) die("sb read");
    bitmap_blocks = (sb.total_blocks / 8 + INVFS_BLOCK_SIZE - 1) /
                    INVFS_BLOCK_SIZE;
    journal_off = (sb.metadata_zone_start + bitmap_blocks) *
                  INVFS_BLOCK_SIZE;
    jp = journal_off;
    for (;;) {
        invfs_l2p_entry e;
        if (fseek(f, (long)jp, SEEK_SET) != 0 ||
            fread(&e, sizeof e, 1, f) != 1) break;
        if (invfs_crc32c(&e, offsetof(invfs_l2p_entry, crc)) != e.crc)
            break;   /* terminator: end of the live journal */
        if (e.type == INVFS_JRN_MAP) { last = e; found = 1; }
        jp += sizeof e;
    }
    if (!found) die("no live journal entries");
    if (last.inode != victim_id) die("last entry is not the victim's");
    /* zero the entry (its CRC then fails: replay stops one entry short) */
    {
        uint8_t z[sizeof(invfs_l2p_entry)];
        memset(z, 0, sizeof z);
        if (fseek(f, (long)(jp - sizeof last), SEEK_SET) != 0 ||
            fwrite(z, sizeof z, 1, f) != 1) die("entry zero");
    }
    /* clear the lost segment's bitmap bits (no orphan would otherwise
     * mask the l2p_miss-only scenario) */
    {
        uint64_t b;
        for (b = last.pba; b < last.pba + (last.length ? last.length : 1);
             b++) {
            uint8_t byte;
            uint64_t off = sb.metadata_zone_start * INVFS_BLOCK_SIZE +
                           b / 8;
            if (fseek(f, (long)off, SEEK_SET) != 0 ||
                fread(&byte, 1, 1, f) != 1) die("bitmap read");
            byte &= (uint8_t)~(1u << (b % 8));
            if (fseek(f, (long)off, SEEK_SET) != 0 ||
                fwrite(&byte, 1, 1, f) != 1) die("bitmap write");
        }
    }
    /* mark DIRTY (the old H6 gate then refused repair forever) */
    sb.state = INVFS_STATE_DIRTY;
    sb.checksum = invfs_crc32c(&sb, offsetof(invfs_superblock, checksum));
    if (fseek(f, 0, SEEK_SET) != 0 ||
        fwrite(&sb, sizeof sb, 1, f) != 1) die("sb write");
    fclose(f);
    fprintf(stderr, "sabotage: killed (inode %llu, lba %llu, pba %llu, "
            "len %u)\n", (unsigned long long)last.inode,
            (unsigned long long)last.lba, (unsigned long long)last.pba,
            last.length);
    return 0;
}

static int cmd_verifyh6(const char *img)
{
    int err = 0;
    invfs_volume *v = vol_open(img, &err);
    uint64_t id;
    uint8_t *buf = NULL;
    size_t blen = 0;
    if (!v) die("open");
    if (vol_needs_recovery(v))
        die("still needs_recovery after fsck -f");
    if (!vol_write_enabled(v))
        die("not RW after fsck -f");
    /* the bystander must be bit-exact */
    id = vol_find(v, "bystander.bin");
    if (!id) die("bystander find");
    if (vol_read_file(v, id, &buf, &blen) != 0 || blen != 32 * 1024)
        die("bystander read");
    {
        uint8_t *want = malloc(32 * 1024);
        if (!want) die("oom");
        fill_pattern(want, 32 * 1024, 55);
        if (memcmp(want, buf, blen) != 0) die("bystander content mismatch");
        free(want);
    }
    free(buf);
    buf = NULL;
    /* the victim keeps failing reads with EIO per missing segment */
    id = vol_find(v, "victim.bin");
    if (!id) die("victim find");
    if (vol_read_file(v, id, &buf, &blen) == 0)
        die("victim read succeeded with a lost segment");
    /* and the volume takes new writes */
    {
        uint8_t post[4096];
        fill_pattern(post, sizeof post, 77);
        if (!vol_create_file(v, "postfix.bin", post, sizeof post))
            die("post-repair create failed");
    }
    vol_close(v);
    printf("H6-OK\n");
    return 0;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: harness <cmd> <img> [args]\n");
        return 2;
    }
    if (strcmp(argv[1], "write-big") == 0 && argc == 5)
        return cmd_write_big(argv[2], argv[3], strtoull(argv[4], NULL, 0));
    if (strcmp(argv[1], "verify-big") == 0 && argc >= 5)
        return cmd_verify_big(argv[2], argv[3], strtoull(argv[4], NULL, 0),
                              argc >= 6 ? strtoull(argv[5], NULL, 0) : 0);
    if (strcmp(argv[1], "rewrite-big") == 0 && argc == 5)
        return cmd_rewrite_big(argv[2], argv[3], strtoull(argv[4], NULL, 0));
    if (strcmp(argv[1], "hdrcheck") == 0 && argc == 5)
        return cmd_hdrcheck(argv[2], argv[3],
                            (uint32_t)strtoul(argv[4], NULL, 0));
    if (strcmp(argv[1], "latch") == 0 && argc == 3)
        return cmd_latch(argv[2]);
    if (strcmp(argv[1], "mkh6") == 0 && argc == 3)
        return cmd_mkh6(argv[2]);
    if (strcmp(argv[1], "sabotage") == 0 && argc == 4)
        return cmd_sabotage(argv[2], strtoull(argv[3], NULL, 0));
    if (strcmp(argv[1], "verifyh6") == 0 && argc == 3)
        return cmd_verifyh6(argv[2]);
    fprintf(stderr, "bad args\n");
    return 2;
}
EOF

gcc -std=gnu11 -O2 -I$REPO/src-extracted/VFS/src -o "$WORK/astv2_harness" \
    "$WORK/astv2_harness.c" $OBJS -Wl,-l:libzstd.so.1 -lz -lpthread \
    || fail "harness build"
H=$WORK/astv2_harness

# ---- Leg A: AST recipe header v2 (H2) -----------------------------------
echo "== leg A: v2 recipe header (>4 GB file) =="
# 8 GB sparse image: the session's atomic-ENOSPC precheck prices the file
# at its uncompressed worst case (17 blocks per 64 KB segment), so the
# volume must hold ~4.6 GB of headroom; real consumption is ~260 MB
# (zero segments compress to nothing).
$B/invf-mkfs $IMG_A 8 >"$WORK/mkfs-a.log" || fail "mkfs A"
BIG=4296015872    # 4 GB + 1 MiB -> 65552 segments (> 0xFFFF too); the
                  # 512 KiB window at 4 GB - 4 KiB ends at 4 GB + 508 KiB,
                  # comfortably inside
"$H" write-big $IMG_A big.bin $BIG || fail "write-big"
"$H" verify-big $IMG_A big.bin $BIG || fail "verify-big"
"$H" hdrcheck $IMG_A big.bin 2   || fail "big.bin is not v2"
"$H" hdrcheck $IMG_A small.bin 1 || fail "small.bin is not v1"
# rewrite leg: patch the straddling window of the existing v2 file
# (session load_old parses the v2 recipe, aliases all 65k+ segments into
# the fork, recommits v2), then re-verify everything
"$H" rewrite-big $IMG_A big.bin $BIG || fail "rewrite-big"
"$H" hdrcheck $IMG_A big.bin 2 || fail "big.bin lost v2 across rewrite"
"$H" verify-big $IMG_A big.bin $BIG 0xBEEF || fail "verify-big after rewrite"
$B/invf-fsck $IMG_A >"$WORK/fsck-a.log" 2>&1 || fail "fsck A"
$B/invf-verify $IMG_A --deep >"$WORK/verify-a.log" 2>&1 \
    || { cat "$WORK/verify-a.log"; fail "verify --deep A"; }
grep -q "0 corrupt" "$WORK/verify-a.log" || fail "verify A reported corrupt"
$B/invf-stat $IMG_A >"$WORK/stat-a.log" 2>&1 || fail "invf-stat A"
echo "   big.bin $(stat -c%s $IMG_A) bytes image; verify: $(grep 'deep:' "$WORK/verify-a.log" | tail -1)"

# ---- Leg B: H5 READONLY latch return ------------------------------------
echo "== leg B: READONLY latch auto-release =="
$B/invf-mkfs $IMG_B 0.125 >"$WORK/mkfs-b.log" || fail "mkfs B"
"$H" latch $IMG_B 2>"$WORK/latch-b.log" || { cat "$WORK/latch-b.log"; fail "latch leg"; }
grep -q "READONLY: free=" "$WORK/latch-b.log" || fail "latch-on never logged"
grep -q "RW again" "$WORK/latch-b.log" || fail "latch release never logged"
$B/invf-fsck $IMG_B >"$WORK/fsck-b.log" 2>&1 || fail "fsck B (dirty after test)"
grep -q "OK" "$WORK/fsck-b.log" || { cat "$WORK/fsck-b.log"; fail "fsck B not OK"; }
echo "   $(grep LATCH-OK "$WORK/latch-b.log" 2>/dev/null || echo LATCH-OK)"

# ---- Leg C: H6 fsck -f with l2p_miss ------------------------------------
echo "== leg C: fsck -f proceeds with l2p_miss =="
$B/invf-mkfs $IMG_C 0.0625 >"$WORK/mkfs-c.log" || fail "mkfs C"
VID=$("$H" mkh6 $IMG_C | sed -n 's/.*victim_id=//p')
[ -n "$VID" ] || fail "victim id"
"$H" sabotage $IMG_C "$VID" 2>"$WORK/sabotage-c.log" || fail "sabotage"
# the volume is DIRTY + one l2p_miss; auto-recovery is disabled so the old
# gate would leave it read-only forever. The repair must proceed, list the
# victim by name + lost range, and come out CLEAN/RW. (rc 3 = "issues
# found" — the expected, honest answer to a real data loss; not a crash.)
set +e
INVFS_AUTO_RECOVER=0 $B/invf-fsck $IMG_C -f >"$WORK/fsck-c.log" 2>&1
FSCK_RC=$?
set -e
[ $FSCK_RC -eq 3 ] || { cat "$WORK/fsck-c.log"; fail "fsck -f rc=$FSCK_RC (want 3)"; }
grep -q "l2p_miss: victim.bin" "$WORK/fsck-c.log" \
    || { cat "$WORK/fsck-c.log"; fail "victim not listed by name"; }
grep -q "\[131072, 163840)" "$WORK/fsck-c.log" \
    || { cat "$WORK/fsck-c.log"; fail "lost range not listed"; }
"$H" verifyh6 $IMG_C || fail "verifyh6"
$B/invf-fsck $IMG_C >"$WORK/fsck-c2.log" 2>&1 || true
grep -q "state:        CLEAN" "$WORK/fsck-c2.log" \
    || { cat "$WORK/fsck-c2.log"; fail "state not CLEAN after repair"; }
echo "   fsck -f: repair proceeded, victim listed, volume RW"

echo "PASS: WP22a (astv2 + readonly-latch + fsck l2p_miss)"
